### ISSUE TITLE
"du"/"Du"

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#228]
https://www.duden.de/sprachwissen/sprachratgeber/Gross-oder-Kleinschreibung-von-duDu-und-ihrIhr

In der Regel werden die Formen des Anredepronomens du kleingeschrieben, ebenso dann auch die der Mehrzahl ihr. Die Kleinschreibung gilt darüber hinaus auch für die Formen der Possessivpronomen dein, euer und auch für deinesgleichen, deinerseits usw.

In Briefen (auch auf Ansichtskarten u. Ä.), E-Mails und SMS kann man allerdings auch großschreiben: „Liebe Elly, wir wünschen dir/Dir viel Erfolg [...]“ Allgemein gilt: In allen Textformen, in denen der Autor selbst den Leser persönlich anredet, kann man du/Du und die genannten Wörter großschreiben. Das gilt dann zum Beispiel für Zettelmitteilungen in WGs [...] und, und, und. In all diesen Fällen empfehlen wir übrigens die Großschreibung.

Umgekehrt heißt dies aber auch: **In der wörtlichen Rede (etwa in Erzählungen oder Romanen) werden du und die anderen genannten Wörter nie großgeschrieben**, da ja hier der Autor nicht den Leser anredet: „Ach, du bist gut integriert, lachte Moira, ich meine, du passt gut in die Landschaft“ (Sylvie Schenk: Der Gesang der Haut). Nicht großgeschrieben wird auch in Werbeanzeigen bzw. -plakaten, Editorials von Jugendzeitschriften oder in Fragebogen (z. B. bei schriftlich fixierten Prüfungsfragen), da es sich hier jeweils nicht um eine persönliche Anrede handelt.

**Comment by ToBeFree** [comment]
Ausnahme: Durchbruch der vierten Wand. Eine einzige Szene des Romans braucht das große "Du". :D

**Comment by yur-y** [comment]
Habe nun alle derartigen Fälle ersetzt (wir hatten es beide einige Male überlesen^^). In der Szene mit der vierten Wand war es lustigerweise kleingeschrieben.
Laut Duden sollte es ja streng genommen auch dort nicht groß geschrieben werden (weil die Anrede etwa in Werbeanzeigen nicht persönlich genug sei); ich bin aber stark dafür, die Regel zu brechen, um den gewünschten Effekt zu erzielen. Machen Werbeleute ja auch ;)

**Comment by ToBeFree** [comment]
Oh, danke :D Ja, sehe ich auch so. Ich habe früher nur nie darauf geachtet. Im Forum zu Schulzeiten fiel es mir meist nicht einmal auf...
