### ISSUE TITLE
Nüggät leitet das Familienunternehmen "seit 21 Generationen". Das ergibt keinen Sinn. 

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#237]
Niemand lebt 21 Generationen. Die Formulierung ist falsch.

**Comment by yur-y** [comment]
"Mein Name ist Dögöbörz Nüggät, ich leite dieses Familienunternehmen inzwischen in der 21. Generation."

#closeIfOK

**Comment by ToBeFree** [comment]
Oha, wie machst du das? 😮 👍
