### ISSUE TITLE
Website: Verkaufsinformationen-Entwurf

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#242]
_Dies ist ein ENTWURF. Das ist alles noch nicht gültig._

-----

_Alle Preisangaben ohne Gewähr: Dies ist kein Onlineshop, sondern die offizielle Informationsseite der Autoren. Wir verkaufen nichts, sondern erklären, wie man das Buch z.B. bei einer Buchhandlung oder bei Amazon bestellen kann._

-----

**Drei Fragen:**

1. Wie viel Geld sollen die Autoren erhalten?

- 0,00€: kostenloses PDF: (Link)
- 3,45€: Dankeschön. Hardcover-Buch direkt beim Verlag bestellen: (Link)
- 1,23€: Weiter zur nächsten Frage

2. Wann haben Sie das letzte Mal eine Buchhandlung von innen gesehen?<br>
_Diese Frage ist ernst gemeint._

Statten Sie der Buchhandlung in Ihrer Nähe einen kurzen Besuch ab.<br>
ISBN des Hardcover-Buches: 000-000-000-00-000-000<br>
Der Preis ist überall gleich: 25,99€<br>
Falls es einer Erwähnung bedarf: Diese Einkaufsmethode ist sogar versandkostenfrei. Wer hätte das gedacht?

Falls Sie daran wirklich kein Interesse haben, weiter zur nächsten Frage.

3. Glauben Sie eigentlich, dass Amazon weiterhin günstig bleibt, wenn Sie zum Konkurs aller Konkurrenten beitragen?

- Nein: Wie wäre es mit einer Bestellung bei Thalia? Link: 
- Ja: Ihnen ist ja wirklich nicht zu helfen. Nutzen Sie wenigstens die Gelegenheit, um eine Bewertung zu verfassen. ;) Amazon-Link:

**Comment by yur-y** [comment]
👍

**Comment by ToBeFree** [comment]
Das wird auf der Seite später etwas anders erscheinen, ohne die Geld-Betonung, denn es handelt sich nicht um ein Projekt mit Gewinnerzielungsabsicht, sondern eine sogenannte "Liebhaberei".
