### ISSUE TITLE
"unter anderem" statt "unter Anderem"! Ganz am Anfang der Datei bereits.

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#252]

**Comment by ToBeFree** [comment]
https://www.duden.de/rechtschreibung/unter_anderem

**Comment by yur-y** [comment]
Ist ja nur im Kommentar, oder? Habs trotzdem geändert.

**Comment by ToBeFree** [comment]
Stimmt :) Hätte aber einen schlechten ersten Eindruck gemacht. ^^
