### ISSUE TITLE
Eingangsszene: Quintus

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#254]
Quintus und das Lateinbuch stammen noch aus dem Original, in dem die Eingangsszene in der Schule spielt. Sie passen nun irgendwie nicht mehr so recht dorthin, selbst wenn Free oder Orakel Lateinstudent wäre (was aber auch nicht wirklich zu ihnen passt).

**Comment by ToBeFree** [comment]
Oh! :)

Hmm. Das ist allerdings... richtig...

Ich habe Mirco im Lateinunterricht kennengelernt. Sollen wir es als Osterei behalten?

**Comment by yur-y** [comment]
Hm, ich finde eine Unstimmigkeit gleich in der Eingangsszene nicht soo gut, würde es aber auch ungern komplett rausstreichen.

**Comment by ToBeFree** [comment]
Notfalls kommt es eben doch weg. Quintus bekommen wir bestimmt irgendwie wieder eingebaut, und sei es in Teil 2 als Comeback. Oder als beleidigter Nebenrollen-Schauspieler, der sich lautstark darüber ärgert, dass er aus der Schlüsselszene eines tollen Romans gestrichen wurde. :D

**Comment by ToBeFree** [comment]
Ach, Mist, der ganze Anfang baut doch darauf auf, dass Quintus tot umfällt.

Vorschlag: Problem aufschieben, das bekommen wir so schnell nicht behoben

**Comment by ToBeFree** [comment]
Bleibt, falls kein besserer Vorschlag kommt :)

Klassiker.
