### ISSUE TITLE
Hubschrauber stürzt über dem Meer ab? (S. 47-51)

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#257]
Eigentlich sind die drei ja gerade in einem Zug in der Nähe der deutsch-niederländischen Grenze. Dann kommt die Polizei, sie kapern deren Hubschrauber und der fliegt an der selben Stelle im Kreis und muss dann notlanden:

"Free war gerade an der spannendsten Stelle seines Buches angekommen. Er bekam erst dann wieder etwas mit, als der Hubschrauber auf Wasser abstürzte. Weil noch ein Fenster offen war [sic!], kam eine Welle hinein."

Jetzt sind sie anscheinend plötzlich irgendwo im Meer. Später werfen sie die wiedergekommenen Polizisten ins Wasser, tauschen dann im Wasser (!) den Boden aus und reparieren in aller Seelenruhe den kaputten Heli, während die Polizei...wo genau ist?

Ich finde sowieso, dass es tendenziell zu viel um Verfolgungsjagd - nächstes Fahrzeug - Verfolgungsjagd geht und bin fast versucht, die Szene einfach komplett rauszunehmen. Dann ginge aber natürlich auch Orakels "Meisterwerk" verloren...

**Comment by ToBeFree** [comment]
Witzigerweise ist die beschriebene Brücke übrigens die Müngstener Brücke (Restaurant-Beschreibung, 10 km/h). Ob das Sinn ergibt... wahrscheinlich nicht. 

Wie wäre es mit einer Verkürzung? Der Helikopter stürzt ab und die Freunde steigen sofort um... achso, Orakel muss ja den Boden zersägen. Na, das können wir doch wirklich nicht streichen. :)

Schwierig, schwierig 😨

**Comment by yur-y** [comment]
Ja, dachte ich mir schon :D
Ach ja, die Polizei versucht übrigens die ganze Zeit, zu zweit in den Heli zu kommen, wird aber "mehrere Male wieder hinausgeworfen". Hatte ich eben überlesen.

Vorschlag: Sie landen im Fluss, die Welle kommt weg und sie ziehen den Hubschrauber erst an Land? Die Polizei bleibt halt einfach so doof wie sie in der Szene jetzt ist?

**Comment by ToBeFree** [comment]
An Land ziehen! Wieso komme ich nicht auf sowas? 👍 😃
