### ISSUE TITLE
Überall: Monospace-Schrift grau statt schwarz gedruckt. "tiny" -> "small"?

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#258]
Möglicherweise ist es angebracht, die Monospace-Schrift auf **"small" statt "tiny"** zu setzen. Falls das nicht gut aussieht, müssen wir uns etwas anderes überlegen.

**Comment by yur-y** [comment]
Seit wir die eine Stelle in script-/footnotesize geändert haben, tritt die doch nur noch in so Computerausgaben und Ähnlichem in separaten Kästen/zwischen Linien auf, oder? Finde, da sieht es auch so nicht schlecht aus.

**Comment by ToBeFree** [comment]
Die Computerausgaben sind tatsächlich das Problem – genau die sind im gedruckten Buch nämlich wirklich unerwartet schwer zu lesen, weil die Buchdruckmaschine entweder eine zu geringe Auflösung hat oder den dünnen Text falsch interpretiert. :(
