### ISSUE TITLE
Seite 036: "in einer schwimmenden" -> "in einer schwimmenden Hochhausetage". Begründung siehe Kommentar

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#260]
Begründung/Kommentar: Auf Seite **38**, also 2 Seiten weiter, sagt der Notfall-Telefonhelfer, er kenne die Geschichte mit der schwimmenden Etage bereits. Das kann er noch gar nicht.

**Comment by yur-y** [comment]
Hatte ich schon gesehen, S. 36 durch "in einer schwimmenden Eta..." ersetzt. Danke! :)
