### ISSUE TITLE
Seite 062: "irgendetwas Interessantes in China" zusätzlich kursiv drucken?

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#265]

**Comment by yur-y** [comment]
Finde es so in Ordnung.

**Comment by ToBeFree** [comment]
Ok :) Ich hatte überlegt, dass dadurch (oder durch Anführungszeichen) klargestellt würde, dass das wörtlich der Auftrag des Autopiloten war. Folglich hat Orakel keine Ahnung, auf welcher Mauer der Helikopter auf einmal gelandet ist. 😊
