### ISSUE TITLE
Seite 066: "random Chinese insult": so okay? Besser ein deutschsprachiger Text? Besser eine echte chinesische Beleidigung als Osterei?

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#269]

**Comment by yur-y** [comment]
Hatte ich auch überlegt. Echte chinesische Beleidigung ginge ja höchstens als Transkription, weiß nicht, ob das dann noch so sinnvoll ist. Runde Klammern hatten wir aber sonst nicht in derartigen Stellen, oder?

**Comment by ToBeFree** [comment]
Ich finde die chinesischen Transkriptionen bei der Radio-Szene eigentlich sogar ganz nett und angenehm zu lesen 😊 

Runde Klammern - nunja, es ist eben die einzige derartige Stelle, daher gibt es kein Vorbild für die Formatierung.

Ganz ursprünglich gab es in den IA übrigens tatsächlich eine chinesische Beleidigung... "Idiot, Total Idiot" oder so. "Fouze Mafan, Duo Mafan, bei bu", meine ich mich zu erinnern. Könnte man wieder einbauen - aber dann versteht eben niemand mehr den Witz. Witzig ist es ja eher dadurch, dass die Eigenschaft als Beleidigung sofort für den Leser sichtbar ist.

**Comment by yur-y** [comment]
Hm, ich weiß nicht, wofür ich bin, entscheide Du. :)
