### ISSUE TITLE
Seite 070: Logik: "Schloss gesprengt"  =/=> "Die Wand, an der er gesessen hatte", hatte nun *unten*...

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#271]
"unten" einfach streichen?

**Comment by ToBeFree** [comment]
(Schlösser sind für gewöhnlich nicht "unten". Die Sprengladung wird also auch kein Loch "unten" in einer Nebenwand verursacht haben.)

**Comment by yur-y** [comment]
Gestrichen.
