### ISSUE TITLE
Seite 073: Formatierung kaputt. "Das Gebäude wird von vier"

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#274]

**Comment by ToBeFree** [comment]
Vorschlag: Monospace, wie bei der Hacking-Szene

**Comment by ToBeFree** [comment]
Besser: kursiv, ohne umgebende Box. Dazu eine nicht-nummerierte Aufzählung verwenden, wie sie bereits bei den Bild-Copyright-Angaben ganz am Schluss zum Einsatz kommt. Kann ich auch nachher machen.

**Comment by yur-y** [comment]
Was ist mit Fließtext, wie es im Wikipedia-Artikel auch steht?

**Comment by ToBeFree** [comment]
Die einfachste Lösung kommt mir nie in den Sinn. 😊 👍

**Comment by ToBeFree** [comment]
siehe #374
