### ISSUE TITLE
Seite 088: "schrie Free" --> "rief Free"

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#278]

**Comment by ToBeFree** [comment]
Schreien hat für mich eine unkontrollierte, hochfrequente, panische, um Hilfe rufende Konnotation. Das passt hier aber gar nicht.

**Comment by yur-y** [comment]
Ja, ich habe "schreien" nach wörtlicher Rede schon relativ oft ersetzt. Es kommt viel zu oft vor. Genauso wie übrigens "meinen".
