### ISSUE TITLE
Seite 091: Sehr schön, kein Fehler: kleine Schrift sieht dort sehr gut aus

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#282]

**Comment by ToBeFree** [comment]
Allerdings könnte sie beim dritten Hinhören ggf. etwas lauter/größer werden. Dick-Druck bringt dort nichts, das hat den falschen Effekt. "small" ist zu groß und ähnelt eher dem Normaltext als dem "tiny"-Text. Es wird wohl keine Lösung geben, also bleibt es wahrscheinlich am besten so, wie es ist.

**Comment by yur-y** [comment]
Doch: Kurzes Googeln hat ergeben, dass es noch {scriptsize} und {footnotesize} gibt, und ich finde, die sehen wirklich nicht schlecht aus, vor allem scriptsize. Probier es einfach mal aus, und dann sag mir, welche Formatierung Dir für die drei aufeinenanderfolgenden Rufe am besten gefällt.

https://de.wikibooks.org/wiki/LaTeX-W%C3%B6rterbuch:_Textgr%C3%B6%C3%9Fen

**Comment by ToBeFree** [comment]
Oooh schön 😃 

Zudem ist bei "scriptsize" und "footnotesize" das Problem aus #377 nicht vorhanden. In dieser Reihenfolge wäre das dann:

* scriptsize
* scriptsize (kein Lautstärkeunterschied)
* footnotesize (Ohr an der Wand)

Zwei Fliegen mit einer Klappe.
