### ISSUE TITLE
Seite 100: Alexandra ist extrem doof für eine zukünftige Sprengstoffexpertin.

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#286]

**Comment by ToBeFree** [comment]
Ist eben so. 😅 
Sie lernt im Laufe des Romans dazu und macht in Greater Sudbury einen Chemiekurs. Den tollen Nitro-TNB-Stoff stellt sie mit Hilfe einer Schritt-für-Schritt-Anleitung her. Passt schon.

**Comment by yur-y** [comment]
Ja, der Chemiekurs war mir auch schon mal aufgefallen. Ich würde ihn eigentlich lieber herausnehmen oder durch irgendetwas Anspruchsvolleres ersetzen.

**Comment by ToBeFree** [comment]
Ja, gerne :)

**Comment by yur-y** [comment]
Ja, genau. So, dass es nicht wie ein VHS-Einsteigerkurs wirkt. ;)

**Comment by yur-y** [comment]
Semirealistischer Änderungsversuch:

Alexandra stieg durch ein Fenster und landete in einem hochgeheimen Chemielabor. Dort fand sie mehrere Behälter, die mit Summenformeln beschriftet waren. »C2H6O«, »NH3« und »CH4O« waren jedoch noch nicht nach ihrem Geschmack. Im weiteren Verlauf der Suche kam sie an »C3H5N3O9« und »H2SO4« vorbei, woraufhin sich ihre Miene aufhellte, sie aber nach kurzem Überlegen dennoch weiterging. Dann stutzte sie. Zwischen zwei Fässern lag ein blauer Zylinder, der entfernt an einen USB-Stick erinnerte und mit »\$cann0r« beschriftet war. Ratlos begutachtete sie das eigenartige Gerät von allen Seiten und steckte es dann in eine Seitentasche ihres Rucksacks. Dabei fiel ihr Blick auf einen roten Behälter, der unter dem Tisch in einem Fach aufbewahrt wurde. Interessiert griff sie danach und stellte ihn auf den Tisch. Das Fass war mit Warnsymbolen und der Aufschrift »CHCl3« beklebt. Sie überlegte noch eine Weile und ließ ihren Blick über die anderen Behälter schweifen. Als sie den roten Behälter wieder in seinem Fach verstauen wollte, fiel er zu Boden und der Deckel löste sich.

Als sie wieder aufwachte, öffnete sich gerade die Tür. Statt den von Alexandra panisch erwarteten FBI-Agenten trat jedoch ein älterer Herr mit einem Wischmopp durch die Tür und zog einen Reinigungswagen hinter sich her.

Noch was: Zahlen tiefstellen in den Summenformeln?

**Comment by yur-y** [comment]
Hm, nee, das klappt auch nicht. Wahrscheinlich ist die Wirkung nicht ausreichend und wenn sie es wäre, wäre Orakel auch betroffen. Hast Du noch irgendeine Idee?

**Comment by yur-y** [comment]
Chemiekurs:

Statt

Alexandra stieß durch Zufall auf eine Schule, in der man einen eintägigen Chemiekurs machen konnte. Die Themen des Kurses waren Summenformeln, gefährliche Stoffe und deren Auswirkungen, die Eigenschaften verschiedener Sprengstoffe und die Minimierung von Unfallrisiken bei Chemieexperimenten.

---

Alexandra stieß durch Zufall auf die »International Conference on Chemistry and Technology of Explosives«, die dieses Jahr in Sudbury stattfand. Obwohl sie nicht offiziell angemeldet war, stellte der zuständige Sekretär der »interessierten Chemiestudentin«, die »zufällig in der Nähe Urlaub machte«, aus Nachsicht einen Teilnahmeausweis aus.

---

So in Ordnung?

**Comment by ToBeFree** [comment]
»International Conference on Chemistry and Technology of Explosives« 💚 😅

**Comment by ToBeFree** [comment]
Wie, die gibt es tatsächlich. Rein damit. Sehr, sehr genial. :D

**Comment by ToBeFree** [comment]
Zum umgekippten Behälter, wieso eigentlich nicht: Dann steht eben ein Fenster offen bzw. eine Belüftung ist aktiv. So wird Orakel nicht betroffen, obwohl Alexandra erstmal in Ohnmacht fällt. 👍

**Comment by yur-y** [comment]
Was ist mit der Hubschrauberszene? Da ist mir echt nix mehr eingefallen.

**Comment by ToBeFree** [comment]
Hm. Im Zweifelsfall den Bug offen lassen und auf das Ende der Korrektur schieben, wenn wir vielleicht dazu übergehen, gemeinsam noch die letzten Fehler auszumerzen. :)

**Comment by ToBeFree** [comment]
Potenziellen Folgefehler bereits sehr schön behoben, hätte ich ganz vergessen:

»Hi, ihr glaubt nicht, was ich entdeckt habe! Eine Konferenz über Sprengstoffe!«, rief sie ihnen zu.

👍

**Comment by ToBeFree** [comment]
Die Helikopterszene: Der Gedanke kam mir auch gerade: Wenn Alexandra sich nicht dumm anstellen soll, macht es eben jemand anderes. 😄 

Ist also bereits gelöst, dadurch, dass Orakel nun die Tube öffnet.

-----

Während yury den Helikopter wieder startete und dem Tankwart zum Abschied zuwinkte, begutachtete Orakel die verschiedenen Chemikalien, die Alexandra im FBI-Hauptquartier geklaut hatte. Er öffnete einfach wahllos eine Plastikpackung und roch an dem Inhalt.

»Erdbeeren, Zahnpasta? Free, nach was riecht das hier?«

Nachdem Free ebenfalls an der Chemikalie gerochen hatte, sagte er: »Ähm, Kaugummi?«

Orakel fragte auch yury, aber der lehnte ab. »Ich brauche jetzt kein Erdbeerzahnpastakaugummi, ich muss mich aufs Fliegen konzentrieren.«

Orakel fragte auch Alexandra. Sie fand, es sei eindeutig Erdbeerzahnpasta.

-----

**Comment by yur-y** [comment]
Sorry, habe im Moment wenig Zeit. Hoffe, dass ich demnächst wieder mitarbeiten kann.

Zur Szene: Alexandra riecht ja immer noch dran und hält die anderen nicht ab?

**Comment by ToBeFree** [comment]
https://github.com/InfiniteAdventures/ia-trilogy/commit/9f98a8076073cf0bff3e9271a61345f5d23d2095 (`https://github.com/InfiniteAdventures/ia-trilogy/commit/9f98a8076073cf0bff3e9271a61345f5d23d2095`)
