### ISSUE TITLE
Seite 100: Fehler, der wohl bleiben wird: "Gebäudereinigung Müller" kennt Alexandra gar nicht.

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#287]

**Comment by ToBeFree** [comment]
Das ist extrem schwierig, denn die Referenz möchte ich auf jeden Fall behalten. Ich war total stolz, das so hinbekommen zu haben... und dann fiel mir irgendwann ein, dass Alexandra noch gar nicht dabei war, als das Gefängnis gesprengt wurde. Auf diese Szene bezieht sich aber das Zitat.

**Comment by ToBeFree** [comment]
Man könnte höchstens jemand anderes als Alexandra dort einbrechen lassen, oder ihr einen Begleiter mitschicken, der die Anspielung versteht.

**Comment by ToBeFree** [comment]
Falls es unverändert bleibt, ein Erklärungs-Ansatz für nörgelnde Leser: Alexandra erkennt Orakel unabhängig von dem Zitat. An seiner Sprache, seiner Wortwahl, seiner Körperhaltung, was weiß ich. Wenn wir es unverändert lassen, kann ein solcher Erklärungsversuch im Bonusband zusammen mit ähnlichen "bekannten Ungereimtheiten" in einer schönen Liste abgedruckt werden.

**Comment by yur-y** [comment]
Ähm, ähem. Ich wusste zwar, dass es später noch einen Bezug gibt, aber ich fand die Stelle am Anfang *so* unlogisch, dass ich sie folgendermaßen verändert hatte:

»Guten Tag. García, Gebäudereinigung. Wir sollen das reinigen«, sagte
Orakel in fließendem Spanisch.

😅

**Comment by yur-y** [comment]
Wobei ich ehrlich gesagt auch gedacht hatte, dass das noch mehrere Male und nicht nur einmal vorkommt.

**Comment by ToBeFree** [comment]
Naja, García und fließendes Spanisch sind vollkommen in Ordnung und durchaus logischer als "Müller" :D 

(Wobei andererseits gerade auf Mallorca doch sowieso jeder Deutsch spricht? Ich war noch nicht dort, aber das vermute ich mal.^^)

**Comment by ToBeFree** [comment]
Übrigens findet die oben genannte Osterei-Szene in den USA statt, wo "Müller" nun wirklich ungewöhlich ist. Da ist es egal, ob García oder Müller dort steht.

Ach, ich sehe gerade, García ist zudem der häufigste spanische Nachname. Nett gewählt als Ersatz für Müller. Find ich gut. :)

Äh, was ich sagen wollte: Deine Änderung finde ich gut, sie verschlechtert auch die Referenz nicht - aber das Problem besteht halt weiterhin unverändert. 😄

**Comment by yur-y** [comment]
Wenn wir es noch irgendwo anders in der ursprünglichen Version mit "Müller" eingebaut bekommen würden (möglichst sogar vor der Szene in Spanien), dann ließe sich das letztere Problem zumindest dadurch lösen, dass Orakel sich "Mueller" nennt. :)

**Comment by yur-y** [comment]
Im Moment steht jetzt "Mueller". Fände es super, wenn wir irgendwo vorher noch mal ne fabrizierte "Original-Szene" in Deutschland hinbekommen. (Sprich, vor der Szene in Spanien.)

**Comment by ToBeFree** [comment]
Aber das Hauptproblem war doch, dass Alexandra nicht dabei war, als die Originalszene passiert ist (?)

**Comment by yur-y** [comment]
Noch schöner fände ich ja immer noch, in Deutschland eine weitere Szene mit 'ü' einzubauen und das ue stehen zu lassen. Aber das sagt sich leicht ;)

**Comment by ToBeFree** [comment]
Ein weiteres Problem: Die Szene bzw. der Witz könnte durch ein drittes
Vorkommen überstrapaziert werden. Ich würde es so lassen, wie es momentan
ist.
