### ISSUE TITLE
Seite 112: "Euro" --> "Dollar" (und siehe Kommentar)

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#289]

**Comment by ToBeFree** [comment]
Kanadische und amerikanische Dollars sind, soweit ich das verstehe, nicht identisch. Es wäre eigentlich komisch, wenn die amerikanischen Goldhändler-Dollars in Kanada einfach so genutzt werden könnten, oder? (Seite 106)

Kartenzahlung würde das Problem lösen, aber das geht in dieser Szene gleich doppelt nicht: Es würde die Szene kaputtmachen (großer Geldbetrag vor Augen des Kassierers, Rückgeld), und die Karte ist zudem noch gesperrt. Darum geht es ja gerade.

Einzige Erklärungsmöglichkeit: Der amerikanische Dollar ist mehr wert als der kanadische Dollar. Das ist tatsächlich so. Das von Orakel auf den Tisch gelegte Geld ist also umso beeindruckender. Und das auf Tourismus eingestellte Geschäft akzeptiert US-Dollars.

**Comment by yur-y** [comment]
Ein Supermarkt akzeptiert US-Dollar? Auf einem Kontinent, wo alles fast nur noch mit Karte gezahlt wird? Ich weiß nicht... Ohne vorheriges Umtauschen wird die Szene wohl nicht funktionieren...

**Comment by yur-y** [comment]
Habe sie jetzt vorher bei dem Pizza-Zwischenstopp Geld umtauschen lassen.

**Comment by ToBeFree** [comment]
Oh, guter Punkt! Das klingt nach einer guten Lösung.
