### ISSUE TITLE
Seite 127: Wunderschönes Chemie-Tiefstellungs-Unicode. Wird gebraucht auf Seite 100 und 114. Siehe Kommentar für Kopiervorlage

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#293]

**Comment by ToBeFree** [comment]
https://de.wikipedia.org/wiki/Unicodeblock_Hoch-_und_tiefgestellte_Zeichen

**Comment by yur-y** [comment]
Habe da einfach \textsubscript benutzt. OK?

**Comment by yur-y** [comment]
Auf Seite 114 würde ich es so lassen, wie es ist. Da geht es ja nur um die Ausgabe des Computerprogramms, und dann ist es vielleicht weniger direkt klar, dass es sich um chemische Summenformeln handelt, wovon die Stelle ja lebt.

**Comment by ToBeFree** [comment]
Ok, stimmt!

**Comment by ToBeFree** [comment]
Ich sehe gerade, dass \textsubscript wohl den Mathematikmodus für diese Zeichen aktiviert; es werden nicht einfach nur die speziellen Unicode-Zeichen ausgegeben. Das könnte z.B. in Überschriften problematisch sein, aber genauer kenne ich mich auch nicht damit aus. Ich würde ganz zum Schluss wahrscheinlich den LaTeX-Befehl durch die Zeichen von der Wikipedia-Seite ersetzen, auch damit der Quelltext möglichst gut menschenlesbar ist.

**Comment by ToBeFree** [comment]
Dankeschön, hätte ich auch so gemacht 😄
