### ISSUE TITLE
Seite 132: "127.0.0.1" --> "::1"  (IPv4 --> IPv6)

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#294]

**Comment by yur-y** [comment]
Hm, aber ich würde behaupten, dass 127.0.0.1 mehr Leute verstehen...

**Comment by ToBeFree** [comment]
Guter Punkt, aber das ist mir aus Prinzip vollkommen egal und wird in 20 Jahren genau umgekehrt sein. 😜

**Comment by ToBeFree** [comment]
Aaaaaaußerdem wird es im Bonusband eine Schritt-für-Schritt-Erklärung der Hacking-Szene geben! 😊

**Comment by yur-y** [comment]
root@sandbox.tobefree.eu:\textasciitilde{}\# echo "::1 db.remote.fbi.gov" >> /etc/hosts
