### ISSUE TITLE
Seite 132: Kursivdruck für Beschreibungstext? "Dieser aus Sicherheitsgründen streng geheim"...

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#295]

**Comment by yur-y** [comment]
Contra: Es ist ein ganzer Absatz, das wäre sehr viel Kursivdruck. Außerdem liest Alexandra vor, es lässt sich also auch als "normale wörtliche Rede" auslegen.

**Comment by ToBeFree** [comment]
👍
