### ISSUE TITLE
Seite 211: Titelbild zeigt Blärg-Bergsee und einen großen Mond. "es gab keinen großen Mond in der Nähe", Mist. Siehe Kommentar.

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#305]

**Comment by ToBeFree** [comment]
Die Szene gefällt mir sehr, und ich finde, sie ist eigentlich gut geschrieben. Der Hinweis auf den fehlenden Mond und das eben stattdessen leuchtende Licht der Sterne würde ich gerne behalten, aber es gibt eben diesen Mond. Vielleicht so:

"der Mond leuchtete nicht hell genug"?

"Nacht, aber es war relativ hell, weil..." (Mond & zentrumsnahe, dichte Sterne sind zusammen ziemlich hell)

**Comment by yur-y** [comment]
Neumond?

**Comment by yur-y** [comment]
Noch mal generell zum Titelbild: Ich habe mir die Titelseite ehrlich gesagt gerade erst noch mal angeschaut, sie ist in dem PDF ja nicht enthalten. Ich finde das Bild echt gut, aber ich finde, dass die geschwungene Schriftart nicht so ganz zum Roman passt. Was meinst Du/welche Gründe hattest Du für die Auswahl?

**Comment by ToBeFree** [comment]
Oh! Das ist ein interessanter Diskussionspunkt. Ich mache aber mal ein neues Issue dafür auf.
