### ISSUE TITLE
Seite 214: Tagebuch-Formatierung ist kaputt ("Wir haben gerade einen sehr gefährlichen"...)

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#306]

**Comment by yur-y** [comment]
Wenn Du mir sagst, wie es eigentlich aussehen sollte, fixe ich es direkt.

**Comment by ToBeFree** [comment]
Vielleicht einfach Kursivdruck mit ordentlichen Absätzen. Ich hatte überlegt, das als Code-Block darzustellen, aber das passt ja gar nicht zum Tagebuch.

Stil-Beispiel: Zeitungsartikel in der FÄZ

**Comment by ToBeFree** [comment]
Weiterer positiver Aspekt: Kursivdruck (textit) sieht im Gegensatz zu Schrägstellung (textsl) bei Linux Libertine, also unserer Buchschriftart, sehr elegant aus. Wenn wir schon eine spezielle Kursivschrift besitzen, können wir sie durchaus nutzen.

**Comment by yur-y** [comment]
>>> Vielleicht einfach Kursivdruck mit ordentlichen Absätzen. Ich hatte überlegt, das als Code-Block darzustellen, aber das passt ja gar nicht zum Tagebuch.

Stil-Beispiel: Zeitungsartikel in der FÄZ <<<

... also auch mit den drei Unendlichzeichen drum herum?

**Comment by ToBeFree** [comment]
An die hatte ich jetzt gar nicht gedacht -- aber ja, ich glaube, die können nicht schaden. Eine gewisse Distanz zum Rest des Textes passt vielleicht ganz gut zum Wechsel zwischen zwei Medien.

**Comment by yur-y** [comment]
Ups, der Vorschlag war gar nicht mal so gut, weil direkt vor dem Satz "Vor der Routenplanung nach Örz schrieb Orakel noch schnell etwas in sein Tagebuch." drei sehr sinnvolle Unendlichzeichen stehen.^^ Dann versuche ich es mal ohne.

**Comment by ToBeFree** [comment]
Oh! Da hätte ich aber auch nochmal nachgucken sollen. 👍

**Comment by yur-y** [comment]
Sieht OK aus.
