### ISSUE TITLE
Seite 227: "Erkundungsraumschiff zu übernehmen" --> "Erkundungsraumschiff zu kapern" (Piratencrew übernimmt nicht, Piratencrew kapert!*) *Spitzfindigkeit siehe Kommentar

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#329]

**Comment by ToBeFree** [comment]
Kaperei ist Freibeuterei, also nicht illegal, sondern im Auftrag eines Staates gegen Schiffe eines feindlichen Staates. Legale Piraterie, solange man nur die "bösen" Schiffe ausraubt. Das ist aber genau das, was uggys tun: von der Regierung legitimierte Raubzüge durchs All.

**Comment by yur-y** [comment]
✔
