### ISSUE TITLE
Seiten 241, 242: "Örz-Expörtärüläz"-Formatierung ist kaputt

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#338]

**Comment by yur-y** [comment]
Wie soll die denn eigentlich aussehen?

**Comment by ToBeFree** [comment]
Das Original ist in Markdown geschrieben, ich habe es bei der LaTeX-Konvertierung übergangen, bzw. wahrscheinlich eher einfach vergessen.

Hier ist das Resultat, wenn man das 1:1 in diesem Kommentarfenster eintippt, welches ja Markdown unterstützt:

**Comment by ToBeFree** [comment]
-----
```
Örz-Expörtärüläz
(Örslängütränslätiön by Äzähüglü Örzgü)

§~3

(1) Es ist verboten, Äöüzz-Technologie auf Planeten zu exportieren, die noch keine offiziellen Gespräche mit der Äöüzz-Wirtschaftsvereinigung aufgenommen haben.

(1.1) Sinn des Gesetzes ist es, einen schweren Eingriff in die Wirtschaft und Politik dieser Planeten zu verhindern. Selbst der Export simpler Geräte hat bereits mehrfach zum Entstehen planetenweiter Diktaturen beigetragen.

(2) Ausnahmen: Absatz 1 gilt nicht für
•	(2.1) die schonende Verhinderung eines Atomkriegs und ähnlicher Selbstzerstörungsszenarien.
•	(2.2) die Verteidigung der Planetenbewohner gegen Angriffe einer fremden, raumfahrenden Zivilisation.
•	(2.3) vom zentralen Wirtschaftsrat ausdrücklich im Voraus genehmigte Exporte.
```
-----

**Comment by ToBeFree** [comment]
Und das ist auch prinzipiell das gewünschte Aussehen. So in etwa, zum Beispiel:

https://www.gesetze-im-internet.de/krwaffkontrg/__6.html

**Comment by ToBeFree** [comment]
Da es hier keine mehrfachen Ebenen gibt, ist das wahrscheinlich relativ simpel.

Örz-Expörtärüläz
(Örslängütränslätiön by Äzähüglü Örzgü)

§~3

(1) Es ist verboten, Äöüzz-Technologie auf Planeten zu exportieren, die noch keine offiziellen Gespräche mit der Äöüzz-Wirtschaftsvereinigung aufgenommen haben.

(1.1) Sinn des Gesetzes ist es, einen schweren Eingriff in die Wirtschaft und Politik dieser Planeten zu verhindern. Selbst der Export simpler Geräte hat bereits mehrfach zum Entstehen planetenweiter Diktaturen beigetragen.

(2) Ausnahmen: Absatz 1 gilt nicht für
\begin{itemize}
\item (2.1) die schonende Verhinderung eines Atomkriegs und ähnlicher Selbstzerstörungsszenarien.
\item (2.2) die Verteidigung der Planetenbewohner gegen Angriffe einer fremden, raumfahrenden Zivilisation.
\item (2.3) vom zentralen Wirtschaftsrat ausdrücklich im Voraus genehmigte Exporte.
\end{itemize}

**Comment by yur-y** [comment]
Danke! Ich würde nach einigem Experimentieren für eine parbox mit items plädieren, weil es sich sonst nicht gut in den Fließtext integriert. Bin mir aber nicht sicher, ob mit \begin{tiny} \begin{ttfamily} oder ohne. Was meinst Du?

\noindent \parbox{\textwidth}{ \vspace{3ex} \hrule \vspace{3ex}

\noindent Örz\_Expörtärüläz

\noindent (Örslängütränslätiön by Äzähüglü Örzgü)

\begin{itemize}
\item[] §~3 Export von Äöüzz-Technologie
\begin{itemize}
\item[] (1) Es ist verboten, Äöüzz-Technologie auf Planeten zu exportieren, die noch keine offiziellen Gespräche mit der Äöüzz-Wirtschaftsvereinigung aufgenommen haben.
\begin{itemize}
\item[] (1.1) Ziel dieser Regelung ist es, einen schweren Eingriff in die Wirtschaft und Politik dieser Planeten zu verhindern. Selbst der Export simpler Geräte hat bereits mehrfach zum Entstehen planetenweiter Diktaturen beigetragen.
\end{itemize}
\item[] (2) Absatz 1 gilt nicht für
\begin{itemize}
\item[] (2.1) die schonende Verhinderung eines Atomkriegs und ähnlicher Selbstzerstörungsszenarien;
\item[] (2.2) die Verteidigung der Planetenbewohner gegen Angriffe einer fremden, raumfahrenden Zivilisation;
\item[] (2.3) vom Zentralen Wirtschaftsrat ausdrücklich im Voraus genehmigte Exporte.
\end{itemize}
\end{itemize}
\end{itemize}

\vspace{3ex} \hrule \vspace{3ex} }

**Comment by yur-y** [comment]
PS: Beides ginge, weil direkt vorher ein Seitenumbruch kommt. Ich tendiere leicht zur tiny-Version.

**Comment by ToBeFree** [comment]
Kurze Anmerkung: Footnotesize, nicht tiny -- der Vorschlag kam, glaube ich, sogar von dir. :) Tiny ist zu unleserlich beim Druck. Aber das korrigiere ich, falls irgendwo vorhanden, nachträglich einfach noch. Die "useful copypasta" enthält noch an manchen Orten fälschlicherweise "tiny".

**Comment by ToBeFree** [comment]
Generell würde ich "footnotesize" (bzw. nach altem Stil "tiny") statt der normalen Schriftgröße verwenden. Die --- oooh, jetzt verstehe ich. Dein anderer Vorschlag ist, auch "ttfamily" wegzulassen. Die Parbox dient nur noch der Verhinderung eines Seitenumbruchs.

Total interessant, das könnte man sogar häufiger im Roman verwenden. Allerdings ist jede "parbox" vermutlich eine Qual für den LaTeX-Interpreter, der den Leerraum ordentlich verteilen muss. Wenn das mal nicht funktioniert, sieht der Text sehr merkwürdig aus.

Footnotesize fände ich allerdings auch bei der Standardschrift angebracht. Das erhöht den sichtbaren Unterschied zwischen dem Fließtext und dem Zitat. Außerdem vermeidet es eventuelle zukünftige Umbruchprobleme durch eine übergroße Parbox.

**Comment by yur-y** [comment]
Das bezog sich nur auf die eine Stelle, wo die vier durch die Wand rufen, oder? Für die Boxen: https://github.com/InfiniteAdventures/ia-trilogy/issues/258

**Comment by ToBeFree** [comment]
"footnotesize" meinte ich nur für Boxen mit Terminalschrift. Der erste Satz in meinem vorherigen Kommentar war nur "laut gedacht". Ich hatte übersehen, dass die von dir vorgeschlagene Box für den Gesetzestext gar keine Terminal-Schriftart nutzt.

**Comment by ToBeFree** [comment]
@yur-y die Lösung aus deiner aktuellen Version finde ich sehr schön. 😃
