### ISSUE TITLE
Seite 244: "Eine halbe Minute später waren sie notgelandet" langweilig, stattdessen Bruchlandung in einem namentlich benannten Mondkrater. Beispiel "Eine halbe Minute später ging die 4-6692 krachend am Rand des Mondkraters XY zu Boden." - ggf. detaillierter weiter beschreiben. Schiff kommt nicht sofort zum Stillstand und reißt eine Furche in den Boden, oder ähnlich.

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#342]

**Comment by yur-y** [comment]
Verbesserungsvorschläge erwünscht:

Eine halbe Minute später ging die 4-6692 krachend im Descartes-Hochland zu Boden. Trotz der starken Erschütterung blieben die vier Freunde unverletzt. Die anderen schienen erleichtert, aber yury sagte: »Wir können froh sein, wenn wir hier wieder wegkommen.«

»Äh«, machte Orakel.

»Was ist?«, fragte Alexandra verständnislos.

»Das sieht nicht so gut aus… Der Warp-Antrieb scheint kaputt zu sein. Wir haben zwar noch einen Raketenantrieb, aber der ist nur auf extrem kurze Distanzen ausgelegt. Wir können damit nicht einmal den nächsten Stern erreichen, geschweige denn Örz.«

»Na super«, sagte Free und sah auf den großflächigen Bildschirm im Raumschiff, das die Umgebung anzeigte. »Und was machen wir je– hey, was macht die weiße Flagge da?«

»Keine Ahnung, aber jetzt dürfen wir uns erst einmal um die uggys kümmern«, sagte yury und zeigte auf das riesige uggy-Raumschiff, das neben der untergehenden Erde am nicht vorhandenen Himmel zu sehen war.

**Comment by ToBeFree** [comment]
Die anderen schienen erleichtert, aber yury sagte:

Vs

Die anderen schienen erleichtert, aber yury blieb pessimistisch:

Oder so. :)

**Comment by ToBeFree** [comment]
Die Flagge hab ich zuerst nicht verstanden. Vorschlag:

**Comment by ToBeFree** [comment]
»Und was machen wir je– hey, was macht die weiße Flagge da?«

Vs

»Und was machen wir je– hey, da flattert ein weißes Tuch!«

**Comment by ToBeFree** [comment]
»Keine Ahnung, aber jetzt dürfen wir uns erst einmal um die uggys kümmern«, sagte yury und zeigte auf das riesige uggy-Raumschiff, das neben der untergehenden Erde am nicht vorhandenen Himmel zu sehen war.

Vs

»Keine Ahnung, aber das Ding wird gleich nützlich«, sagte yury und zeigte auf das riesige uggy-Raumschiff, das neben der untergehenden Erde am nicht vorhandenen Himmel zu sehen war.


Dann steigt er mit Raumanzug aus, greift nach der zerfledderten weißen Flagge und wedelt damit herum.

Falls die Freunde sich ergeben wollen.

**Comment by ToBeFree** [comment]
Die Szene gefällt mir sehr gut, die Vorschläge sind optional. Vor allem der Insiderwitz mit der Flagge gefällt mir sehr. Bisher wusste ich nichts davon. 🙂 👍

**Comment by yur-y** [comment]
"Flattern" ist unwahrscheinlich, trotz ankommendem uggy-Raumschiff.^^

**Comment by ToBeFree** [comment]
Oh, da ist ja gar keine Atmosphäre. Das wäre ein bitterer Sachfehler gewesen, danke. 😄 

Der "edit"-Einwand ist leider sehr gut. Aber ich glaube, das lässt sich doch relativ simpel lösen:

(Achtung, in deiner letzten hochgeladenen Version steht "yury bl:", da fehlt irgendetwas)

Enthält mehrere kleinere Bearbeitungen an verschiedenen Stellen:

----

»ihre identifikation ist seit 30 sekunden ueberfaellig. wir werden nun die unmittelbare zerstoerung einleiten.«

»Das sind doch leere Drohungen, die haben eh nichts davon, wenn sie uns zerstören«, hoffte Free. yury versuchte währenddessen verzweifelt, auf dem Mond notzulanden, weil es für eine Richtungsänderung schon zu spät war.

Eine halbe Minute später ging die 4-6692 krachend im Descartes-Hochland zu Boden. Trotz der starken Erschütterung blieben die vier Freunde unverletzt. Die anderen schienen erleichtert, aber yury bl: »Wir können froh sein, wenn wir hier wieder wegkommen.«

»Äh«, machte Orakel.

»Was ist?«, fragte Alexandra verständnislos.

»Das sieht nicht so gut aus… Der Warp-Antrieb scheint kaputt zu sein. Wir haben zwar noch einen Raketenantrieb, aber der ist nur auf extrem kurze Distanzen ausgelegt. Wir können damit nicht einmal den nächsten Stern erreichen, geschweige denn Örz.«

»Na super«, sagte Free und sah auf den großflächigen Bildschirm im Raumschiff, das die Umgebung anzeigte. »Hier sind nur Krater und hässliche Felsbrocken– hey, was ist das denn da drüben für eine weiße Flagge?«

»Keine Ahnung. Die uggys machen mir gerade mehr Sorgen«, sagte yury und zeigte auf den hässlichen Klotz, der neben der untergehenden Erde am nicht vorhandenen Himmel zu sehen war.

Das Piratenraumschiff schien immer größer zu werden und landete schließlich einen halben Kilometer entfernt von der 4-6692 auf dem Mond. Viele bewaffnete uggys liefen (wenn man die Fortbewegungsart eines uggys überhaupt noch als »Laufen« bezeichnen konnte) auf die 4-6692 zu. Die vier Freunde sahen ein, dass ihnen keine andere Wahl blieb, und verließen ohne Waffen in ihren Raumanzügen die 4-6692.

Free schien sich für besonders intelligent zu halten, als er die weiße Flagge aus dem Boden riss und damit den uggys zuwinkte. Wenige Sekunden später zerfetzte eine Salve großkalibriger Bleikugeln das symbolische Friedensangebot, und Free starrte entgeistert auf die Überreste der ersten USA-Flagge auf dem Mond.

»Ich glaube, die uggys sind nicht allzu begeistert von deiner Verhandlungstaktik«, stellte Alexandra fest. »Vielleicht sollten wir stattdessen die leeren Hände in die Luft heben.«

»Und was ist daran besser?«, fragte Free skeptisch, während er den Fahnenstab vorsichtig auf den Boden legte.

»Naja, dann kann man wenigstens sehen, dass wir keine Waffen in den Händen halten.«

Alexandra und Free diskutierten noch immer, als sie zusammen mit Orakel und yury in eine Art Gefängniszelle auf dem uggy-Schiff gesperrt wurden. Eine kleine Gruppe von uggys übernahm die Kontrolle der 4-6692, und kurz darauf starteten die beiden Raumschiffe.

»Hey, wo sind wir hier?«, fragte Alexandra.

»Im Gefängnis auf einem riesigen Piratenschiff«, antwortete Orakel. »Wenigstens leben wir noch.«

Dann holte er einen Muffin aus einer seiner vielen Taschen und begann damit, ihn zu essen.

»Haben die dir den nicht abgenommen?«, fragte Free erstaunt.

»Nö«, antwortete Orakel genüsslich schmatzend.

**Comment by yur-y** [comment]
Das ist super, danke! Ist eingebaut.
