### ISSUE TITLE
Seite 251: Formatierung des Äöüzz-Liedes "Läzzä wörzz" ist kaputt; Kursivdruck wäre zudem nicht schlecht.

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#345]

**Comment by yur-y** [comment]
So?

»Tätätätädüdädubäbbummzzz dä Aöüzz wäll wänn äväri wörzz

\noindent beköööz bekööözz nöbödü kän stöööööp däääm

\noindent föräävä föräävä föräävä

\noindent föräävä föräävä föräävä

\noindent änt nöbödü wöll stöp dä Aöüzz

\noindent beköööz bekööözz nöbödü kän stöööööp däääm

\noindent föräävä föräävä föräävä

\noindent föräävä föräävä föräävä

\noindent beköööz bekööözz nöbödü kän stöööööp däääm

\noindent föräävä föräävä föräävä

\noindent föräävä föräävä föräävä

\noindent ölä ölä dä Äöüzz wäll wäään äääääääveri läzt wöööörz

\noindent änt nöbödü wöll stöp dä Aöüzz

\noindent beköööz bekööözz nöbödü kän stöööööp däääm

\noindent föräävä föräävä föräävä

\noindent föräävä föräävä föräävä

\noindent ölä!«

**Comment by ToBeFree** [comment]
Ach, da war ja was mit Absätzen. 🙂 Ja, sieht sehr gut aus!

Auch gut: Diese Lösung gibt keine Probleme mit dem Seitenumbruch und passt sich gut an den restlichen Text an. Bei Code-Blöcken oder Ähnlichem müsste man darauf achten, dass der Text nicht zu lang wird.

**Comment by yur-y** [comment]
Habe mich umentschieden, sieht ohne \noindent besser aus. Lösung jetzt:

»\textit{Tätätätädüdädubäbbummzzz dä Aöüzz wäll wänn äväri wörzz}

\textit{beköööz bekööözz nöbödü kän stöööööp däääm}

\textit{föräävä föräävä föräävä}

\textit{föräävä föräävä föräävä}

\textit{änt nöbödü wöll stöp dä Aöüzz}

\textit{beköööz bekööözz nöbödü kän stöööööp däääm}

\textit{föräävä föräävä föräävä}

\textit{föräävä föräävä föräävä}

\textit{beköööz bekööözz nöbödü kän stöööööp däääm}

\textit{föräävä föräävä föräävä}

\textit{föräävä föräävä föräävä}

\textit{ölä ölä dä Äöüzz wäll wäään äääääääveri läzt wöööörz}

\textit{änt nöbödü wöll stöp dä Aöüzz}

\textit{beköööz bekööözz nöbödü kän stöööööp däääm}

\textit{föräävä föräävä föräävä}

\textit{föräävä föräävä föräävä}

\textit{ölä!}«
