### ISSUE TITLE
Seite 253 ff: Formatierung der Lesegerät-Ausgabe ist kaputt. "ugunektioun uhfud." etc., auch die Ausgabe "Protokoll der Vereinigten uggy" usw.

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#347]

**Comment by yur-y** [comment]
Wiederum die Frage, wie es denn eigentlich sein sollte. Alternative: Einfach in normalen Anführungszeichen?

**Comment by ToBeFree** [comment]
Kursivdruck wäre das Mindeste, finde ich -- aber es ist eine Textausgabe, keine Sprachausgabe. Daher würde ich die Terminal-Text-Syntax nutzen:

\noindent \parbox{\textwidth}{ \vspace{3ex} \hrule \vspace{3ex}

    \begin{footnotesize}
    \begin{ttfamily}

\noindent Bla Bla

\noindent Bla Bla Bla.

    \end{ttfamily}
    \end{footnotesize}

\vspace{3ex} \hrule \vspace{3ex} }

**Comment by yur-y** [comment]
✔
