### ISSUE TITLE
Seite 254: "Er lief bestimmt zehn Minuten durch das Raumschiff" --> "Er lief bestimmt zehn Minuten im Kreis" (und siehe Kommentar)

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#348]

**Comment by ToBeFree** [comment]
Es muss offensichtlich sein, dass er nicht in Not ist und sich total dumm verhält. Sonst wäre es ziemlich gemein, ihn zehn Minuten lang allein durch die Gegend rennen zu lassen. Außerdem wird hier ein Wiederholungsfehler gelöst.

**Comment by yur-y** [comment]
Es steht ja bereits "ganz offensichtlich ohne echte Not". Raumschiff durch Kreis ersetzt.
