### ISSUE TITLE
Seite 259: Ausgabe des Generators ("Prötectiön") schlecht formatiert, kursiv wäre nett

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#355]

**Comment by yur-y** [comment]
Kursiv erledigt. Sonst noch was?

**Comment by ToBeFree** [comment]
Hmm, das Örzlängü dort war zumindest in der Testdruck-Fassung merkwürdig und schlecht lesbar. Dazu kommt, dass die entscheidende Warnmeldung dann sowieso in Deutsch kommt. Dann kann man sich den Örzlängü-Teil vorher auch sparen.^^

Ich gucke mir das einfach nachher nochmal an. Kommt auf meine Merkliste für die gemeinsame Überarbeitung.
