### ISSUE TITLE
Seiten 272, 273: "DÄVID" & "souloftheinternet@": schlecht formatierte Textstellen, Kursivdruck wäre zudem gut

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#358]

**Comment by yur-y** [comment]
Habe wieder die Code-Formatierung mit der parbox und den Linien versucht. Leider gehen Zeilenumbrüche dabei kaputt. Gibt es dafür eine Lösung?

**Comment by ToBeFree** [comment]
Ich gucke eben ins PDF, danke fürs Hochladen :)

**Comment by ToBeFree** [comment]
Ah, das Problem hatte ich auch an anderen Stellen. Am elegantesten lässt es sich wohl lösen, indem man "\\" (ja, doppelter Backslash, das ist keine Escape-Sequenz für einen Backslash!) ans Ende jeder Zeile packt, auf die ein Zeilenumbruch folgen soll.
