### ISSUE TITLE
Seite 306: "was zu essen" --> "etwas zu essen" (sonst umgangssprachlich)

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#366]

**Comment by yur-y** [comment]
Das wird öfters gesagt, aber immer nur in wörtlicher Rede. Soll ich das überall ersetzen?

**Comment by yur-y** [comment]
Ich bin da agnostisch und weiß nicht, ob es Empfehlungen gibt. Habe es jetzt überall ersetzt. Willst Du dann auch noch überall "nicht mal" ersetzen?

**Comment by ToBeFree** [comment]
Gelöst. Eine absichtliche Ausnahme: Free regt sich über fehlendes WLAN auf der Insel auf. 😄
