### ISSUE TITLE
S. 61: Im Flug entführt?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#373]
"Bei einem kurzen Zwischenstopp stellten Free und Orakel ihren im Flug entführten kleinen
Helikopter an einer Tankstelle ab, deckten sich mit Nahrungs- und Kero-
sinvorräten für mehrere Monate ein, befreiten den Piloten und wünschten
ihm eine angenehme Heimreise."

- Wieso im Flug entführt, und welcher Pilot muss befreit werden?

**Comment by ToBeFree** [comment]
Oh! Das ist ein Verweis auf eine inzwischen gestrichene Szene, in der Holzkisten zwischen Helikoptern hin und her geworfen werden. Ich gucke mir das nochmal genauer an, aber ich glaube, den Piloten können wir aus dieser Erzählung herausnehmen.

Witzigerweise habe ich diesen Zwischenstopp während meiner Überarbeitung eingebaut. Ich habe also diesen Verweis eingefügt und dann bei einem zweiten Durchgang seine Quelle entfernt...
