### ISSUE TITLE
S. 73-74: Wikipedia-Zitat

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#374]
.> »Das Gebäude wird von vier Wachtürmen an jeder Gebäudeecke gesäumt, die nur von innen betreten werden können.«
.> »Den Eingang bildet eine etwa 20 Tonnen schwere und rund 60 cm dicke Tür aus sieben Schichten Stahl einer geheimen Legierung.«
.> »Die gesamte zum Öffnen notwendige Zahlenkombination weiß kein einzelner Mensch komplett. Stattdessen muss eine nicht bekannte Anzahl Mitarbeiter unabhängig voneinander diverse Codes eingeben, um die Tür zu öffnen.«
.> »Hinter der Tür befinden sich 28 Einzelabteile, in denen das Gold gelagert wird.«
.> Quelle: http://de.wikipedia.org/wiki/Fort_Knox, Abruf 2018-04-02, 00:42 UTC

[Punkte hinzugefügt, um die automatische Formatierung zu verhindern]

Können wir nicht die Quelle herausnehmen? - Oder zumindest die Abrufzeit, weil sie ja nicht wirklich in die Romanebene passen, sondern eher eine zusätzliche "Sachebene" mitten im Text aufmachen, was ich nicht so schön finde. Falls die Quellenangabe mit Abrufdatum aus Lizenzgründen drinbleiben muss, können wir sie vielleicht zu den anderen Bild- und Tonquellen verschieben?

**Comment by ToBeFree** [comment]
Oh, ja - wirklich toll fand ich das beim Schreiben auch nicht. :D

Drinlassen würde ich die Quellenangabe auf jeden Fall, aber ans Ende verschieben ist eine gute Idee.

Es gibt natürlich L(u)aTeX-Plugins, die sich um Zitate kümmern. Immerhin wird LaTeX meistens im wissenschaftlichen Bereich verwendet; Quellenangaben sind alltäglich. Hier haben wir aber keine solche Software eingerichtet; man müsste dazu erstmal BibTeX konfigurieren und beim Compilieren ein zusätzliches Programm aufrufen - das alles für eine einzige Quellenangabe. Das sollten wir stattdessen irgendwie manuell machen. Kümmere ich mich später drum. :)

**Comment by yur-y** [comment]
Ich habe mal das zweite Issue dazu geschlossen, um keine Dopplung zu haben. Ich lasse es jetzt vorerst so:

»Das Gebäude wird von vier Wachtürmen an jeder Gebäudeecke gesäumt, die nur von innen betreten werden können. Den Eingang bildet eine etwa 20 Tonnen schwere und rund 60 cm dicke Tür aus sieben Schichten Stahl einer geheimen Legierung. Die gesamte zum Öffnen notwendige Zahlenkombination weiß kein einzelner Mensch komplett. Stattdessen muss eine nicht bekannte Anzahl Mitarbeiter unabhängig voneinander diverse Codes eingeben, um die Tür zu öffnen. Hinter der Tür befinden sich 28 Einzelabteile, in denen das Gold gelagert wird.«

Quelle: http://de.wikipedia.org/wiki/Fort\_Knox, Abruf 2018-04-02, 00:42 UTC

Und wenn Du am Ende noch die Quelle verschieben willst, wäre mir das recht.

**Comment by ToBeFree** [comment]
Ok, das ist auf jeden Fall erstmal besser als der vorherige Stand. Ich packe es auf meine Merkliste, wir können uns das nach Abschluss deiner Überarbeitung ja einfach nochmal angucken.

**Comment by ToBeFree** [comment]
lol -- hast du den Apostroph in das Label "Tobias' Merkliste" eingebaut, oder hab ich das am Smartphone unbewusst gemacht? 😄

**Comment by ToBeFree** [comment]
(Ah nee, bleibt ja offen)
