### ISSUE TITLE
S. 81: Alexandra wirft Granaten durch die Gegend?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#375]
»C9H8N6O15. Nicht geeignet für Kinder unter drei Jahren. Enthält verschluckbare Kleinteile«, murmelte sie vor sich hin, während sie an einer Granate bastelte. Als sie fertig war, öffnete sie die Tür des Helikopters und warf einen letzten Blick auf ihr Werk. Ein unheimliches Lächeln trat auf ihr Gesicht, dann holte sie aus, zielte kurz und schmiss die Konstruktion in hohem Bogen nach draußen.

»Kann in Verbindung mit chlorhaltigen Reinigern unerwünschte Reaktionen hervorrufen. Kühl und trocken lagern, mindestens haltbar bis…«

Draußen gab es einen lauten Knall. yury blickte erschrocken zur Seite. Einer der unbemannten, automatisch gesteuerten Helikopter wurde auseinandergerissen; an der Stelle des Hauptrotors klaffte ein großes Loch. Es dauerte nicht lange, bis die Schwerkraft das fliegende Helikopterwrack in einem Waldstück zerschellen ließ. Unten zeugte ein Feuerball von der Brennbarkeit des Kerosins. Der kleine Waldbrand und yurys entsetzter Protest konnten Alexandra aber nicht davon abhalten, weitere Experimente durchzuführen.

- Woher weiß sie denn, dass unten im Wald oder im betreffenden Helikopter keine Menschen sind?

**Comment by ToBeFree** [comment]
Ah Mist.

Die Originalszene war deutlich, deutlich rücksichtsloser. Durch komplett automatisch fliegende Helikopter dachte ich, das Problem gelöst zu haben. Dass sich darin niemand befindet, könnte sie eventuell von außen erkennen: Die Helikopter sind bunt zusammengeklaut, und die wenigen von Menschen gesteuerten Exemplare sind ihr vielleicht bekannt. Aber der Einwand mit dem Wald ist leider ziemlich berechtigt.

Ersatzlos streichen? Immerhin ist dieser Text sowieso nachträglich erfunden worden und war im Original gar nicht enthalten. Wir streichen also nichts "authentisches".

**Comment by ToBeFree** [comment]
Ein bisschen schade um den zerstörerischen Text und die damit verbundene Alexandra-typische Situationskomik, aber das moralische Problem wiegt schwerer. Eine Weile lang hatte ich überlegt, stattdessen einen Felsen als Aufprallort zu verwenden, weil man bei einem Felsen aus der Ferne eventuell besser sieht, ob dort jemand steht. Für sinnlose Zerstörung ist das Risiko aber zu groß, dass der Helikopter nicht dort landet, wo er soll. Es wirkt doch sehr weit hergeholt, dass Alexandra spontan den Aufprallort des Helikopters im Voraus berechnet haben soll.
