### ISSUE TITLE
S. 84: "...explodieren bei starker Erschütterung"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#376]
Free musste noch einige Male hin- und herfliegen, um eine beachtliche Menge Dynamit, mehrere Feuerzeuge, drei Rucksäcke und drei kleine Papiertüten mit Nitro-TNB abzuholen. Einen Teil der Sachen legte Free neben Orakel auf dem Copilotensitz ab.

»Achtung, die Tüten explodieren bei starker Erschütterung!«, warnte Alexandra.

- Das klingt nicht nach einer guten Idee, diese Art Sprengstoff a) generell in einem Hubschrauber mitzunehmen, und sie b) mit einem Modellflugzeug durch die Gegend zu fliegen, nachdem im Satz zuvor gesagt wurde, dass Free relativ rough fliegt.

**Comment by ToBeFree** [comment]
"Free relativ rough fliegt" brachte mich zum Schmunzeln. 😊 

Joa... Hm... Ich glaube, die einzige Person, die diese Tüten verwendet, ist sowieso Alexandra. Die wirft in Fort Knox damit um sich. Wir müssen die Tüten daher nicht mit dem Flugzeug transportieren; es könnte stattdessen auch einfach nur die Rucksäcke und das Dynamit mitnehmen. Dynamit ist bekannt als "sicherer" Sprengstoff, welcher nicht mehr einfach so explodiert - das war der Grund für seine Erfindung und seine Beliebtheit. Zur Herstellung wird erstaunlicherweise eben das ansonsten hochexplosive Nitroglyzerin verwendet - eine Sensation.

Dass Nitro-TNB bei Erschütterung explodiert, wird für eine simple Granatenwirkung im Roman mehrfach genutzt und erwähnt. Das damit verbundene Risiko ebenfalls: Hakon Yang gibt seine Identität als Bright Mountain preis, als er hört, dass Alexandra an Bord damit experimentieren möchte.

Da es bei Fort Knox zum Einsatz kommt, lässt sich der Transport mit dem Hubschrauber wahrscheinlich nicht verhindern. Die Sprengkraft von Nitro-TNB wird im Roman genau definiert, die Erschütterungsempfindlichkeit hingegen nicht. Als ich die Definition geschrieben habe, stand ich vor der Überlegung, auch die Erschütterungsempfindlichkeit in einer physikalisch dafür geeigneten Größe anzugeben. Es gibt tatsächlich diese Möglichkeit. Nur hatte ich befürchtet, dass im Roman Szenen vorkommen, deren Erschütterung eindeutig das Mindestmaß übersteigt. Meine Definition wäre dann beweisbar unlogisch/falsch gewesen, und das hätte mir nicht gefallen.

Kurz: Weil die genaue Erschütterungsempfindlichkeit von Nitro-TNB nirgendwo klargestellt wird, kann es im Roman auch im Helikopter transportiert werden. Es ist dann eben "unempfindlich genug" für diese Anwendung. Es steht nicht einmal irgendwo, ob es stärker oder weniger empfindlich als Nitroglyzerin ist.

Vorschlag: Sprengstofftransport per Modellflugzeug streichen, aber im Helikopter (ohne, dass das extra erwähnt wird!) ist das Nitro-TNB eben mit dabei.

**Comment by yur-y** [comment]
Free musste noch einige Male hin- und herfliegen, um eine beachtliche Menge Dynamit, mehrere Feuerzeuge und drei Rucksäcke abzuholen. Einen Teil der Sachen legte Free neben Orakel auf dem Copilotensitz ab.

So?

**Comment by ToBeFree** [comment]
Klingt gut! Das Ablegen der Sachen ist auch ein netter Einschub. 🙂

**Comment by ToBeFree** [comment]
Ich glaube, an derartigen Details mangelt es der Geschichte ziemlich stark. Das ist ein Vorteil hinsichtlich von Action, schnellen aufeinanderfolgenden Szenen, nicht abreißender Spannung und wenig Langeweile -- Gegenbeispiel: Der Herr der Ringe. Dafür fehlt eben, besonders mit diesem Gegenbeispiel verglichen, ein Großteil der Atmosphäre, die in "guten" Romanen wie selbstverständlich mit einem Großteil des Textes aufwändig aufgebaut wird. In einem Fantasy-Roman ist das sicherlich nochmal deutlich wichtiger als in einer Science-Fiction-Actionstory, aber solche Details dürfen auch bei uns eigentlich nicht fehlen. Leider ist das Hinzufügen dieser Details nicht immer einfach; beim Ausdenken einer Szene kommen mir solche Dinge meist noch nicht in den Sinn. Ich habe dann eine gewisse Grundidee, einen Plan und ein Ziel, und ich setze den literarischen Weg dorthin relativ konsequent und ohne große Umwege um. Das führt zu Detailmangel.
