### ISSUE TITLE
S. 91: {tiny}

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#377]
\begin{tiny}

\textit{»yury? Alexandra?«}

    \end{tiny}

- Der Abstand zur Zeile darüber ist deutlich kleiner als der zur Zeile darunter. Das sieht hässlich aus. Gibt es dafür einen Fix?

**Comment by ToBeFree** [comment]
Sieht auf Papier gar nicht großartig schlimm aus, finde ich. Fiel mir auch nicht auf. Ich sehe aber, was du meinst-- ah. Ich habe gerade #282 gesehen. Ich schreibe dort weiter :)


#282
