### ISSUE TITLE
S. 93: Second Liutenant

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#378]
Ich habe absolut keine Ahnung von Militärrängen, aber würde es nicht eher passen, wenn es der Rang direkt unterhalb des Colonel wäre? Laut https://en.wikipedia.org/wiki/Military_rank wäre das der "Lieutenant Colonel".

**Comment by ToBeFree** [comment]
Ich leider auch nicht 😊 - ich fand halt, das klingt da gut. Da es einen Colonel gibt, könnte ein unbedarfter Leser vielleicht denken, mit "Lieutenant Colonel" wäre der "Colonel Aimbot Johnson" gemeint. Oder so...

Außerdem muss dort oben ja nicht unbedingt derjenige sein, der direkt dem Colonel untersteht. Vielleicht ist ein "Lieutenant Colonel" unten beim Einsatz beteiligt, und der Second Lieutenant darf sich großzügigerweise um die Besenkammer kümmern. 😄

**Comment by yur-y** [comment]
OK, dann bleibt der Second Lieutenant.
