### ISSUE TITLE
Pilot 40 oder "Hakon Yang"?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#379]
Bisher wird er relativ konsequent sowohl vom Erzähler als auch von den anderen "Pilot 40" genannt. Allerdings hat er sich ja vorgestellt, deshalb ist es schon etwas komisch, wenn yury sagt:

»Orakel? Pilot 40⁈«, staunte yury. (S. 95)

**Comment by ToBeFree** [comment]
Oh ja, guter Einfall. Als die Gruppe vor der großen Außen-Stahltür steht, werden alle Namen einmal genannt:

"Als Orakel vorsichtig mit einem
Finger gegen den Stahl drückte, fiel das Tor einfach nach hinten um. yury,
Alexandra, Free und Pilot 40 starrten fassungslos auf 20 Tonnen Schrott."

Bereits bei dieser Szene hatte ich die gleiche Überlegung und habe testweise "Hakon Yang" oder "Yang" eingebaut. Und es liest sich nicht gut, denn der Name ist nicht etabliert und verwirrt dort total. Zudem räumt er in diesem Satz dem Nicht-Protagonisten einen zu hohen Dauer-Stellenwert ein.

Bei _deinem_ Beispiel hingegen fände ich "Orakel? Hakon Yang?" ebenfalls schöner. :)

**Comment by ToBeFree** [comment]
Apropos, dort gehört meiner Meinung nach "zwanzig" statt "20" hinein, besonders nach der "40". 😅

**Comment by ToBeFree** [comment]
Anmerkung: Ist dir aufgefallen, woher der Name Hakon Yang kommt?

**Comment by yur-y** [comment]
Nein, woher? :)

**Comment by ToBeFree** [comment]
https://www.schachburg.de/members/11-hako

**Comment by ToBeFree** [comment]
(kein tatsächlicher Charakterbezug, aber ich fand es ganz lustig, die Burgadministration um General Breit Kiffer herum noch mit Colonel **Aimbot** Johnson und **Hako**n Yang in der Geschichte auftauchen zu lassen. TuXx hat keinen guten Namen dafür. 😉 )
