### ISSUE TITLE
Anzahl Goldbarren

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#388]
Ein Standard-Goldbarren, wie er in Fort Knox liegen könnte, wiegt anscheinend [ca. 12,44 kg](https://de.wikipedia.org/wiki/Barren_(Metall)#Edelmetallbarren). Wenn wir davon ausgehen, dass Pilot 40 seine Beute (falls er welche hatte) nicht den anderen übergeben hat und sie noch halbwegs mobil aus Fort Knox rausgekommen sind, können die vier eigentlich maximal 16 Goldbarren mitgenommen haben (50 kg pro Person). Einer davon ist irgendwas in der Größenordnung von 500.000 Euro wert. Also haben sie zusammen ca. 8 Millionen Euro erbeutet.

Als sie auf Örz ankommen, haben sie "über die Hälfte" des Goldes zu Geld gemacht, haben aber immer noch einen beachtlichen Wert übrig. Sagen wir also, sie haben 10 Barren verkauft. Gefühlt waren sie aber im ersten Teil bei mehr als 10 Goldhändlern (sie laufen ja mehrfach durch ganze Städte und klappern alle ab). Außerdem hat so ein Provinzjuwelier in Sudbury wahrscheinlich keine ~700.000 CAD für einen Goldbarren auf der hohen Kante, oder? Außerdem heißt es im Wikipedia-Artikel, dass diese eigentlich nur von Zentralbanken verwendet werden (und daher noch mal viel misstrauischer machen müssten als ohnehin, zudem wenn der Raub von Fort Knox durch alle nationalen Medien gegangen ist). Auf S. 109 heißt es, dass "mehrere Millionen Dollar" zusammenkamen bei dem Versuch, "das restliche Gold zu Geld zu machen". Sprich, allein dort müssen sie eigentlich 3, 4 Barren verkauft haben.

**Comment by ToBeFree** [comment]
Oh, ich hatte mir irgendwie ca. 4-5 kg pro Barren vorgestellt. Und damals, als die Originalszenen geschrieben wurden, hatte zumindest ich persönlich noch Rucksäcke voller Goldbarren im Sinn. 😃 

Vielleicht könnten die Freunde das Gold vorher zersägen? Aufgrund der Weichheit des Metalls dürfte das kein Problem darstellen, aber der Verkauf eines zersägten Goldbarrenstücks erweckt bei Goldhändlern und Juwelieren sicherlich nicht unbedingt das größte Vertrauen.

Dass gerade in dieser Branche kein Misstrauen gegenüber Diebstahl entgegengebracht wird, halte ich für unrealistisch. Natürlich kann nicht jeder Juwelier aufwändig die Herkunft des Goldes überprüfen, aber man müsste schon sehr skrupellos sein, um diese Barren oder Teile davon ganz ohne Nachfrage zu kaufen. Der Händler müsste anschließend sofort das Diebesgut einschmelzen, um Spuren zu verwischen. Er müsste selbst kriminell sein.

**Comment by yur-y** [comment]
Zersägen dürfte theoretisch wirklich gehen mit einer Metallsäge (die zu beschaffen wäre). Aber die Frage bleibt, ob das nicht sehr misstrauisch macht.

**Comment by ToBeFree** [comment]
Meister Orakel kann das Zeug auch zu Goldstaub zersägen. 😋

**Comment by ToBeFree** [comment]
Vielleicht könnte man mit der Säge und einer Menge Schmirgelpapier beliebige andere Formen daraus herstellen. Kleine Würfelchen zum Beispiel sind vielleicht relativ leicht zu erstellen. Aber wirklich toll ist das auch nicht.

**Comment by ToBeFree** [comment]
Sollen wir das abhaken als "ist eben so"?

**Comment by ToBeFree** [comment]
Obwohl: Nein, jetzt packt mich der Ehrgeiz. :) Orakel zersägt die Barren. Gold ist so weich, dass dabei wahrscheinlich nicht einmal allzu viel "Abfall" anfällt? Das müsste man nachgucken können. Es gibt bestimmt YouTube-Videos von Leuten, die Goldbarren zersägen.
Gegebenenfalls (solange Gold als Material das zulässt) poliert Orakel die Schnittkante bzw. einfach den ganzen Barren mit Schleifpapier. Er bringt die Barrenstücke in schöne Barrenform, sodass aus den großen Zentralbank-Barren kleinere, dünne, schöne Kilogramm-Goldbarren werden, im bekannten Format für Privatanleger und deren flache Schließfächer. Dann schnappt sich Orakel eine Hochprofil-Münze aus härterem Metall, legt die Münze mittig auf den flachen Barren und schlägt mit einem schweren Hammer auf die Münze. Das Motiv der Münze prägt sich auf das Gold ein; fertig ist der "Münzbarren".

**Comment by ToBeFree** [comment]
Goldstaub oder Goldspäne fängt Orakel mit untergelegten Stoffservietten auf. Der wird einzeln verkauft. 

Denkbar wäre auch die Herstellung von Goldgranulat mit Schleifpapier und einer Metallsäge aus den großen Goldbarren . Extrem aufwendig, mit viel "Abfall" verbunden, aber lässt sich vermutlich ziemlich gut an Juweliere verkaufen.
