### ISSUE TITLE
S. 130: Wie errät yury dieses Passwort?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#391]
Gibts dazu ne Auflösung? :D

**Comment by ToBeFree** [comment]
Haha :smile:

Das ist, wenn man so möchte, das Passphrasen-Äquivalent zu "1111", "password" oder "example":

https://www.google.com/search?q=correct+horse+battery+staple

**Comment by ToBeFree** [comment]
https://www.explainxkcd.com/wiki/index.php/936:_Password_Strength

Der Witz dabei, dass jemand es wirklich verwendet, ist, dass der Benutzer einen eigentlich sehr sicheren Passwortvorschlag nutzt... Etwa so, als ob in der Zeitung empfohlen wird, ein Passwort wie "J435976x++10" zu nutzen, und jemand dann genau dieses Passwort nutzt.

**Comment by yur-y** [comment]
Haha, OK :D
