### ISSUE TITLE
"Noch mal"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#392]
Immer, auch in "verdammt noch mal". Aber: "nochmals". Kurzes Strg+F hat ergeben, dass ich das auch schon viel zu oft übersehen habe. Ich habe jetzt alle occurrences ersetzt, aber falls jemand noch mal (^^) eine Szene hinzufügen sollte, dran denken. :)

**Comment by ToBeFree** [comment]
Aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by ToBeFree** [comment]
Na, da habe ich fast Panik bekommen.

https://www.duden.de/rechtschreibung/noch_mal

Meine nie wieder abgewöhnbare Schreibweise, "nochmal", ist aber durchaus als "alternative Schreibung" auch im Duden vermerkt. Natürlich sollten wir im Roman wohl eher die vom Duden empfohlene Schreibweise verwenden. Daher ist dieses Issue sehr gut, auch um das für weitere Korrekturen festzuhalten. Ich werde wohl die nächsten Jahre damit verbringen, mich auf "noch mal" umzugewöhnen. Das ging mir schon mit einigen anderen Wörtern so - dieses Lektorat bringt mir wirklich etwas fürs Leben. xD

**Comment by ToBeFree** [comment]
Kein Fehler, nur eine Notiz
