### ISSUE TITLE
Anführungszeichen kursiv, wenn der Text kursiv ist

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#393]
Sollen bei Kursivdruck einer gesamten Aussage auch die Anführungszeichen kursiv sein?

**Comment by yur-y** [comment]
Oh. Ich fürchte, ich habe es jetzt überall andersherum gemacht.^^

**Comment by ToBeFree** [comment]
Ausnahme: »\textit{Geheimauftrag zur proaktiven Wiederherstellung der Selbstkonsistenz des Universums}«

als Zitat innerhalb einer echten wörtlichen Rede.
