### ISSUE TITLE
Logische Probleme beim Mona-Lisa-Diebstahl

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#394]
Format: 77 × 53 cm (https://de.wikipedia.org/wiki/Mona_Lisa)

See the problem?

(Mal abgesehen davon, dass natürlich die gesamte Szene vollkommen unrealistisch ist, aber die gröbsten Logikprobleme sollte man denke ich trotzdem beseitigen.)

**Comment by ToBeFree** [comment]
Ah, das Ding ist zu groß für einen Rucksack?

Nehmen wir mal an, Orakel ist ein totaler Banause und faltet das Ding notfalls in eine Richtung. Sinnvoller wäre wohl, das Bild zu rollen, aber mir geht es um etwas anderes:

Wenn man das Bild in eine Richtung beliebig rollt oder faltet, ist nur noch die kürzeste Seite für die Rucksackdimensionen interessant. Das wären dann trotzdem noch 53 cm. Ein relativ großer Rucksack, wenn das die Rucksack-Innentaschenhöhe ist. Am Eingang gibt es einen Security-Check. Rucksäcke sind wohl erlaubt ( ), und zwar bis zu den Maßen...

...jetzt musste ich schmunzeln.

`Only luggage not exceeding **55** x 35 x 20 **cm** (21.5 x 13.5 x 7.5 inches) can be accepted and must be placed in the lockers after being checked.`

Anders gesagt: Die Mona Lisa darf mit. Sehr freundlich. 😉 


In diesem Video laufen die Besucher ebenfalls mit Rucksäcken durch die Gegend: https://www.youtube.com/watch?v=PNjuSMSy9MU

**Comment by ToBeFree** [comment]
Ich habe jetzt einen Zollstock genommen, um mir die Dimensionen besser vorstellen zu können. Ein Rucksack mit einer Größe von 53 cm ist groß. Vielleicht sogar auffallend groß. Er ist nicht überdimensional und riesig, aber "groß" ist sicherlich eine gute Beschreibung.

Andere Überlegung: "**stopfte** es in seinen Rucksack"? Nicht gerade die feine Art, aber mit dem Adjektiv würde ich das Bild auch in meiner Hosentasche verstaut bekommen. 😄

**Comment by ToBeFree** [comment]
Merge with #397

**Comment by ToBeFree** [comment]
"Stopfen" und "Rollen"... Das Bild wurde auf eine Papyrus-Holzplatte gemalt.

Problem gelöst.
