### ISSUE TITLE
Titel 2. Teil ("Die Erde ist nicht genug")

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#396]
"Die Erde ist nicht genug!" Evtl. das Ausrufezeichen entfernen?

**Comment by ToBeFree** [comment]
Oh, findest du? :)

Wenn du möchstest, gerne. Ich fand es dort zumindest nicht störend oder auffallend. Andererseits enthält der Titel des ersten Teils keine Sonderzeichen.
