### ISSUE TITLE
Glaspyramide

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#397]
Die Glaspyramide *ist* nicht das Louvre. Sie ist dessen Hauptein- und ausgang, aber die Ausstellungsstücke selbst hängen dort ja nicht. Deshalb ergibt es auch überhaupt keinen Sinn, dass Orakel und Free beim Diebstahl der Mona Lisa *durch die Pyramide* fliehen, statt irgendeinen anderen (Not-)Ausgang zu nehmen. Siehe auch: https://www.louvre.fr/sites/default/files/medias/medias_fichiers/fichiers/pdf/louvre-plan-information-deutsch.pdf

**Comment by ToBeFree** [comment]
Oh! Ich hatte eine falsche Vorstellung von der vertikalen Struktur dieses Museums. Das PDF ist sehr gut. Ich habe jetzt auch noch auf YouTube nach "louvre visit" gesucht, um das Hineingehen und Hinausgehen mitzuerleben.

https://www.youtube.com/watch?v=PNjuSMSy9MU

Aber wenn ich das auf dem Plan richtig sehe, wird die Mona Lisa im ersten Obergeschoss relativ zentral in einem großen Raum präsentiert. Um das Gebäude von dort aus fluchartig verlassen zu können, muss man wohl eine Treppe hinunterlaufen -- das sollten wir in die Geschichte einbauen. Gerade bei Treppen lassen sich Fluchtszenen wahrscheinlich sehr schön beschreiben (nimmt mehrere Stufen auf einmal, überspringt die letzten fünf Stufen, stolpert rückwärts einige Stufen abwärts und dreht sich dabei wieder richtig herum, rutscht am Geländer herunter o.ä.).

Und von dort aus geht es dann, wenn ich das richtig sehe, relativ gut und schnell auch durch den Hauptausgang raus? Man müsste dafür allerdings noch eine Etage weiter hinunter und danach wieder an die Oberfläche laufen.

Was mich gerade wundert: Gibt es denn zumindest irgendwo auf dem Weg eine Glastür, die außerhalb der Öffnungszeiten geschlossen ist und sich vielleicht im Alarmfall schließen lässt?

**Comment by ToBeFree** [comment]
Fail: Falsche Commit-Beschreibung. Das hier wurde nicht gelöst.

**Comment by ToBeFree** [comment]
Commit "reverted" und verbessert. Dieses Issue hier muss noch gelöst werden.

**Comment by ToBeFree** [comment]
So, das wird wieder ein schönes Projekt. 😅

**Comment by ToBeFree** [comment]
- [ ] Glasscheibe vor der Mona Lisa
- [ ] Treppen auf dem Weg: "nimmt mehrere Stufen auf einmal", "überspringt die letzten fünf Stufen", "stolpert rückwärts einige Stufen abwärts und dreht sich dabei wieder richtig herum", "rutscht am Geländer herunter" o.ä. -- das wird lustig.
- [ ] Warum durch die Glaspyramide? Weil das Wachpersonal die Notausgänge bewacht. Die Freunde laufen zu einem Notausgang, sehen dort den Wachmann, drehen panisch um, werden von diesem Wachmann nun ebenfalls verfolgt und suchen ihr Glück nach einer irren Jagd durchs Museum und einem Sprung über mehrere Treppengeländer als Abkürzung schließlich in der Glaspyramide.

**Comment by ToBeFree** [comment]
Die Flucht-Beschreibung lässt sich vielleicht noch verschönern, aber die Logikfehler wurden nun hoffentlich behoben.
