### ISSUE TITLE
Buchformate, Veröffentlichungsplattformen

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#399]
Vom **fertigen** Buch, _nach_ der Veröffentlichung in Druckform, ausgehend, werden wir verschiedene offizielle Buchformate anbieten:

* **PDF:** Hauptformat, bis auf die fehlende ISBN (!!)\*, <s>Hinweis auf Kaufmöglichkeit des Buches</s> (vermeiden, damit das PDF nicht als SPAM interpretiert wird), Impressumshinweis etc. identisch mit der Druckfassung.
* **HTML:** Grundlegende, einfach strukturierte Textdatei mit Inline-CSS (!!). Von außen werden nur Bilder geladen, die über relative (!) URLs referenziert werden. Das komplette Buch mit Bildern besteht ausschließlich aus einer einzigen HTML-Datei und mehreren JPG-/PNG-Dateien. Keine CSS-Dateien, und bloß kein Javascript. Javascript nicht einmal inline.
* **LaTeX-Quellcode:** Natürlich. Idealerweise mit der Dateiendung ".txt", damit Suchmaschinen, Webserver und Browser die Textdatei als solche erkennen, herunterladen, sichern und indizieren. Über das Zeilenende müssen wir uns dabei nochmal Gedanken machen, denn unter Windows wird es ohne CRLF Probleme geben. Es kann sinnvoll sein, die öffentliche .txt-Version durch das Linux-"unix2dos"-Programm laufen zu lassen.
* <s>Möglicherweise</s> **EPUB** <s>abhängig davon, wie einfach das zu realisieren ist, ob es gut aussieht, und ob wir bei EPUB-Veröffentlichung über einen Verlag überhaupt legal an die Quelldatei herankommen und diese kostenlos verbreiten dürfen. Wahrscheinlich Konvertierung mit dem freien "Calibre"-Programm statt mit einer proprietären Verlagslösung.</s><br>Update: EPUB kommt auf jeden Fall; siehe zwei Kommentare weiter unten. 🙂 

Weniger bevorzugt, aber ebenfalls offiziell von uns angeboten werden folgende Formate, welche leider NICHT den gesamten Inhalt des Buches wiedergeben können. Vielmehr handelt es sich um eine Möglichkeit, zumindest den Textinhalt des Buches an verschiedenen ungewöhnlichen Stellen zu verewigen.

* **Markdown:** Reiner, roher Text. Lesbar mit jedem Texteditor. Überschriften sind als solche sofort erkennbar, obwohl es keine richtige "Formatierung" gibt. Im Interesse der Lesbarkeit als reiner Text wird auf manche Formatierungsmöglichkeiten **verzichtet**. Das gilt wohl besonders für Quellcode-Stellen und bestimmte Sonderzeichen.
* **BBCode:** Veröffentlichung als riesiger Beitrag im Archiv der Schachburg, und als Überraschungsbeitrag im toten Freiwuppertal-Forum. Es wird ausschließlich BBCode-Syntax verwendet, welche möglichst unabhängig von der eingesetzten Forensoftware funktioniert. Das Vorhandensein einer offiziellen BBCode-Version hat historische Gründe: Die Infinite Adventures wurden ursprünglich in einem phpBB-Internetforum geschrieben, und genau dorthin kehren sie fast 10 Jahre später zurück.

Die Veröffentlichung von Sicherungs-Exemplaren erfolgt auf folgenden Plattformen:

* Internet Archive: Alle Formate. Falls möglich, inklusive Versionsgeschichte als ZIP-Datei.
* Project Gutenberg (self.gutenberg.org)? Achtung, Read-Only und eventuell nicht lizenzkompatibel
* GitHub: Alle Formate, vollständiger Quellcode.
* BitBucket: 1GB-Repository-Limit. Wenn alles fertig und aufgeräumt ist, schaffen wir das wahrscheinlich.

Die Veröffentlichung kann/darf voraussichtlich nicht auf folgenden Plattformen erfolgen:

* Wikibooks: Leider nur für Fachliteratur.
* Wikisource: Wahrscheinlich nur für gedruckte, manuell digitalisierte Bücher, die als Quelle für Wikipedia nützlich sind und vorher nicht online erhältlich waren.
* Wikicommons: Nur für Bilder, nicht für Text.

\*Anmerkung zur ISBN: Auf keinen Fall eine feste ISBN als Bestellempfehlung ins PDF packen.

Q: "Wieso? Gerade die PDF-Version kann man doch sehr einfach bei Bedarf aktualisieren."

A: "Eben nicht. Die PDF-Version geistert unkontrolliert durchs Netz. Sie braucht unbedingt ein Datum und eine Versionsnummer, und das gedruckte Buch soll man dann eben bei einem Buchhändler erfragen.

Zudem ist eine ISBN speziell für eine bestimmte Form der Veröffentlichung bestimmt; bereits eine Taschenbuch-Ausgabe hätte eine andere ISBN. Eine Neuauflage hat ebenfalls eine andere ISBN. Die ISBN ist nichts, was nach 20 Jahren noch auf die aktuellste Fassung verweisen muss -- im Gegenteil: Genau das tut sie absichtlich nicht."

**Comment by yur-y** [comment]
Ist EPUB nicht einfach ein umdeklariertes HTML mit ein paar Zusatzfunktionen? Wenn wir eine funktionierende HTML-Datei haben, kann ich mir vorstellen, dass Calibri o. ä. damit sehr gut umgehen könnten, und alle Leser_innen mit E-Book-Readern wären wohl dafür dankbar, wenn es das Format gäbe.

**Comment by ToBeFree** [comment]
@yur-y Frohes Neues! 😃 Ich glaube, du hast recht, ja. Ich werde auf jeden Fall ein EPUB erstellen, notfalls (oder auf jeden Fall teilweise) von Hand. Der Quelltext kommt dann ins Repository.

Über Drittanbieter vertriebene E-Books werde ich mit dem Hinweis versehen, dass diese aufgrund der AGB des Anbieters nicht frei lizenziert werden können: die CC-BY-SA-Lizenz erlaubt explizit das Umgehen von technischen Schutzmaßnahmen, falls welche vorhanden sind. Das darf ich natürlich nicht erlauben, weil ich dieses Recht selbst nicht besitze. Der Hinweis wird vielleicht so aussehen:

"...Eine frei lizenzierte, DRM-freie Version dieses E-Books im EPUB-Format ist möglicherweise auf infiniteadventures.de erhältlich."

**Comment by yur-y** [comment]
Es wird über Drittanbieter vertriebene E-Books geben? Wieso das?

**Comment by ToBeFree** [comment]
Das "richtige" Buch wird ja auch über einen Drittanbieter vertrieben. Der nennt sich "Buchhändler". :P 

Damit die Infinite Adventures auch bei denjenigen ankommen, die einen E-Book-Reader ohne .epub-Importfunktion oder ohne Computeranschluss besitzen. Und bei denjenigen, die nicht technisch versiert genug sind, um etwas anders zu nutzen als den offiziellen E-Book-Store ihres Geräts.

**Comment by yur-y** [comment]
Das war gar nicht als Kritik gemeint^^ Ich hatte mich nur gefragt, wer das denn überhaupt bereitstellen sollte. (Im Gegensatz zum Buchhänder, der das Buch ja nur auf Bestellung liefert.) Oder bietet epubli an, ein eigenes E-Book über die diversen Stores zu vertreiben? Kostet das was?

**Comment by ToBeFree** [comment]
Achso 🙂 -- ja, richtig, epubli bietet das an, und die Veröffentlichung ist kostenlos. Pro Buch fällt eine Kommissionsgebühr in Höhe von 30% des Nettoerlöses an. Diese 30% werden berechnet, nachdem Umsatzsteuer und ggf. die Kommissionsgebühr des E-Book-Stores abgezogen wurden.

Der Preis für das E-Book sollte mindestens 20% unter dem Preis der Printausgabe liegen. Wir werden diese Vorgabe problemlos einhalten. Für den extrem unwahrscheinlichen und unerwarteten Fall, dass das Buch wie früher Harry Potter im Selbstverlag durch die Decke geht, achte ich darauf, dass das Honorar für Printausgabe und E-Book-Ausgabe ca. einen Euro beträgt.

**Comment by ToBeFree** [comment]
Achso 🙂 -- ja, richtig, epubli bietet das an, und die Veröffentlichung ist kostenlos. Pro Buch fällt eine Kommissionsgebühr in Höhe von 30% des Nettoerlöses an. Diese 30% werden berechnet, nachdem Umsatzsteuer und ggf. die Kommissionsgebühr des E-Book-Stores abgezogen wurden.

Der Preis für das E-Book sollte mindestens 20% unter dem Preis der Printausgabe liegen. Wir werden diese Vorgabe problemlos einhalten.
