### ISSUE TITLE
Bonusband-Urkunden: Beispieltexte: US-amerikanische "Commissions" in zivile Positionen

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#437]
Kopiert von

https://en.wikipedia.org/wiki/Commission_(document)#Examples_of_Commissions_to_Civil_Offices

===United States===
The Constitutional requirement mentioned above, that the President commission all officers of the United States, includes a wide range of civilian officials, including justices of the Supreme Court and other federal judges, U.S. attorneys and marshals, the heads of executive departments, subcabinet officials down to the level of assistant secretary, diplomatic representatives, and members of the Foreign Service, among others.  Commissions are issued in the name of the President, either under his own signature or that of an official expressly delegated to act on his behalf, and under either the great seal of the United States or, if prescribed by law, the seal of the department in which the appointment is made.

A typical commission for a Presidentially-appointed, Senate-confirmed civilian official in the Executive Branch would read:
{{quote|
''John E. Doe 
''President of the United States of America

''To all to whom these presents shall come greeting:  Know ye that reposing special trust and confidence in the Integrity and Ability of Rebecca Frances Roe of Kansas, I have nominated and, by and with the advice and consent of the Senate, do appoint her Secretary of Transportation and do authorize and empower her to execute and fulfill the duties of that Office according to law, and to have and to hold the said office with all the powers and privileges thereunto of right appertaining, unto her the said Rebecca Frances Roe during the pleasure of the President of the United States for the time being

''In Testimony whereof I have caused these Letters to be made Patent and the Seal of the United States to be hereunto affixed.

''Done at the City of Washington this second day of December in the Year of our Lord two thousand seventeen and of the Independence of the United States of America the two hundred and fortieth.

''By the President	[President's signature]

''[Great Seal]  [Secretary of State's signature]
}}

For certain positions, other characteristics such as "prudence" (for ambassadors) or "wisdom, uprightness, and learning" (for judges) may be used in addition to or instead of "integrity and ability."  If a position is for a fixed term of years or "during good behavior," the appropriate wording replaces the clause beginning "during the pleasure of the President."

Commissions of officers in the [[U.S. Foreign Service]] are also signed by the [[President of the United States|President]].  The commission of a newly commissioned officer reads:

{{quote|
''The President of the United States of America

''To (name of officer) Greeting

''Reposing special trust and confidence in your Integrity, Prudence and Ability, I have nominated and, by and with the advice and consent of the Senate, do appoint you a Foreign Service Officer, a Consular Officer, and a Secretary in the Diplomatic Service of the United States of America, and do authorize and empower you to do and perform all such matters and things as to the said offices do appertain, and to have and to hold the said offices, and to exercise and enjoy all the rights, privileges and immunities thereunto appertaining, during the pleasure of the President of the United States.

''In testimony whereof, I have caused the Seal of the United States to be hereunto affixed.

''Done at the City of Washington this .... day of .... in the year of our Lord .... and of the Independence of the United States of America the ....

''By the President  (President's signature)
}}

The commission is countersigned by the Secretary of State, and the singular Great Seal of the United States, entrusted to the Secretary under the 1789 statute creating the [[United States Department of State|Department of State]],<ref>1 U.S. Statutes at Large, ch. 4, sec. 1</ref> is affixed.

**Comment by yur-y** [comment]
Darf man fragen, wofür das gut ist? ;)
