### ISSUE TITLE
"ENDE des ersten Teils" (S. 139)

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#438]
Würde ich evtl. rausnehmen, was meinst Du?

**Comment by ToBeFree** [comment]
Herzlich willkommen zurück! 💚 😃 👍 

Ja, sehr gerne. Ich glaube, das diente mir während der Überarbeitung als Such-Anker, mehr nicht.

**Comment by yur-y** [comment]
✔
