### ISSUE TITLE
Silbentrennung bei Eigennamen

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#439]
Ich weiß nicht, ob es möglich ist, dem Programm allgemein zu verbieten, bestimmte Wörter zu trennen. Falls ja, würde ich glaube ich dazu tendieren, die bestehenden Trennungen, die bei Orakel ("Ora-kel") und Alexandra ("Alexan-dra" und "Alex-andra", was ich persönlich am unschönsten finde) auftauchen, zu verbieten, auch auf Kosten von größeren Leerzeichen hier und da.

**Comment by ToBeFree** [comment]
Sehr, sehr guter Punkt. Ich habe schon mehrfach überlegt, wie ich das "Alex-andra" loswerde. Vom Duden wird es als "möglich" aufgelistet, aber nicht empfohlen: https://www.duden.de/rechtschreibung/Alexandra

Das "Alex", welches dann am Ende einer Zeile steht, sieht halt einfach merkwürdig aus. Generell gilt das für viele Wörter, die in getrennter Form einen anderen Sinn ergeben ("Kombi-Nationsgabe")

Und ja, die Möglichkeit müsste es geben. Man kann für bestimmte Wörter im Dokumentenheader festlegen, wie sie (falls überhaupt) getrennt werden sollen. Ich weiß nicht, wieso ich das bisher nicht ausprobiert habe.

Versuche mal, eine Zeile vor \begin{document}, im Kopfteil einzufügen:

  \hyphenation{Ale-xan-dra}
  \hyphenation{Orakel}

(fände ich in Ordnung), oder strikter:

  \hyphenation{Alexan-dra}
  \hyphenation{Orakel}

oder auch gerne tatsächlich:

  \hyphenation{Alexandra}
  \hyphenation{Orakel}

**Comment by yur-y** [comment]
Oh, es gibt tatsächlich Duden-Empfehlungen für die Trennung von Eigennamen! Spannend. Ich finde aber, wenn wir schon Ale|xan|dra oder Alexan|dra erlauben, können wir auch Ora|kel erlauben. Würde Dir aber die Entscheidung überlassen, welche von den drei Optionen wir nehmen.

**Comment by ToBeFree** [comment]
Testweise können wir die Bindestriche natürlich auch komplett weglassen. Dir war ja ursprünglich eine von mir jetzt festgelegte Trennung negativ aufgefallen. Vielleicht schafft LaTeX es, durch geschickte Wahl von Buchstaben- und Wort-Abständen die Löcher zu kaschieren.

**Comment by yur-y** [comment]
yury und Free werden bisher nie getrennt, ich füge aber zur Sicherheit mal alles ein. Ob ich die Beschwerden sehe, bin ich mir aber nicht sicher - Du wirst sie aber ja spätestens entdecken, wenn Du das nächste Mal kompilierst.

**Comment by ToBeFree** [comment]
LaTeX meckert dann solche Sachen wie "underfull hbox" o.ä., welche meist gar nicht allzu dramatisch sind. Es sind aber gute Ansatzpunkte, um nochmal nachzusehen. Aber ja, mach ich gerne :)
