### ISSUE TITLE
S. 148/149: Seitenumbruch vor der Formel

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#440]
Zumindest ist das in meiner derzeitigen Version so. Finde ich vom Layout her nicht optimal; falls es nach allen Korrekturen immer noch so ist, sollten wir uns da was überlegen.
Ach ja, und woher kommt eigentlich die Formel?

**Comment by ToBeFree** [comment]
Zum angesprochenen Problem: Guter Punkt, kommt auf die Merkliste für die gemeinsame Überarbeitung!

Zur Formel: Da hätte ich noch viel mehr Rechnungen einfügen können, aber spätestens dann muss man die folgende Quelle angeben: https://en.wikipedia.org/wiki/Alcubierre_drive#Mathematics_of_the_Alcubierre_drive

Sollte man vielleicht generell tun. Ich habe die eine Formel als Allgemeingut dort eingebaut, aber guter Stil ist das wahrscheinlich nicht.

Das Zitat darf nicht zu lang sein, sonst ist es kein Zitat mehr, sondern eine Nutzung nach Wikipedia-Lizenz, und die würde sofort zu Problemen führen. Der "Share-Alike"-Teil der bei Wikipedia verwendeten 3.0-Version der CC-Lizenz ist inkompatibel mit allen anderen Lizenzen auf der Welt, inklusive unseres 4.0-Updates. Außerdem ist die Autorenliste dann fragwürdig, denn es stammt nicht mehr das gesamte Werk von uns.

Vielleicht kann man die Formel aus einer von Alcubierres Arbeiten zitieren, an Wikipedia vorbei. Die Wikipedia-Informationen kommen ja irgendwo her. Das sieht als Quellenangabe schöner aus, und macht eigentlich auch mehr Sinn.

**Comment by ToBeFree** [comment]
Okay, nochmal betrachtet. Wenn LaTeX dort einen Umbruch einfügt, ist das von LaTeX entschieden worden, weil alle anderen Lösungsmöglichkeiten "noch hässlicher" aussähen. Wo letztendlich die Zeilenumbrüche landen, ist in einem solchen Fall absichtlich nicht die Entscheidung der Autoren. Möglicherweise etwas ernüchternd, aber eine schwer umstößliche Feststellung: Diesen Bug sollte man, wenn es aktuell überhaupt noch einer ist, nicht hier, sondern beim LaTeX-Interpreter melden.
