### ISSUE TITLE
S. 149: Die Steuerung für die Raketentriebwerke funktioniert nicht mehr...

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#441]
...und die vier schlafen deshalb ein? Sollte das nicht Panik auslösen?

**Comment by ToBeFree** [comment]
Haha, tatsächlich. Ja, das liest sich merkwürdig, ist aber wirklich so gemeint. Wir sollten das umformulieren.

Erklärung: Klar, das gibt erstmal Panik. Und dann Verzweiflung. Resignation. Schließlich Schulterzucken und Müdigkeit, zumal ja angeblich durch irgendwelche mathematischen Formeln die Sicherheit der Reise garantiert worden ist. 😄

**Comment by yur-y** [comment]
Na ja, aber da glauben sie ja noch nicht, dass wirklich eine Reise stattfindet, oder?

**Comment by ToBeFree** [comment]
Oh.
Daran hatte ich gar nicht gedacht.

Hm.

Wenn die Freunde davon ausgehen müssten, entweder im Helikopter letztendlich zu ersticken, oder die Situation schnellstmöglich zu lösen, dann machen sie sich eventuell über Funk o. ä. bemerkbar. Sie würden es in ihrer Verzweiflung zumindest auf jeden Fall versuchen. Eine Beschreibung solcher Vorgänge würde aber mit einem Schlag die verspielt-absurde IA-Atmosphäre durchbrechen und diesen Teil des Romans in eine Horrorgeschichte verwandeln. Nicht gut.

Es muss also tatsächlich eine Lösung her, und ich weiß noch nicht, welche dafür gut geeignet ist.
