### ISSUE TITLE
ISG-Gewicht durch Silizium-Kugelgröße definieren (Avogadro-Projekt)

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#443]
**Anmerkung von ToBeFree: Siehe letzter Kommentar, der Rest ist erledigt!**

-----

...weil einige der bisherigen ziemlich inkonsistent waren.

1 Örz-Jahr = knapp 344 Örz-Tage (343 = 7^3 -> ein weiterer Grund für die Äöüzz, im 7ersystem zu rechnen)
1 "Mön" = 49 Örz-Tage - obwohl Örz keinen Mond hat (oder?)
1 Örz-Woche = 7 Örz-Tage
1 Örz-Tag = 7^2 Örzklonks (nicht "Klönks"!) ≈ 28 Erdstunden (Die Klonk-Angaben für die Bleibefrist und die Jobsuche habe ich daher auch verändert, weil sie anscheinend sowieso keine Freakangaben enthielten)
1 Örzklonk (Ö) = 7^4 Örzklöks ≈ 34 Minuten
1 Örzklök (ö) ≈ 0,85 Erdsekunden

1 ISG ≈ 1/2 Kilogramm (ich wollte keine potenziellen Freakangaben verändern und sonst passte es mit den Goldbarren nicht)

Die Erklärung für Äzz bleibt, der Polizist sagt aber nicht mehr "Das sind ja mindestens 3 Milliarden Äzz" (so viel mehr Gold als die zwei verkauften Goldbarren können sie nicht mehr haben und ihm wird auch nicht alles gezeigt), sondern "Das sind ja mindestens 49 Millionen Äzz".

**Comment by ToBeFree** [comment]
Das ist großartig. 😃 

* Örz-Jahr: Sehr gute Überlegung. Wow. (Anmerkung für die Zukunft, 7^3 sind "1000_7", das musste ich mir gerade nochmal kurz bewusst machen) Nur eine Nachfrage: "knapp 344", weil die Natur eben nicht ganz so funktioniert, wie man sie mathematisch haben möchte, richtig? Siehe "Schaltjahr" und "Schaltsekunde" auf der Erde. Dann gerne!
* Mön: lol -- gute Einheitenwahl. Und gute Frage: Nein, eigentlich hat Örz keinen Mond, denn es war nie von einem Mond die Rede, und der wäre bestimmt irgendwo aufgetaucht. Andererseits wird seine Existenz auch nirgendwo explizit verneint; Örz könnte sogar _mehrere_ Monde haben. Dass der wichtigste dieser Trabanten sich dann aber ausgerechnet in Mön-Intervallen sehr mathematisch nützlich dreht, wäre doch etwas weit hergeholt. Also gerne "Mön", ohne dass es einen echten Mond dafür gibt. Und der Grund für die Bezeichnung ist irgendwo in der Geschichte zu suchen, die aber offenbar keinen lebenden Äöüzz interessiert. Oder die Geschichte ist ein intimes/unangenehmes Geheimnis, über welches die Äöüzz grundsätzlich nicht mit Fremden reden. Das galaktische Koordinatensystem ist ja ebenfalls irdischen Ursprungs, und die vier Freunde wundern sich bereits darüber. Gleiches gilt für den Namen "Örz", der sehr nach "Earth" klingt, und die gesamte Örzlängü-Sprache.
* Örz-Woche ist eine gute Bezeichung, sonst müsste man sich tausende Namen merken. Wenn man es aber schafft, eine Einheit zu finden, deren Name sofort die Bedeutung klarmacht, dann ist das kein Problem. Bei "Mön" ist das ja der Fall. Wir könnten die Wochen als "Wük", "Wöök", bezeichnen, oder so. Sieht aber doof aus. ^^ Mir gefällt dein Vorschlag.
* Örz-Tag: Moment, wieso sind 49 Erdsekunden ein Tag? Oooh. Ich verstehe. Ich glaube, das doppelte Gleichheitszeichen in einer Zeile in deinem Beitrag ist ein wenig missverständlich. 🙂  Dann: Sehr schön gelöst. Nutzt das Siebenersystem, nutzt mathematisch eindeutig verständliche Zusammenhänge, und ist trotzdem erdähnlich. Wunderschön!
* Örzklonk: Gute Unterscheidbarkeit zwischen den Bezeichnungen "Klonk" und "Klök". Ist dadurch nicht allzu fehleranfällig. Gefällt mir. Ansonsten könnte man stattdessen "Klump" oder ähnliches überlegen, um wirklich ganz klar zu unterscheiden. Das ist aber wahrscheinlich eher unschön und nicht erforderlich.

* ISG: Gerne Neudefinition, wenn dir dazu etwas cleveres einfällt -- wäre aber ein bisschen schade für die Freakangabe-Szene bei Äürüm, an der ich mehrere Stunden gesessen habe. Falls die in ähnlicher Form erhalten bleiben kann, bzw. durch die Neudefinition nicht kaputtgeht, sehr gerne. 😅

**Comment by ToBeFree** [comment]
Ich habe schamlos das GitHub-Privileg des Repository-Erstellers genutzt und oberhalb deines Beitrags eine Anmerkung eingefügt. Falls das doof erscheint, kannst du sie gerne wieder löschen. 😄

**Comment by yur-y** [comment]
- "Klonk": War auch vorher die Formulierung. Es kam nur einmal "klönk" vor, daher die Klarstellung.
- ISG: Die Freakangabe bleibt ja gerade erhalten, wenn 1 ISG = 500 Gramm ist... Ist doch in Ordnung, oder?

**Comment by ToBeFree** [comment]
Ja, ist vollkommen in Ordnung; ich überlegte nur, ob man vielleicht weiter gehen kann und sich auch dort etwas Wissenschaftliches ausdenkt. Vielleicht etwas, das im Gegensatz zur kommenden Kilogramm-Neudefinition auf der Erde tatsächlich mathematisch schön ist. Keine nachträgliche krumme Nummer, die eine ursprüngliche Fehlentscheidung nachbilden soll. Eher so etwas wie "Das 7^7^7-fache eines Silizium-Atom-Gewichts". Das Ergebnis darf sehr gerne so genau wie möglich 500 Gramm entsprechen, ohne dabei an Eleganz zu verlieren. 

Ich wäre trotz des damit verbundenen Aufwands dafür, das Issue offen zu lassen, denn das reizt mich sehr. Wenn man eine SciFi-Serie beginnt, dann hat man die Möglichkeit, sich über solche Sachen frühzeitig Gedanken zu machen und ein genial durchdachtes System zu erschaffen - - - oder man merkt erst nach mehreren Romanveröffentlichungen, dass man am Anfang etwas vergessen hat. Etwas, das eigentlich richtig cool gewesen wäre. 😄
