### ISSUE TITLE
"Grundriss" des Raumschiffs in Textform drinlassen?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#444]
"Von oben sah das ungefähr so aus: (‑o‑)" (S. 183)

...oder doch durch eine "richtige" Zeichnung ersetzen?

**Comment by ToBeFree** [comment]
Mir gefällt die Schlichtheit der Text-Definition, die ganz ohne Zusatzgrafik auskommt -- aber ich versende im Gegensatz zu normalen Menschen ja auch Text-Only-E-Mails. 🙄 😅 

Ich hab schon überlegt, irgendjemanden gegen ein bisschen Geld um eine nette technisch aussehende Zeichnung zu bitten, idealerweise eine Vektorgrafik, die man in den Bonusband einbauen könnte und die frei lizenziert sein müsste. Grundsätzlich kann ich auch mit Inkscape umgehen, aber dort bekomme ich bisher nur absolute Grundformen zustande. LibreOffice Draw ist ein bisschen benutzerfreundlicher, erstellt aber beim Export teilweise kaputte oder dämlich programmierte SVGs. Hmm Hmm.

Also, von mir aus einfach so lassen. Und demnächst vielleicht eine Zeichnung. Vielleicht auch erst in den IA3... 🙂

**Comment by ToBeFree** [comment]
Eigentlich könnte Orakel mal wieder etwas zeichnen. 😅 👍 

Ich schick ihm mal einen Link hierzu. Fragen kostet nichts.

**Comment by ToBeFree** [comment]
Im "ia-trilogy-media"-Repository gibt es erste SVG-Entwürfe für eine Blaupause. Ich habe die Maße der 4-6692 im Roman genauer beschrieben.
