### ISSUE TITLE
Die Jobs der vier auf Örz...

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#445]
S. 180: "Zwei Tage später standen die vier Freunde vor einer Baustelle und
begutachteten die Überreste des Hochhauses, die gerade mit großen Last-
wagen abtransportiert wurden. Orakel hatte inzwischen einen Job als
Restaurantt ester bei einer großen Zeitung gefunden, und Free verbrachte
täglich einige Stunden damit, kaputte Örztöps auseinanderzuschrauben.
Altersbedingt ausgefallene Teile wurden durch neue ersetzt; die repa-
rierten Geräte wurden anschließend mit kleinen Paketdrohnen zu ihren
Besitzern geliefert. Nicht selten landete im Gegenzug ein großzügiges
Trinkgeld auf dem Konto der vier Freunde."

...und was macht Alexandra? An dieser Stelle steht nichts, vier Seiten später ist sie plötzlich "gnadenlose Literaturkritikerin", wobei darauf auch nie wieder Bezug genommen wird, wenn ich das richtig sehe. Damit wäre sie die einzige der vier, die nicht ihr offensichtliches Interessengebiet (Chemie) zu ihrem Job gemacht hat?

**Comment by ToBeFree** [comment]
Oh! Naja, ursprünglich stand da was von Sprengstoff-Verkäuferin, aber das funktioniert ja in mehrerer Hinsicht nicht.

Ja, Literaturkritikerin hatte ich überlegt, weil es sehr kompatibel mit den Abenteuerreisen ist und keinen festen Arbeitsplatz voraussetzt. Andererseits hat Orakel genau dieses Problem, zumindest in abgemilderter Form: Man kann ja auch, als Extrembeispiel, die Gefängniskantine auf ugghy testen und einen lustigen Bericht darüber veröffentlichen.

Auch Frees Job ist reisetauglich.

Was könnte Alexandra tun, im chemischen Bereich? Einfach nur "experimentieren" erscheint mir doch ein bisschen zu unpräzise und eher wie eine kindliche Vorstellung der täglichen Arbeit eines Chemikers. Andererseits weiß ich bis heute tatsächlich nicht, wie ein möglicher Tages-Arbeitsablauf von Chemikern in bestimmten Branchen aussieht. Ich kann mir darunter nicht viel vorstellen.

Alexandra könnte natürlich berufliche Werkstoff-Testerin oder so etwas werden. Das gibt ihr die Möglichkeit, "berufliche Gründe" zur Rechtfertigung von Kanonenschüssen auf fremde Stahllegierungen anzubringen, hat aber ansonsten wenig Witz und ist eher langweilig und zu simpel gedacht. 

Vielleicht fällt uns noch etwas ein. Alexandras Beruf taucht vielleicht bereits ein paar Mal auf, aber die wenigen Erwähnungen beruflicher Tätigkeit, falls es denn welche gibt, lassen sich sehr leicht nach dem Motto "Lesen als häufig ausgeübtes Hobby" umschreiben.

**Comment by ToBeFree** [comment]
Es passt nicht mehr in die IA1, glaube ich, aber in den IA2 könnte Alexandra zusammen mit Äöüzz-Wissenschaftlern auf Örz an neuen Raumschiff-Materialien forschen. Dazu gehören dann vielleicht auch, was ihr besonders Spaß macht, Tests der neuen Panzerungen gegen verschiedenste Formen von Gewalt. Explosionen, kinetische Geschosse, Laser... Ganz nach Alexandras Geschmack. Sogar mit Sprengstoff darf sie dort arbeiten, und bei einem großen Militärzulieferer entwickelt sie tatsächlich einen neuen Sprengstoff auf Basis des "Nitro-TNB".

In den IA1 ist Alexandra pragmatisch: Während der Raumschiff-Reisen kann sie schlecht an diesen Projekten arbeiten und nutzt stattdessen ihre literarischen Fähigkeiten, um als Lektorin (gerade von mir neu eingebaut für #500 !) Geld zu verdienen.

Ich verschiebe das in die IA2-Ideenliste.

**Comment by ToBeFree** [comment]
https://www.freiwuppertal.de/ia-autoren/mw/index.php?title=Diskussion:IA2#Die_Jobs_der_vier_auf_.C3.96rz
