### ISSUE TITLE
Englisch in Äöüzz-Technik? (S. 192, 202)

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#447]
Warum sollten Äöüzz-Gerätschaften eigentlich englischsprachige Logs anlegen? (S. 192, S. 202)

**Comment by ToBeFree** [comment]
Oh. Ähm.

Wenn wir folgende Ersetzung anwenden, wird es wahrscheinlich logischer:

English --> Örzlängü
O --> Ö
o --> ö
A --> Ä
a --> ä
U --> Ü
u --> ü

**Comment by yur-y** [comment]
Nr. 1:

bgin mörgnözy tränsmissiön
gäläct cöördinätes: 5528.5804 ly; 351.274398° 0.5427996°
T-13 infrared mörgnözy;
>>>> forcing äütömätic eväsiv mänövär
T-12 ignöring mänüäl cöntröl ättmpt
T-05 high-mäss impäct impäct
T-04 high-mäss impäct impäct impäct impäct;
>>>> pöwär plänt öütpüt crjticül
T-03 high-mäss 22 impäct
T-02 pöwär plänt hüdrögen füsiön öt öf cöntröl;
>>>> shüld mörgnözy shütdöwn
T-01 crjticül impäct impäct impäct;
>>>>  hüll breäch ditäctöd
end öf tränsmissiön

**Comment by yur-y** [comment]
Und bei Nr. 2 ist das Problem, dass außerdem irdische Himmelsrichtungen und metrische Einheiten verwendet werden.

**Comment by ToBeFree** [comment]
"crjticül", ich liebe dieses Wort 😄 

Ich hatte bei meiner Überarbeitung eigentlich versucht, Örzlängü ein bisschen zu standardisieren, lesbarer zu machen und z.B. auf das Weglassen von Buchstaben zu verzichten. Andererseits sind Wörter wie "Crjticül" einfach zu schön, als dass man darauf verzichten könnte. Und "eväsiv" sieht toll aus.
"ditäctöd"... Ich lache beim Lesen. Lass uns das so behalten. xD

Irdische Himmelsrichtungen: Wenn man Osten als die Himmelsrichtung definiert, in die sich der Planet dreht, und wenn man Norden als die Richtung definiert, in die man gucken muss, damit diese Drehung "im Uhrzeigersinn" läuft, dann kann man auf jedem drehenden Planeten die Himmelsrichtungen festlegen. Anders als frühere Schifffahrer und Planetenbewohner ist man für diese Definition nicht auf Magnetfelder oder Sterne angewiesen; man kommt schließlich aus dem Weltall und hat die Drehung beobachtet.
Das sollten wir aber vielleicht klarstellen. Einer der Protagonisten (oder mehrere! Hatten wir so vielleicht noch gar nicht als Gesprächsstil!) könnte sich darüber wundern, dass die Himmelsrichtungen wie bei uns auf der Erde benannt sind. Der Bordcomputer, oder ein anderer Protagonist, könnte das dann erklären.

Metrische Einheiten: Wäre vielleicht sogar in Ordnung, als Übersetzungsergebnis. Andererseits ist die ganze Benutzeroberfläche ja jetzt doch auf Örzlängü eingestellt. Dann brauchen wir vielleicht doch so etwas wie Örz-Meter. Wird aber kompliziert, wenn sich dann der Leser etwas grobes darunter vorstellen soll. Die Entfernungsangabe ist ja nicht nur Gimmick, sondern dient auch dem Verständnis.

**Comment by yur-y** [comment]
Das ist lustig, weil ich beim Schreiben vor acht Jahren immer versucht hatte, Örzlängü (hieß das nicht früher "Özlängü"?) zu standardisieren. Und ich finde auch immer noch, dass das gleiche Wort nicht in verschiedenen Schreibweisen vorkommen sollte. Aber nur Englisch mit Umlauten wäre dann doch auch zu langweilig, finde ich.
"Crjticül" kam vom Namen des geretteten Raumschiffkapitäns. ;)

**Comment by ToBeFree** [comment]
Ah 🙂 Können wir gerne nachholen. Schaden kann es nicht. Mein Standard, einfach, damit die Korrektur dadurch nicht aufgehalten wird, und damit Lesbarkeit immer garantiert ist, war pures Englisch. Jemand, der kein Deutsch kann bzw. keine deutschsprachigen Umlaute kennt, wird vielleicht sogar ganz simpel darüber hinweg lesen. Diesen Standard habe ich, glaube ich, konsequent eingehalten bzw. nachträglich durchgesetzt. Es wird also relativ leicht, die momentan standardisierten Wörter in einen neuen Standard umzuwandeln.

Sowohl zur einheitlichen Schreibweise, als auch zum Argument "langweilig", stimme ich vollkommen zu, nachdem ich den genialen Text da oben gelesen habe. Den Örzlängü-Standard sollten wir unbedingt auch in den Bonusband packen.

"Crjticül": Im Namen hatte ich es absichtlich ein bisschen verschleiert. Ich habe es nie als kleingeschriebenes Adjektiv in einem Satz ausprobiert. Gefällt mir aber sehr gut. xD

**Comment by yur-y** [comment]
Was früher - wenn ich mich richtig erinner - auch oft enthalten war, war "c -> k", also "impäkt", "köördinätes", "krjtikül".

**Comment by ToBeFree** [comment]
https://www.freiwuppertal.de/ia-autoren/mw/index.php?title=%C3%96rzl%C3%A4ng%C3%BC

😄

**Comment by ToBeFree** [comment]
c und k gefallen mir gut^

Lass uns das hier als Diskussionsseite verwenden, in dieser Hinsicht ist MediaWiki ein bisschen antiquiert :)

**Comment by ToBeFree** [comment]
Sehr cool! :D

"wörst-käse" 😅

**Comment by yur-y** [comment]
LOL. Nach dem ersten Blick ins Freiwuppertal-Forum seit fast 6 Jahren muss ich feststellen, dass ich, ohne das explizit zu versuchen, die gleichen Regeln für "Özlängü" (so war nämlich doch mein ursprünglicher Name für die Sprache! Können aber gerne bei "Örzlängü" bleiben) wieder eingeführt habe, die ich damals schon versucht hatte durchzusetzen. Damals hieß es z. B. "wörst-käz". Oder auch der FÄZ-Artikel: :D


ÄÖÜRÜZÜ KÄPTÜRD BÄI DÜKTÄTÖR FLÖTIN ÄLÄND

Än Äöürüzü dät öfbräkd fröm Örz dö wääks ägö e dät häs bün föünd ön Örs jästärdä wüch wös ölsö räpörtd bäi FÄZ.NÄT wös käptürd bäi dä Örs düktätör Flötin Äländ. Äzä ässümd dät dä Äöürüzü äskäpd fröm ön Äöüzz fämüli tü täk köntröl öf ä späzsäp cölld "4-6692", whäl äzä ünnöwn höw dä Äöürüzü mänägd tü äviät dä späzsäp tü Örs. Dä 4-6692 äz ön lärg späzsäp dät äz ün prävät pröpertü e dät häs ä kwäntä kömpütär kön ä kömpütüpöwär grätär dän öl süperkömpütärs ön Örs. Dä Äöürüzü häd bün äbl tü üs dät kwäntä kömpütär för säväräl häkin äkziöns ön pöpülär Örsnet säts öl övär dä Örs.
Tüdä, äzä bäköm nöwn dät dä däktätör Flöting Äländ mänägd tü käptür dä Äöürüzü, ässümin dät äzä ön mütät Örskät kün trä äis. Pröbäbli dä düktätör äz göin tü änälüs dä Äöürüzü tü gät niöüw rüsörch risälts ön mütätd Örskäts bükös hä nöws äböüt dä äksistänz öf Örz, büt nävär söw än Äöürüzü. Dä Örz präsidänt ämphäsäzd tüdä dä äksträm impörtänz öf dä Örspüpl nöt gättin tü nöw änüting äböüt Örz ör Örzkültür.
