### ISSUE TITLE
Die Kapiteleinteilung...

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#448]
...ist super, bis auf Kapitel 16, welches _viel_ zu lang ist. Wie wäre es mit zwei weiteren Kapitelteilungen nach der Landung auf dem Planeten (S. 205) und nach "Stille." (S.220)? Wenn ja, was wären gute Titel?

**Comment by ToBeFree** [comment]
Nach der Landung auf dem Planeten: Ja, würde ich auch vorschlagen, und der nächste Titel könnte "Odyssee" oder "Rückflug" heißen. Beinahe hätte ich geschrieben: "Odyssee im Weltraum" -- aber das gäbe vielleicht markenrechtlichen Streit mit den Produzenten des gleichnamigen legendären Kinofilms. Vielleicht gibt es kreativere Vorschläge. :)

Wenn man nach "Stille" ebenfalls trennt, was ich vollkommen in Ordnung und gut finde, fällt für das vorhergehende Kapitel der Titel "Odyssee" eventuell weg, denn das ist dann nur noch eine "Tour durchs Weltall", eine "Sightseeing-Tour zwischen den Sternen", oder ähnliches. Klingt aber gar nicht schlecht, finde ich!

Wenn man nach "Stille" trennt, kommen für das damit beginnende Kapitel einige spannende oder dramatische Namen in Frage. Zu überlegen ist auch, ob der Titel dabei die Handlung vorweg nehmen darf. Nennt man das Kapitel zum Beispiel "Piraten", "Piratenüberfall", "Skrupellose Gangster" (würde ich für IA3 aufbewahren), "Freibeuter" oder ähnlich, dann ist Alexandras spätere Erklärung für den Leser auf einmal überflüssig. Sie muss natürlich trotzdem drin bleiben, damit die Handlung vollständig ist, aber sie ist auf einmal redundant. Dieses Problem gibt es aber ganz oft, und wir haben es bestimmt schon bei einigen Überschriften in Kauf genommen. Trotzdem kann man versuchen, durch einen weniger eindeutigen Titel die Spannung aufrecht zu erhalten.
Möglich zum Beispiel: "Der Wahnsinn hat Methode" (abgewandelt von Shakespeare, also nicht geschützt), "Neue Schwierigkeiten" (ein bisschen zu allgemein und nichtssagend, oder?), "Alles oder nichts" (passt nicht so wirklich, klingt eher doof), "Das Ultimatum" (hm.), "Unersättliche Gier", "Räuberische Trampeltiere", "Dreister Überfall" (gefällt mir trotz leichtem Vorwegnehmen der Handlung sehr gut!), "der derair" (auch nett!)

**Comment by yur-y** [comment]
Ich sehe den Fokus im mittleren Teil eher beim Geschehen auf dem Planeten als in der Sightseeing-Tour. Möglich wäre "Blärg" als Titel.

Für den ersten Teil könnte ich mir irgendwas von der Form "[Adjektiv] Mission" vorstellen, was nicht zu langweilig ist.

Und für den letzten Teil finde ich "der derair" tatsächlich ziemlich gut :D

**Comment by ToBeFree** [comment]
Ach, ich hab das falsch verstanden! 😄 

Ich hatte mich verlesen: nach dem Abflug vom Planeten. Aber bei der Landung passt natürlich deutlich besser:

-----

Alexandra tippte sich an die Stirn. »Das glaubst du doch selbst nicht. Aber wir müssen nachsehen, ob im Wrack noch Überlebende sind, und ob die Ausrüstung vollständig ist.«

Damit waren alle einverstanden. yury drückte einen Knopf und eine sanfte, automatische Landung wurde eingeleitet. Allmählich zog sich der Schatten unter ihnen zusammen. Das noch immer von starken Schutzschilden umgebene Schiff näherte sich vorsichtig dem Boden. Als die Schilde die Erde berührten, passten diese sich fließend an die Umgebung an und bildeten schließlich eine große Kuppel um die gelandeten Besucher von Örz.

Als die Triebwerke herunterfuhren und das Schiff auf Hydraulikstützen zum Stehen kam, erfüllte Stille das Raumschiff. Aus der Ferne waren leise friedliche Tiergeräusche zu hören; zwitschernde Vögel und vollkommene Windstille schienen allen Befürchtungen zu widersprechen.

∞∞∞

-----

Stille ist natürlich ein perfekter Kapitelübergang. Eine kleine Unendlichzeichen-Trennung gibt es ja sogar bereits an der richtigen Stelle.

Das Kapitel hat dann natürlich einen auf den Planeten bezogenen Namen. "Blärg" ist, falls uns nichts besseres einfällt, eigentlich nicht schlecht -- nimmt allerdings die Pointe beim Abflug möglicherweise vorweg. Der Leser weiß noch nicht, dass das der Planetenname ist; es könnte auch ein Wesen oder irgendein Ereignis auf dem Planeten sein. Trotzdem würde ich den Namen nach Möglichkeit vermeiden, nicht nur, weil er nicht spannend genug ist.

Irgendetwas mit "Mission" klingt toll. Darf man natürlich nur einmal im ganzen Roman als Kapitelüberschrift verwenden, aber das ist ja glücklicherweise gegeben. Zu Fort Knox und der Mona Lisa hätte es beispielsweise noch gepasst.

Leider fällt mir noch kein passendes Adjektiv ein; denkbar wäre eine "Bergungsmission", aber das ist zu langweilig oder verräterisch.

Man könnte auch eine Überschrift wie "Verbotenes Paradies" wählen. 🙂

**Comment by yur-y** [comment]
"Verbotenes Paradies" (für den ersten oder zweiten Teil?) finde ich ehrlich gesagt nicht so gut, weil der Planet zwar als landschaftlich schön, aber für mich nicht wirklich als paradiesisch beschrieben wird, und verboten passt auch nur so halb.
Also fehlen uns noch drei Kapitelüberschriften, auch wenn das derzeitige "Notruf im All" sich notfalls für den dritten Teil recyceln ließe. Was hältst Du von "der derair" für den dritten Teil?

**Comment by ToBeFree** [comment]
Das Einfachste zuerst: "der derair", sehr gerne. 😃 

Die Einwände zum "verlorenen Paradies" sind gut.

Ich begreife jetzt in diesem Moment erst, dass wir drei Überschriften brauchen. Es entstehen drei Kapitel, wo vorher nur eines stand. Okay. 

Meine Vorschläge:

* **"Notruf im All"**, Beginn wie gehabt (S. 185), weil da ja tatsächlich der Notruf eintrifft.
* "Scherben und geschmolzenes Metall", "Scherben und geschmolzenes Eisen", "Geschmolzenes Metall", beziehen sich jeweils, ohne dass der Leser es ahnt, auf das gesamte Kapitel, und nicht nur auf das Wrack. Ansonsten vielleicht "Überreste eines Traums" bzw. "Überreste eines Albtraums", wie Orakel bereits in Gedanken formuliert hat, oder "Endstation Bergsee"?
* **"der derair"**, nach "Stille." (S. 220)

**Comment by yur-y** [comment]
Ich dachte, der Notruf bezieht sich auf den Notruf der vier, als sie von den uggys überfallen werden. Der Notruf von dem verunglückten Schiff ist ja schließlich schon vor dem Kapitelbeginn passiert, wenn ich es richtig verstehe. Ich bin immer noch für irgendwas mit "Mission". "Interstellare Mission"? Oder "Urlaub in der Katzenpfote"/"Urlaub auf Cat's Paw"? Überzeugt mich irgendwie alles nur so halb.

Für die zweite Überschrift nehme ich jetzt erst mal "Geschmolzenes Metall", vielleicht fällt uns ja noch was besseres ein.

Und "der derair" ist gesetzt. :D

**Comment by ToBeFree** [comment]
Achso, oh, nein, das bezog sich von Anfang an gedanklich auf den Notruf der Möribünd Explörer! 😃 Und ja, theoretisch ist das richtig. Da der Notruf trotzdem erst in diesem Kapitel dem Leser und den anderen Protagonisten vorgestellt wird, und da er der Auslöser für die Sternenreise ist, halte ich das für eine gute Kapitelüberschrift... hm. Na, zumindest, solange uns nichts besseres einfällt. Der Titel wirkt ansprechend auf mich; die Gegenvorschläge überzeugen mich ebenfalls nur halb.^^

Nicht "Endstation Bergsee"? 😄 Irgendwas Besseres muss wohl doch noch her. Wir können ja einfach das Issue offen lassen, bis uns etwas einfällt.
