### ISSUE TITLE
Cover-Schriftart: "Infinite Adventures": Tangerine Bold zu geschwungen?

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#449]
Von #305, von yury:

"Noch mal generell zum Titelbild: Ich habe mir die Titelseite ehrlich gesagt gerade erst noch mal angeschaut, sie ist in dem PDF ja nicht enthalten. Ich finde das Bild echt gut, aber ich finde, dass die geschwungene Schriftart nicht so ganz zum Roman passt. Was meinst Du/welche Gründe hattest Du für die Auswahl?"

**Comment by ToBeFree** [comment]
Ursprüngliche Motivation war für mich, eine Schriftart zu finden, die folgende Anforderungen erfüllt:

* **frei lizenziert**, kann problemlos im Repository mitgeliefert und im Dokument vollständig eingebunden werden. Gute Sammlung: https://fonts.google.com -- alle anderen Sammlungen taugen wahrscheinlich leider recht wenig, denn "free to download"-Schriften aus dem Netz sind oft raubkopiert und erst recht nicht frei lizenziert.
* **optisch ansprechend**, keine 0815-Schrift.
* **passend zum Coverbild** und vielleicht zum generellen "Abenteuer"-Thema.

Dafür erscheint mir Tangerine Bold eigentlich recht gut -- andererseits ist weder das Coverbild, noch die Schriftart, unbedingt repräsentativ für den gesamten Roman. Nur: Wie sehen die Alternativen aus? Zumindest das aktuelle Buchcover inklusive Schriftarten finde ich persönlich sehr ansprechend.

"Passend zum Roman" ist ein generell guter Kritikpunkt. Theoretisch müsste man das Cover ersetzen, aber das möchte ich auf keinen Fall. Das Cover war ein wunderschöner Glücksfund, noch dazu Public Domain und im richtigen Bildformat, hoch aufgelöst. Die Schriftart wurde nachträglich passend dazu gewählt. Im ursprünglichen Entwurf hatte ich eine unfreie Schriftart verwendet, die nach Tintenschrift aussah. Wahrscheinlich erinnerst du dich noch an die Entwurfsliste, die damals per E-Mail an euch ging. Tangerine Bold war die ähnlichste Schriftart, die ich frei finden konnte.

Ich bin für neue Vorschläge offen und baue diese gerne testweise mal mit GIMP ein, um einen Vergleich zu bieten. Die xcf-Dateien befinden sich außerdem im Repository, sodass du selbst gerne jederzeit experimentieren kannst. Nur der Textschatten ist dann nicht passend; den müsste man für Experimente durch ein schwarzes Rechteck ersetzen. Sehr schön fand ich auch die Vorschaufunktion bei Google Fonts, und der Knopf "Apply to all fonts", der nach dem Eintippen des Beispieltexts viele Vergleiche bietet.

**Comment by ToBeFree** [comment]
Ich mag die Schrift immer noch. :) Issue schließen?

**Comment by yur-y** [comment]
Jap. :)
