### ISSUE TITLE
Zeilenumbruch

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#450]
Vor Gedankenstrichen sollte kein Zeilenumbruch stehen. Lässt sich das irgendwie realisieren? Evtl. indem man jeden Gedankenstrich durch [geschütztes Leerzeichen][Gedankenstrich] ersetzt?

**Comment by ToBeFree** [comment]
Oh, das ist ein interessanter Aspekt. Es wundert mich, dass LaTeX sich nicht darum kümmert. Dein Workaround klingt interessant; das geschützte Leerzeichen ist in LaTeX eine Tilde ("~"). Ich habe allerdings schlechte Erfahrungen mit diesem Zeichen gemacht. Mein damaliger Kommentar, aus "Useful Copypasta":

Tilde. Standardbedeutung: geschütztes Leerzeichen. Für ASCII-Art notwendig.
Hinweis: Geschützte Leerzeichen verhindern nicht die Trennung des restlichen Wortes.
Ein geschütztes Leerzeichen hat daher das Potenzial, die Trennung deutlich hässlicher als vorher zu machen.


Weil sich die Umbrüche während jeder Überarbeitung ändern, kann man hier nicht für jeden Einzelfall eine eigene Lösung finden. Wenn wir uns für eine Lösung entscheiden, muss sie überall im Dokument, immer, funktionieren. Ich befürchte, dass das auf "wir lassen es unverändert" hinausläuft. Theoretisch handelt es sich hier um einen Stilfehler, den LaTeX vielleicht selbst eines Tages durch ein Software-Update beheben sollte. Wir können nur einen Workaround basteln, oder es eben aus Prinzip lieber sein lassen. Der Quelltext sähe mit solchen Konstrukten ja auch merkwürdig aus.

**Comment by yur-y** [comment]
Was meinst Du mit "Trennung deutlich hässlicher machen"? Was wäre das Problem damit, "–" durch "~–" zu ersetzen? Was passieren könnte, ist dass dann höchstens ein Wort zusätzlich getrennt wird, nämlich das vor dem Gedankenstrich. Z. B. S. 17:

>Trotzdem konnten Free, Orakel und yury mit knapper Not entkom
-men – zumindest dachten sie das<

statt

>Trotzdem konnten Free, Orakel und yury mit knapper Not entkommen
– zumindest dachten sie das<

Ist das schlimm?

Wikipedia ist nicht ganz eindeutig:

>Ein Zeilenumbruch kann sowohl vor als auch nach einem Gedankenstrich erfolgen.
Ein einzelner Gedankenstrich sowie der abschließende eines Gedankenstrichpaares stehen aus Gründen der Lesbarkeit normalerweise nicht am Zeilenanfang.[6] Häufig wird verallgemeinert und vereinfacht, dass grundsätzlich keine Gedankenstriche am Zeilenanfang stehen sollten.[7][6][8][9][10] Daneben gibt es die Empfehlung, paarige Gedankenstriche nicht vom Einschub zu trennen.[11]<

Aus der Zeitung kenne ich es so, dass Gedankenstriche immer am Ende und niemals am Anfang stehen.

**Comment by yur-y** [comment]
Überall ersetzt. Bei stichprobenartiger Kontrolle habe ich nichts gesehen, was kaputtging, aber einige Stellen, wo es geholfen hat.
