### ISSUE TITLE
Wo kommt der Schutzschildgenerator her? (S. 210)

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#451]
»Das Gleiche könnte ich dich fragen«, gab Orakel zurück. »Wir befreien wir jetzt die anderen?«
»Mit dem Schutzschildgenerator«, schlug Alexandra vor.

**Comment by ToBeFree** [comment]
Den hat Alexandra mitgenommen, aber ich sehe gerade, dass ich das nirgendwo so beschrieben habe. Der komische Metallkasten in Alexandras Hand ist der Generator. Hier die aktuell nichtssagende Szene, die ich falsch im Kopf hatte:

> Mit einem merkwürdig aussehenden Metallkasten in der linken Hand sprang Alexandra aus der Bodenschleuse, ohne das Einschalten des Antigrav-Aufzugs abzuwarten. In der anderen Hand hielt sie eine kleine futuristische Betäubungspistole, die sie nach allgemeinem Protest statt des Flammenwerfers mitgenommen hatte. Anschließend folgten yury und Free, und zuletzt verließ Orakel mit einem vollkommen überdimensionalen Wanderrucksack, einem Schweißbrenner und einem Handtuch das Raumschiff.

Dass es sich bei dem Metallkasten um den Generator handelt, könnte man dem Leser ja durchaus erst im Gefängnis verraten. Das wäre ein schöner Schreibstil, finde ich.

Andererseits: Orakel hat einen Schweißbrenner dabei? Warum verwendet er den dann nicht? Warum darf Alexandra den Generator behalten? Also, irgendetwas ist da noch ziemlich unlogisch.

Der Schweißbrenner wird genutzt, um das Wrack zu öffnen. Ohne den geht es also nicht voran.

Im Gefängnis jedoch kommt er nie zum Einsatz -- nicht einmal bei der Befreiungsaktion. Dort verwendet Alexandra eine elektrische Metallsäge. Anmerkung: Der Strom kommt aus einem Akku, vielleicht mit Wasserstoff, vielleicht noch mit Plutonium. Ob man das nochmal klarstellen sollte? Ich glaube, man kann darauf verzichten. Es ist mit der Äöüzz-Technologie durchaus erklärbar.

Mögliche Erklärung für das Fehlen des Brenners im Gefängnis wäre, dass die Spinnenwesen den Schweißbrenner stehlen. Er ist auch, vor allem wenn die Wesen ihn in Aktion gesehen haben, deutlich leichter als Waffe oder Gefahrenquelle zu erkennen. Wenn die Spinnenwesen gesehen haben, wie Orakel damit das Wrack aufschweißt, dann nehmen sie ihm dieses Wunderding natürlich ab.

Folglich steht der Brenner auch bei der Befreiung nicht mehr zur Verfügung. Eigentlich ganz praktisch.

Es stellt sich nur noch die Frage, wie denn der Schutzschildgenerator im Gefängnis in Alexandras Hände kommt.

Man könnte einen kurzen Einschub, vielleicht sogar eine längere Szene, schreiben: Alexandra (blind) oder Orakel (mit Nachtsichtgerät!) stößt auf das Lager der Spinnenwesen. Unbewacht, vielleicht schlecht oder gar nicht gesichert, stehen in einer Höhlennische die ganzen technischen Dinge herum. Das erklärt aber noch nicht, wieso der Brenner fehlt.

Vielleicht stößt Orakel zufällig auf den Metallkasten. Der Rest der Geräte ist nirgends zu finden, aber der Metallkasten liegt so blöd am Boden herum, dass Orakel darüber stolpert. Er weiß zwar nicht, worum es sich dabei handelt, nimmt ihn aber mit, weil er ihn zuvor als Teil von Alexandras Ausrüstung gesehen hatte. Alexandra ist begeistert, als sie den Kasten sieht, und erklärt, was man damit machen kann.
