### ISSUE TITLE
S. 220: "Stille."

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#453]
Das Wort soll die Dramatik erhöhen; ich bin mir aber nicht sicher, ob es nicht sogar effektvoller wäre, das Kapitel/den Abschnitt mit dem Satz vorher zu beenden. Meinung?

**Comment by ToBeFree** [comment]
Ich kann den Einwand verstehen, würde das Wort aber drin lassen, trotz Kapiteltrennung. Dazu muss ich sagen, dass ich noch nicht beides ausprobiert und vor meinen Augen gesehen habe; falls du das hast, wirkt mein Kommentar vielleicht unqualifiziert. Ich kann es ab nächstem Wochenende ausprobieren, denn dann habe ich bis zum 1. September den ganzen Tag Zeit für die IA.

Der Roman hat eine extrem hohe Erzählgeschwindigkeit, auch im zweiten Teil noch. Die ganze Blärg-Szene hat nur wenige Seiten, dabei ist das gefühlsmäßig vielleicht eine der längsten zusammenhängenden Erzählungen des Romans.

Das Wort "Stille." an dieser Stelle verhindert hoffentlich, dass der Leser sofort umblättert. Diesen Effekt hat es zumindest auf mich. Wenn in einem Roman eine längere Denkpause beschrieben wird, halte ich beim Lesen tatsächlich inne. Die Handlung in meinem Kopf funktioniert gar nicht anders. Da muss dann auch kurz gedanklich eine echte Pause sein, sonst ist die Atmosphäre beschädigt. 😄
Der Umkehrschluss aus dieser Lesegewohnheit wäre für mich persönlich, das Wort "Stille" dort zu lassen.

Ein Gedankenexperiment: Auf das Kapitel folgt keine Fortsetzung, sondern ein neuer Handlungsstrang. Erst später kehrt die Erziehung zu den Freunden zurück.
Das nun in einen Kinofilm umgesetzt:
Mit "Stille": Die Stille ist Teil der Szene. Der Schnitt folgt nach fassungslosem, dramatischen Schweigen.
Ohne "Stille": Der Schnitt erfolgt sofort; der Kinobesucher erfährt nicht, ob dort Stille war, oder ob der Schnitt schnell erfolgen musste, weil kurz darauf direkt noch etwas passiert wäre.

Falls das alles immer noch nicht überzeugt, wird das Wort "Stille" sofort entfernt. 😄

**Comment by yur-y** [comment]
Überzeugt, dann bleibt es. Ich war mir wie gesagt nur nicht sicher. War das mit dem neuen Handlungsstrang als Vorschlag gemeint? Dann müssten wir aber tatsächlich was Neues schreiben.

**Comment by ToBeFree** [comment]
Nein, das war nur ein Gedankenexperiment :D
