### ISSUE TITLE
Spitzfindigkeit: "der Inhalt der bestimmt dreißig Kilogramm schweren Kiste wurde auf die Körbe verteilt" -->"der bestimmt dreißig Kilogramm schwere Kisteninhalt wurde auf die Körbe verteilt"?

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#454]
Die Kiste wiegt ja nur zusammen mit ihrem Inhalt 30 kg. Es wäre erstaunlich, wenn die Kiste selbst 30 kg wiegt.

**Comment by yur-y** [comment]
Ich finde zwar, dass die andere Formulierung auch geht, aber OK ✔

**Comment by ToBeFree** [comment]
Ich auch -- ich stutzte dann allerdings beim kritischen erneuten Lesen. Ich weiß nicht, ob mir das in einem "normalen" Roman irgendwie merkwürdig aufgefallen wäre.^^

**Comment by yur-y** [comment]
Hey, wieso darf man noch nach dem Schließen kommentieren? :D

**Comment by ToBeFree** [comment]
Haha 😋

**Comment by ToBeFree** [comment]
Wahrscheinlich kannst du das sogar *jetzt* noch. :)
