### ISSUE TITLE
Zeit- und Ortsangaben

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#456]
Ich glaube, wir haben das schon mal irgendwo diskutiert, aber ich finde es gerade nicht.
Derzeit sind Zeit- und Ortsangaben häufig in der Form

- "(Auf dem uggy-Kommandoraumschiff)"
- "(Büro von Floating Island, Washington, D.C.)"
- "(5 Minuten später)"

Ich finde das unschön. Für die Ortsangaben wäre eine Möglichkeit, sie fett zu drucken oder eine andere Schriftart zu wählen. Die Klammern würde ich dabei lieber weglassen. Die Zeitangaben sollten möglichst umgeschrieben werden. Wenn das nicht gut passt, wie hier...

> »wir sind bald da. hast du die thermodings bereitgemacht?«
»oh, mist.«
(5 Minuten später)
»so, bereit. wann sind wir da?« <

..., dann weiß ich auch nicht, wie es besser aussähe.

**Comment by ToBeFree** [comment]
Da bin ich mir gar nicht so sicher :) Es gibt in der internen Diskussion einen Thread dazu, aber da steht anscheinend nichts von diesem speziellen Problem.

Ja, das sollten wir ändern. Was hältst du von Zentrierung, wie bereits bei den Unendlichzeichen genutzt? Ich hatte Kursivdruck statt Fettdruck überlegt, aber da Kursivdruck auch anderweitig genutzt wird und eine Bordcomputer-Stimme sein könnte, bin ich für Fettdruck. Zumal ich -- das hatte ich jetzt aber wirklich schonmal geschrieben :D -- den Fettdruck bei Linux Libertine auf dem Papier sehr schön finde.

Klammern weglassen: jup

Zeitangaben durch Fließtext ersetzen, meinst du? Ich finde, das klingt gut. In Ausnahmefällen wie dem uggy-Gespräch könnte man die Ortsangaben-Formatierung nutzen.

**Comment by yur-y** [comment]
Ich überlege gerade, die Ortsangaben vielleicht sogar ganz wegzulassen. Dann muss man in einigen Fällen eine andere Erklärung hinzufügen, aber fast immer wird es aus dem Kontext klar und ich finde, so wirkt es besser. Das Problem ist, wenn man einmal damit anfängt, diese Ortsangaben über die Abschnitte zu schreiben, ist es schwer zu rechtfertigen, wo man damit aufhört.

**Comment by yur-y** [comment]
An einer Stelle habe ich bisher leider keine Lösung für die Zeitangabe gefunden:

»wir sind bald da. hast du die thermodings bereitgemacht?«
»oh, mist.«
(Fünf Minuten später)
»so, bereit. wann sind wir da?«
»wir haben leichte verspaetung. noch 15 minuten.«
»alles klar. das gibt aerger vom chef…«
»mir egal. sei du bloss leise. du hast komplett vergessen, das thermo-
dings einzu…«
»hyperthermogenerationszuender, wenn ich bitt en darf. du verstoesst
gegen § 9234848 der…«
»klappe jetzt! an die arbeit! wir sind in 15 minuten da!«
»ups, der chef. nix wie weg.«

Fließtext würde die Wirkung der Stelle hier kaputtmachen. Ideen?

**Comment by yur-y** [comment]
Danke!

...oh, mal so nebenbei: Die uggys benutzen eigentlich keine Minuten als Zeitmaßstab.

**Comment by ToBeFree** [comment]
Oh, Mist. 😄 

Naja, es handelt sich immerhin um eine Übersetzung. Da ist das mit irdischen Minutenzahlen wahrscheinlich noch akzeptabel. Auch auf Örz werden ja einige Dinge (mit teilweise äußerst krumm aussehenden Ergebnissen) von den Übersetzungsgeräten bzw. dem Romanerzähler umgerechnet.

**Comment by ToBeFree** [comment]
Ich finde, die uggys sollten DIN-Normen zitieren 😆

**Comment by ToBeFree** [comment]
Bereits erledigt, danke. 😃
