### ISSUE TITLE
Zeileneinrückung vor Absätzen

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#457]
Grundsätzlich gut, bei sehr langen Dialogen mit größtenteils einzeiligen Beiträgen sieht es aber für mich komisch aus. Wahrscheinlich gibt es keine Lösung?

**Comment by ToBeFree** [comment]
\noindent

😃

Wäre allerdings irgendwie inkonsistent.

**Comment by yur-y** [comment]
Ja, schon. OK, auch egal.^^
