### ISSUE TITLE
Wofür kommt Island eigentlich ins Gefängnis? (S. 240)

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#458]
Er hat nur Orakel eine E-Mail geschrieben. Er wird von Wolfgang erpresst (was in der E-Mail steht), der aber selbst nicht im Gefängnis landet. Gut, Orakel wird international gesucht, und Island bittet darum, potentiell aus dem Gefängnis befreit zu werden, aber in den USA sollte das nicht dazu reichen, um "kurze Zeit später" (um genau zu sein: wenige Stunden!) im Gefängnis zu sein.
Er kommt in die D.C. Central Detention Facility, das ist ein "jail", kein "prison", also ein von der Stadt operiertes Gefängnis für Untersuchungshaft oder kleinere Delikte. Untersuchungshaft könnte natürlich sein. Andererseits könnte man denken, wenn das FBI einen seiner Top-Agenten ins Gefängnis stecken will, dann nicht zusammen mit Kleinkriminellen in ein läppisches lokales Kleingefängnis. In D.C. gibt es aber kein federal prison... Vielleicht ist es aber auch egal, weil es eh niemand merkt.^^

**Comment by ToBeFree** [comment]
Die Unterscheidung zwischen "jail" und "prison" war mir früher nicht so klar, und bis gerade hätte ich die beiden Begriffe auch nicht eindeutig zuordnen können. Ich hatte allerdings bei der Wahl dieses Gefängnisses tatsächlich darauf geachtet (oder zumindest positiv überrascht bemerkt), dass man da "wenige Stunden später" in U-Haft sitzen kann. Bei einem richtigen "prison" ist das wohl nicht der Fall.

Und ja, es sollte wohl in D.C. stehen. Das war sicherlich einer der Beweggründe für dieses Gebäude. Zudem hat es tatsächlich einen aus Google Maps sichtbaren Innenhof, in dem die Freunde landen können. :D 

Zur eigentlichen Frage: Was hat Island getan? Gute Frage. Als Kinder dachten wir noch, der heimliche Kontakt des Gesetzeshüters mit dem international gesuchten Verbrecher reiche für eine Gefängnisstrafe aus. Das ist wohl eher nicht der Fall, zumindest nicht so drastisch wie in den IA dargestellt.

Vielleicht müssen wir uns einen besseren, zusätzlichen Erpressungsgrund ausdenken? Vielleicht hat Island mit dem Geld irgendetwas Illegales getan? Das Erbe betrug wohl mindestens eine Million Dollar, sonst würde Wolfgang kaum diese Summe fordern. Mit einer Million Dollar kann man wahrscheinlich tatsächlich einige Dinge veranlassen, die bei Enttarnung zu einer Gefängnisstrafe führen. Vielleicht hat Island heimlich die vier Freunde unterstützt? Die Goldhändler bestochen? Das wäre vielleicht ein lustiger Plot Twist und eine Lösung für das Problem, warum die Goldhändler so naiv sind.

**Comment by ToBeFree** [comment]
Das ist eigentlich bereits ganz nett gelöst:

"Die E-Mails an Orakel waren noch das geringste Problem, aber der Rest seiner E-Mail-Kommunikation durfte auf keinen Fall in die Hände seiner Vorgesetzten kommen."

Würde ich schließen. Mein Vorschlag im vorherigen Kommentar wäre merkwürdig: Erst heimliche Unterstützung, dann erbitterter Gegner im Rest des Romans?
