### ISSUE TITLE
"...grafie"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#460]
Der Duden will es auch so, ich bin aber sehr für die "...graphie", wenn das OK ist.

**Comment by ToBeFree** [comment]
Oh 🙂 

Also von mir aus gerne!

**Comment by ToBeFree** [comment]
Es wäre höchstens zur "Standardisierung" eventuell ein Argument, stets die Duden-Empfehlung zu wählen. Bei meiner Überarbeitung habe ich das, glaube ich, aus diesem Grund so oft wie möglich getan.

Es gibt aber keinen Grund dazu, sich nicht absichtlich für bestimmte Sprachformen zu entscheiden. Wir sollten solche Änderungen vielleicht irgendwo festhalten, damit das konsistent bleibt. Noch ein Standard-Dokument, wie bereits für Örzlängü, im Wiki?

**Comment by yur-y** [comment]
Habe bis jetzt auch immer die Duden-Empfehlung genommen, obwohl es sich bei "zu Hause" schon gesträubt habe. Bei "grafie" hört es aber auf! :D
Wenn Du ein Dokument anlegst, schreibe es rein; ich weiß aber nicht, wie viele Fälle noch vorkommen werden.

**Comment by ToBeFree** [comment]
💚
