### ISSUE TITLE
Was ist die Motivation der vier, auf die Erde zurückzukehren, Island zu befreien und Chaos anzurichten?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#462]
Auch hier habe ich das Gefühl, wir haben das schon mal diskutiert, aber ich finde es nicht.^^
Warum wollen die vier auf die Erde zurück und Island befreien, und, noch viel schlimmer, warum sind sie (besonders yury) so unglaublich naiv, die Technik der Äöüzz nicht nur aller Welt zu zeigen, sondern auch noch Island in die Hand zu geben? Sie wissen zumindest, dass den Äöüzz die Kontaktaufnahme zu den Menschen verboten ist; sie haben verstanden, warum es unmoralisch ist, Äöüzz-Technologie zu verbreiten (siehe Blärg; wobei es möglich ist, dass sie nicht wissen, dass es illegal ist) - und sooo dumm sind sie im Rest des Buches ja auch nicht. Später sagt Free, dass sie "Floating Island in seiner Not kurzerhand ohne Erlaubnis einige Äöüzz-Geräte geschenkt" haben, was andeutet, dass es eine spontane Entscheidung war, aber sie hätten ja zumindest vorher darüber nachdenken müssen.

**Comment by ToBeFree** [comment]
Kurze Anmerkung: Frees von dir zitierter Satz kam erst in meiner Überarbeitung dazu, da stand vorher irgendeine schlechtere Begründung...

Hier die Originalszene!

**Comment by ToBeFree** [comment]
Kapitel 9: Gut != gut gemeint

Alexandra wurde als nächstes wach, kurz danach wachte auch yury auf. Nach dem Frühstück machten sie sich auf die Suche nach Orakel und Free.
Auf dem Weg zum Raumhafen, wo sie Orakel und Free vermuteten, trafen sie einen Bekannten, der anscheinend sehr in Eile war und grußlos an ihnen vorbei ging. Ansonsten waren die Strätöi menschenleer. »Warum ist hier denn keiner?«, wunderte sich Alexandra. »Keine Ahnung, vielleicht ist irgendein besonderes Ereignis, von dem wir nichts mitbekommen haben?«, riet yury.
Wenig später sahen sie ein Pülizijä-Individumobil, welches direkt vor ihnen anhielt. Zwei Mitarbeiter der Pülizijä (sogenannte Pülizijäöi) sprangen aus dem Wagen und zielten mit merkwürdig aussehenden Geräten, die für Alexandra wie Waffen aussahen, auf die beiden und forderten sie auf Özlängü auf, die Hände zu heben und einzusteigen. »Sie sind verhaftet!«
Orakel hatte allerdings wenig Lust darauf, einzusteigen. Er holte in aller Ruhe einen Hamburger aus irgendeiner seiner Taschen hervor und begann, ihn langsam aufzuessen. yury, Alexandra und Free befanden sich bereits im Wagen, als Orakel unsanft herein geschubst wurde. »Hey, ich wollte doch nur noch etwas essen!« Dann wurde die Tür zugeschlagen und das Individumobil fuhr los. Die vier diskutierten darüber, was sie falsch gemacht haben könnten. Der Fahrer schien mit zu hören, denn kurz darauf sprang irgendwo eine Art Drucker an und yury hielt danach eine Touchfolie in der Hand. Es las sie den anderen vor:

Örz-Ixpörtärüläz
(Örslängütränzlätiziön bäy Äzähüglü Örzgü)

Es ist illegal, Äöüzz-Technologie, die mehr als nur dem Schutz einer einzelnen Person dient, auf Nicht-Äöüzz-Planeten zu exportieren.

Sinn des Gesetzes ist es, einen schweren Eingriff in die Forschung auf dem Planeten zu verhindern. Die Bevölkerung soll notwendige Technologien selbst erforschen und so gut wie keine Hilfe durch die Äöüzz bekommen.

Ausnahmen:
•	Der Planet ist von einer Selbstzerstörungskatastrophe bedroht (z.B. drohender Atomkrieg).
•	Die exportierten Geräte können bei Bedarf per Fernsteuerung von Örz aus aufgelöst werden.
•	Die Bewohner des Planeten werden durch ein fremdes, raumfahrendes Volk von der Vernichtung bedroht.

In jedem der drei Fälle muss zusätzlich eine Genehmigung der Äöüzz-Regierung vorliegen.

»Hä, und wo ist das Problem?«, fragte Orakel verwundert. »Ganz einfach, wir haben Floating Island einen großen Schutzschildgenerator gegeben, der dazu in der Lage ist, mehr als nur ihn selbst abzuschirmen. Und jetzt haben wir ein Problem. Da steht nämlich nicht die Strafe drauf…«, erklärte Alexandra. Dann hielt das Individumobil an und die vier mussten aussteigen.

Nach langen Erklärungen und Ausreden stand das Urteil fest: Die Strafe für die vier betrug 30 Millionen Äzz, wobei das noch recht wenig dafür war, dass sie in den Forschungsprozess einer ganzen Planetenbevölkerung eingegriffen hatten.
Als alternative Strafe durften (bzw. mussten, denn 30 Millionen Äzz konnten sie unmöglich zahlen) sie die illegal exportierte Technologie auf der Erde vernichten und dann »nur noch« 1000 Äzz zahlen. Die 1000 Äzz würde yury mit den Erkundungsflügen mit seinem Raumschiff schon irgendwie zusammenbekommen.

Die vier machten sich auf dem Weg zu der 4-6692, um Floating Island den großen Schutzschildgenerator wieder abzunehmen. Als yury im Raumschiff ankam und den Supercomputer sah, mussten Orakel und Free ihn dazu überreden, ihn nicht wieder auszubauen. yury gab sich schließlich geschlagen und startete die Triebwerke. Orakel versuchte, Alexandra zu erklären, wie der Computer funktionierte, während Free weiterhin verzweifelt versuchte, darauf Linux zu installieren. Dann schaltete yury den Warp-Antrieb ein und nach einigen Örzklöks waren sie im Sonnensystem angekommen.
Kurz bevor sie die Umlaufbahn der Erde erreichten, sah Orakel ein Objekt auf dem Schirm. »Was ist das?« Free trat näher. »Verdammt, das sieht sehr nach uggy aus…« Wenige Sekunden später erreichte sie der Funkspruch:
»Ugguwu jdfu njuwu ghuddu!« Diesmal brauchte der Übersetzer nicht lange: »mein name ist der nju-210beta. ich bin raumschiffkommandant auf einem raumschiff der uggy-raumpolizei. bitte identifizieren sie sich oder sie werden vernichtet. dies ist die wiederholung 1 von 2. sie haben noch 10 sekunden zur identifikation.«
»Schalte den Warp-Antrieb so hoch, wie Du kannst!«, rief Alexandra. Orakel drehte auf und sie beschleunigten auf 23.42 öm/ök.
»mein name ist nju-210beta. ich bin raumschiffkommandant auf einem raumschiff der uggy-raumpolizei. bitte identifizieren sie sich oder sie werden vernichtet. dies ist die wiederholung 2 von 2. sie haben noch 5 sekunden zur identifikation.«
»Pass auf«, sagte yury. »Der Nävgätör sagt, wir befinden uns auf Kollisionskurs mit dem Objekt virgö.lökälgrüp.sönsüstem.örs.nätüräl_sätlüt_1!« Orakel fragte: »Was soll das denn sein?« »Der Mond«, meinte Free. »Sieht ganz so aus«, stimmte Alexandra zu. »Warte mal – Kollisionskurs?« »Ja«, bestätigte yury. »Dann ändere die Richtung! Schnell!«, drängte Alexandra. »Das versuche ich doch die ganze Zeit! Aber es geht nicht!« Free rollte mit den Augen. »Du bist so unfähig, Orakel…« »Dann mach es besser!«
»ihre identifikation ist seit 30 sekunden überfällig. wir werden nun die unmittelbare zerstörung einleiten.«
»Das sind doch leere Drohungen, die haben eh nichts davon, wenn sie uns zerstören«, meinte Alexandra. Orakel versuchte währenddessen verzweifelt, auf dem Mond notzulanden, weil es für eine Richtungsänderung schon zu spät war.

**Comment by ToBeFree** [comment]
Dass die Polizei kommt, war damals deine Idee -- ich weiß noch, wie du uns damit ins Schwitzen gebracht hast. 😛  Damit hatten also nicht einmal die Autoren gerechnet.

**Comment by yur-y** [comment]
Alles geschenkt, aber das löst das roman-immanente Problem nicht. ;)

**Comment by ToBeFree** [comment]
Ich behalte es im Kopf, denn das ist wirklich schwierig. Vielleicht geeignet für die gemeinsame Überarbeitung. :)

**Comment by ToBeFree** [comment]
Eine mögliche Erklärung: Die Protagonisten sind abenteuerlustig und haben (zumindest unbewusst) großen Spaß daran, die Äöüzz-Technologie auf der Erde einzusetzen. Dass Floating Island um Hilfe bittet, ist eine willkommene Einladung zu einem Abenteuer, und die Freunde reden sich ein, dabei etwas Gutes zu tun.

**Comment by ToBeFree** [comment]
Schließen ohne Bearbeitung?

**Comment by ToBeFree** [comment]
<h1 align="center"><big>❄️<br>Eingefroren: Testdruck läuft</big></h1>

<p align="center">Seit dem Testdruck bemerkte Fehler und Wünsche bitte im <a href="https://github.com/InfiniteAdventures/ia-trilogy/projects/4"><b>neuen Projekt</b></a> einfügen.</p>
