### ISSUE TITLE
Vor gemeinsamer Überarbeitung einmal das Repository säubern

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#464]
Das mache ich, die Notiz ist für mich -- hierbei sollen gelöschte Dateien endgültig aus der Versionsgeschichte entfernt werden. Anschließend ist es erforderlich, dass jeder seine Kopie löscht und eine neue Fork anlegt; ansonsten protestiert Git und weigert sich, neue Änderungen anzunehmen. Immerhin wurde ja die Versionsgeschichte manipuliert.

Vorher zu erledigende Aufräumarbeiten:
* Überflüssige Bilder entfernen.
* "universe map", "public-domain"- und "creative-commons"-Sammelordner in zweites Repository verschieben. Erst gegen Ende wieder die tatsächlich genutzten Grafiken ins Hauptrepository schieben.
* Log-Dateien, Aux-Dateien löschen. Diese sind beim Compilieren entstanden und dienten nur der Fehlersuche.
* Sämtliche Versionshistorie: Entpacken, Neues hinzufügen, Duplikate entfernen (Linux-Tool), Verpacken, Originale löschen.
* Verzeichnisse umstrukturieren, wenn nötig. Jetzt wäre der Zeitpunkt dazu, die Ordnerstruktur in eine klare, vernünftige Ordnung zu bringen.

**Comment by yur-y** [comment]
OK - Du sagst mir dann einfach zu gegebener Zeit, was ich machen soll.^^

**Comment by ToBeFree** [comment]
Gerne 😄

**Comment by ToBeFree** [comment]
Kompliziert wird es nicht, denke ich. Während der Aufräumarbeiten, oder gerne im Voraus, sind Vorschläge zur neuen Struktur oder zu grundsätzlichen Änderungen willkommen; das wird etwa einen Tag in Anspruch nehmen.
