### ISSUE TITLE
Inhaltsverzeichnis

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#465]
Ich fände es super, wenn der 2. Teil auf einer separaten Seite beginnen könnte, falls das irgendwie geht. Derzeit ist nur noch ein Unterkapitel des 2. Teils auf der ersten Seite des Inhaltsverzeichnis.

**Comment by ToBeFree** [comment]
Gefällt mir!

Und das geht tatsächlich. Hätte ich nicht gedacht. Und es hält dauerhaft. Als ich das gelesen habe, dachte ich zuerst, es wäre eine nicht-dauerhafte Aktion:

https://tex.stackexchange.com/questions/6489/split-the-table-of-contents-in-two-pages

Die Änderung kommt aber, jetzt verstehe ich endlich, ins Hauptdokument. An der .toc-Datei wird nicht herumgebastelt.

Diese Zeile

    \addtocontents{toc}{\protect\newpage}

muss einfach irgendwo vor dem zweiten "\part" eingefügt werden.

Glücklicherweise schrieb er "newpage"; warum das besser ist als "pagebreak", steht in Issue #405

**Comment by yur-y** [comment]
Danke! Das funktioniert, nachdem ich die verbliebenen \pagebreaks am Anfang des Dokuments durch \newpages ersetzt hatte. Übrigens sah die Formatierung der Erklärung, die - auch mit \pagebreak - auf zwei Seiten aufgespalten war, sehr komisch aus. Ich habe das mal geändert in:


\noindent \textbf{Teil 1:}

\noindent Die absurd-witzige Vorgeschichte. Drei verrückte Studenten unternehmen eine äußerst unkonventionelle Weltreise mit gestohlenen Zügen, Helikoptern und Flugzeugen.

\bigskip

\noindent \textbf{Teil 2:}

\noindent Die inzwischen international gesuchten Freunde setzen sich kurzerhand ins All ab. Science Fiction mit bunten Sternennebeln, Raumpiraten, Kanonengefechten und zwei größenwahnsinnigen Diktatoren.

\bigskip

\bigskip

\noindent Diese Geschichte ist in einem Forenspiel entstanden, bei dem man zu dieser Geschichte jeweils einen Abschnitt hinzufügen musste. Die für dieses Format ungewöhnlich hohe, zusammenhängende Qualität veranlasste uns dazu, die entstandene Geschichte als Buch zu veröffentlichen. Mehr Informationen gibt es auf der offiziellen IA-Website:

\noindent infiniteadventures.de

\bigskip

\noindent Vom 14. Februar 2010 an schrieben die Autoren, anfangs noch ohne yury, die folgende Geschichte. yurys Erscheinen im Text kennzeichnet die Stelle, an der er anfing, die Infinite Adventures zu dem zu machen, was sie heute sind.

\noindent \textbf{Die Handlung des Romans ist fiktiv, absurd und nicht zur Nachahmung geeignet.} Etwaige Ähnlichkeiten mit tatsächlichen Begebenheiten oder lebenden oder verstorbenen Personen wären rein zufällig. Der gesamte Inhalt des Buches wurde von den Autoren der Infinite Adventures frei erfunden.

    \newpage

**Comment by ToBeFree** [comment]
Oh ja, das ist eine schöne Lösung. Ich fand die Erklärungsformatierung ebenfalls merkwürdig. 🙂

**Comment by yur-y** [comment]
✔
