### ISSUE TITLE
"Nur noch" 1000 Äzz...

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#468]
...oder doch eher 10.000 oder 100.000? Sind ja immer noch Peanuts für die vier.
Ach ja, und es sollte natürlich auch keine Zehnerpotenz o. Ä. sein, aber da denke ich mir was aus, wenn die Größenordnung stimmt.

**Comment by ToBeFree** [comment]
Oh, Zehnerpotenz. Danke, das hab ich komplett übersehen, sogar beim Bugreport. 😄 

100.000 sind zumindest keinesfalls Peanuts, wenn die Freunde eben "nur" Millionäre sind und bereits ein Geschäfts-Hochhaus gekauft haben, nachdem sie die geplanten Mieter mit Geld abgespeist haben. Da hatte ich schon Bedenken, dass das Geld eigentlich nicht (oder nur knapp) ausreicht. Anschließend wurde das Gebäude abgerissen und eine spezialdesignte Traumvilla an dessen Stelle gebaut. Erklärung, allerdings: Die Äöüzz haben das Bauen und Abreißen perfektioniert. Das läuft selbst auf lebensfeindlichen Planeten wie Routine ab, und an Baumaterial und Robotern mangelt es nicht. Keine Bauarbeiter müssen bezahlt werden. Das Grundstück in bester Lage dürfte den größten Kostenanteil ausgemacht haben, das Hochhaus war im Vergleich dazu wahrscheinlich fast geschenkt.

Die Äöüzz-Währung funktioniert anders als die Erd-Währungen; Edelmetalle haben dort einen für uns absurd wirkenden Wert, da wir offenbar nur auf der Erde ungewöhnlich viel davon abbekommen haben. Lebensmittel sind im Wert ungefähr gleich; Technik sprengt alle Vergleiche. Von der Menge Gold, welches die Vereinigten Staaten oder China dafür hergeben würden, exklusiv an diese Technologien zu gelangen, könnte man ganze Erdkontinente kaufen. Kein Wunder, dass der Export für Äöüzz-Privatpersonen verboten ist. Warum die Imperiumsregierung jedoch die Situation nicht ausnutzt, obwohl sie aus profitorientierten Konzernen besteht, bleibt ein großes Rätsel, das wohl irgendetwas mit geschichtlicher Erfahrung oder tiefstem, geradezu religiösem Respekt zu tun haben muss.

Die Einnahmen durch einen äußerst glücklich gelaufenen Erkundungsflug nach drei lebensgefährlichen Situationen (Dunkelgefängnis, Papierflieger-Angriff, uggy-Überfall) lagen ungefähr in der 100.000er Größenordnung. Wenn die Freunde nicht ständig mehrere zufällig auch noch privat entführungsversicherte Personen retten, würde ich höchstens ein Drittel davon als "durchschnittliches Monatsgehalt" abschätzen.

Davon ausgehend: 10.000 wären wohl ein kurzes schmerzhaftes Lippen-Verziehen, mit dem Bewusstsein, dass man möglicherweise den nächsten schlechter bezahlten Auftrag "umsonst" durchführt. Mit einem blauen Auge davon gekommen, eine eher symbolische Strafe, die als deutliche Minderung gegenüber der ursprünglichen Strafe spürbar ist und ein Gefühl von "Okay, damit ist die Geschichte endlich erledigt" zurücklässt. Die hauptsächliche Strafe, auch wenn sie vielleicht nicht als solche empfunden wird, ist nicht das Geld, sondern der Island-Sturzauftrag auf der Erde.

100.000: Klingt nach einem deutlichen, schmerzhaftem Tritt in den Hintern, falls es erneut passiert.

1.000.000: Ab dieser Größenordnung ist die Grundlage für das Leben auf Örz in Gefahr. Man bedenke, welcher Aufwand und welches Risiko notwendig waren, um diese Summe auf der Erde zu "erarbeiten". 

Achso, und ja, 1000 sind Peanuts für die vier Freunde. Guter Punkt! Vielleicht Aktiendividenden eines halben Monats. Geschenkt ohne Arbeit.

**Comment by yur-y** [comment]
117.649 = 7^6. Ein deutlicher, schmerzhafter Tritt in den Hintern sollte es ja auch sein. #closeIfOK

**Comment by ToBeFree** [comment]
Gefällt mir, danke! :D
