### ISSUE TITLE
S. 249 oben: Einfügung oder nicht?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#469]
Ich hatte überlegt, auf S. 249 oben noch einen Satz von yury an das Äöüzz-Zitat anzufügen, bin mir aber nicht sicher, ob es die Wirkung zerstört. Ehrliche Meinung?

»So ganz unrecht habt ihr ja nicht. Aber bei uns regiert der Kapitalismus«, erklärte er stolz. »Wir brauchen keine inkompetenten Herrscher, die aus persönlichen Motiven Kriege anzetteln und in die Geschichte eingehen wollen. Stattdessen regieren bei uns immer die Unternehmen, die gerade den größten Teil zu unserer wirtschaftlichen Leistung beitragen.«

»Also im Prinzip so wie auf der Erde, nur ehrlicher«, murmelte yury.

∞∞∞

**Comment by ToBeFree** [comment]
lol

Das muss unbedingt rein. 😄 👍

**Comment by yur-y** [comment]
✔
