### ISSUE TITLE
"Das Internet auf ugghy bestand zu 30% aus Propagandaseiten" --> "Das Internet auf ugghy bestand zu 90% aus Propagandaseiten"?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#470]
-

**Comment by ToBeFree** [comment]
Wer hat denn damals die 30% verzapft? 😄 Natürlich 90.


-----

Anmerkung: Das war ich natürlich. Aber nicht ursprünglich:

> Der Planet, auf dem sie gelandet waren, wurde von den uggy "ugghy" genannt. yury gab zu dieser "genialen Namenswahl" natürlich sofort einen ironischen Kommentar ab. ugghy wurde von K. Irby Vogel regiert. Vogel hatte so viel Geld gehabt, dass er den Planeten, auf dem er lebte, einfach gekauft hatte. Laut uggy-Gesetz war das möglich und nun hatte Vogel die volle Macht über den gesamten Hauptplaneten der uggys. Nicht alle uggys waren damit zufrieden, aber sie konnten nichts gegen Vogel machen. Das Internet auf ugghy bestand zu 30% aus Seiten, die von Vogel nach und nach gesperrt wurden. Kurz nach seinem "Amtsantritt" hatte Vogel seinen besten Berater entlassen. Die vier nahmen sich vor, so schnell wie möglich von diesem Planeten zu fliehen. Als Orakel endlich seinen Muffin aufgegessen hatte, befanden sich die vier wieder in einer Art Gefängniszelle. Alexandra suchte in ihren Taschen und bemerkte, dass ihr das Al2-TNB abgenommen wurde. "Na super.", meinte sie enttäuscht.

Es handelt sich um einen nachträglichen Korrekturfehler von mir. Ursprünglich gemeint waren **Protestseiten gegen die Regierung**. Die ursprüngliche Formulierung ergibt aber keinen Sinn. Dein Vorschlag löst das verschlimmbesserte Problem nun tatsächlich.

**Comment by yur-y** [comment]
✔
