### ISSUE TITLE
Hinweis von Seite 1 "Dies ist eine offizielle Ausgabe der Infinite Adventures, ..." auch im Lizenz-Kapitel einfügen!

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#475]
Sicher ist sicher. :)

**Comment by yur-y** [comment]
Nach "Falls du die Rechte in dieser Lizenz nutzen möchtest, musst du sie vollständig gelesen und verstanden haben. Es genügt nicht, nur die »menschenlesbare Zusammenfassung« zu lesen. Aus diesem Grund bieten wir keine solche Zusammenfassung an." eingefügt. Richtig?

**Comment by ToBeFree** [comment]
Jein; das ist theoretisch nicht Teil der Lizenz, sondern eine explizite Erklärung eines Teils der Lizenz, der besonders wichtig ist, aber gerne übersehen wird. Ich werde mir da aber noch überlegen, wo und wie ich das besser formulieren kann. Das ist erstmal super, danke :D
