### ISSUE TITLE
Außerhalb der IA, im "archive"-Ordner: "Orakels Tagebuch:" Orakel hat einen Teil des Tagebuchs geschrieben

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#476]
Ich glaube, da steht, ich hätte "Orakels Tagebuch" geschrieben. Habe ich auch beinahe vollständig alleine. Der folgende Teil, sehe ich gerade, stammt aber von Orakel selbst:

Liebes Tagebuch, 
heute bin ich in New Jork (durchgestrichen) York. Diese Idioten in den Jets haben wir abgeschüttelt. Und wenn Sonic nochmals ein Flugzeug fliegt, steige ich NICHT ein. Der Kerl kann ja gar nichts. Kann der eigentlich bis drei zählen??? Da will der eine einfache 180° Kurve mit einer 757 fliegen und bringt uns alle in Lebensgefahr!!! Wenn ich nicht heldenhaft noch das Flugzeug gerättet (durchgestrichen) gerettet hätte, waren wir alle tot. Ich habe das Flugzeug im Meer gelandet und wir treiben auf eine Werft zu. Da war so ein MEGA Schiff so ganz teuer und so und wir sind dagegen gefahren!!! Dann ist das Schiff gesunken und der Kapitän war ziemlich sauer. Bestimmt auf Sonic. Hätte der nicht diese 180° Kurve geflogen, wäre das alles nicht passiert. 
Ja, mein leibes Tagebuch, warum bin ich jetzt in New YORK??? Sonic, yury und ich schwammen schnell zu einem Rettungsboot des untergehenden Schiffes und ruderten damit weg. Auf einmal kommt dieser Idiot mit einem Motorboot aus der Werft und schießt auf uns!!! Und der hat uns auch getroffen!!! Mitten ins Boot. BUM!!! Hat das geknallt. Aber ich nahm ein Ruder und schlägte (durchgestrichen) schlug den Kapitän in dem Motorboot, der uns übrigens einholte, k.o.
Dann fuhren wir mit dem Motorboot weiter in den nächsten Hafen und fuhren mit einem leeren Kreuzfahrtschiff!!! Aber irgendwie blieb das dann stehen. Dabei hab ich doch nur Waschmittel in eine überdimensionale Waschmaschine gefüllt. Naja, wir sind dann mit einem Rettungsboot weiter gefahren. Ich muss jetzt aufhören. Gleich hab ich ein Interview mit so einem komischen Herrn Zwieback. Der macht arme Leute wieder reich.

**Comment by ToBeFree** [comment]
https://www.freiwuppertal.de/forum/viewtopic.php?f=43&t=349

**Comment by yur-y** [comment]
"Information

You are not authorised to read this forum."

**Comment by ToBeFree** [comment]
Ups, das lag im Adminbereich. Wird verschoben. :)

**Comment by ToBeFree** [comment]
Ist jetzt im IA-Gruppenbereich; Link identisch. :)
