### ISSUE TITLE
Quelltext-Fehler: Dort steht "\^C". Gemeint ist: "\^{}C"

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#483]
Kaum zu sehen, aber natürlich soll da kein Zirkumflex über dem C erscheinen. Gemeint ist die übliche Kommandozeilen-Schreibweise für "Strg+C", also "^C".

**Comment by yur-y** [comment]
Haha, auch übersehen 😄 
✔
