### ISSUE TITLE
"Zumindest erwiesen sich die uggys nicht als vollkommen unmenschlich."

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#485]
Der Satz ist ein bisschen lustig. Ähnliche Konstruktionen kommen zuweilen im Zusammenhang mit den Äöüzz vor. Was tun, einfach so lassen?

**Comment by ToBeFree** [comment]
Im Zusammenhang mit den Äöüzz, jetzt wo du es sagst: Äöüzz sind Menschen. Das habe ich an vielen Stellen konsequent durchgesetzt und dabei sogar eine mögliche Verwirrung des Lesers ganz absichtlich in Kauf genommen. :)

**Comment by ToBeFree** [comment]
Im Zusammenhang mit uggys, oder mit den Äöüzz, als die Protagonisten diese Gruppierung gerade erst kennen lernen:

Gerne so lassen. Falls dir aber eine weniger verdrehte Ausdrucksweise einfällt, natürlich gerne ersetzen. ^^

**Comment by yur-y** [comment]
Äöüzz sind Menschen? Ich dachte, sie gehen vielleicht aus irgendeiner vormals menschlichen Besiedelung hervor etc., aber sie haben immer noch 3 Augen und grünes Fell. ;)

**Comment by ToBeFree** [comment]
@yur-y Das ist eine philosophische Frage, keine biologische. Ich war mir sicher, du würdest mir da sofort zustimmen. ;)

**Comment by yur-y** [comment]
Verstehe ich nicht.^^

**Comment by ToBeFree** [comment]
Wenn es Begriffe wie "Menschlichkeit" gibt, dann erfüllen die Äöüzz diese Kriterien genauso wie Erdgeborene. Welchen Begriff sollte stattdessen ein Äöüzz verwenden?
Auf mich wirkte es beim Schreiben irgendwie komisch, wenn ich z. B. erklären musste, dass da eben die vier Protagonisten und drei Äöüzz am Fenster stehen

**Comment by ToBeFree** [comment]
Moment, habe versehentlich auf "Close and comment" getippt

**Comment by ToBeFree** [comment]
Beitrag ist fertig, siehe oben

**Comment by ToBeFree** [comment]
Okay, die "sieben Menschen" sind in der aktuellen Fassung gar nicht vorhanden. "Zu siebt standen die Örz-Bewohner am Fenster", finde ich eine sehr schöne Lösung.

**Comment by ToBeFree** [comment]
"Menschlich" ist zwar eigentlich streng wörtlich genommen ein merkwürdiger Begriff in solchen Zusammenhängen, aber der Duden definiert es beispielsweise mit "tolerant, nachsichtig; human".

Das ist also in Ordnung, würde ich sagen. Da ich gerade die Issues durcharbeite, schließe ich hier -- gerne wieder öffnen, falls das hier wirklich ein zu lösendes Problem ist. 🙂
