### ISSUE TITLE
"In" oder "auf" Wikipedia?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#486]
"Free hatte sich einmal die Regeln in Wikipedia durchgelesen, konnte es aber auch nicht spielen."

Ich würde ja zu "auf" (oder falls "in", dann sogar "in der") tendieren, bin mir aber auch unsicher.

PS: Ich verwende keine Seitenzahlen mehr, weil meine nach einigen Reformatierungen des Inhaltsverzeichnisses und längenverändernden Korrekturen mittlerweile anders sind. Ich hoffe, die Suche genügt?

**Comment by ToBeFree** [comment]
Suche ist super, der Quelltext liegt ja vor.. Ich öffne den immer über GitHub im Browser und nutze die Suchfunktion des Browsers. Seitenzahlen dienten von meiner Seite nur zum Markieren von Fehlern im physisch vorliegenden Testdruck.

**Comment by ToBeFree** [comment]
Zu Wikipedia, das frage ich mich auch immer. Sowohl im Englischen, als auch im Deutschen. Wir sollten uns wohl an den Wikipedia-Richtlinien orientieren - - an den etablierten, beinahe als Regeln geltenden Seiten. Diese sind in der deutschsprachigen Wikipedia leider nicht immer so klar als "policy" gekennzeichnet wie in der englischsprachigen.

Blinder Vorschlag: [[WP:V]] in de.wikipedia.org - - Link folgt.

**Comment by ToBeFree** [comment]
https://de.wikipedia.org/wiki/Wikipedia:Belege

**Comment by ToBeFree** [comment]
Ha, Volltreffer. :)

"in der Wikipedia", zweimal. Eins davon im Einleitungssatz.

**Comment by ToBeFree** [comment]
Besser, und im verlinkten Artikel ständig bevorzugt:

"die Regeln in einem Wikipedia-Artikel durchgelesen". Löst das Problem und sieht gut aus, finde ich. :)

**Comment by yur-y** [comment]
✔
