### ISSUE TITLE
yury mal wieder leicht diktatorisch...

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#488]
Alexandra wollte gerade einen Vorschlag machen, aber yury kam ihr zuvor:

»Nein, das werden wir nicht tun.«

Alexandra war baff. »Kannst du Gedanken lesen?!«

»Hin und wieder. Lass uns weiter Doppelkopf spielen.«

...und Alexandra lässt es sich einfach gefallen, was auch nicht ihrem Charakter entspricht.

- Die Stelle irgendwie verändern und yury dabei weniger diktatorisch machen, aber den Witz möglichst erhalten?
- Alexandra lässt es sich nicht gefallen...aber dann ist die Frage, was ihr Plan ist?
- ...

**Comment by ToBeFree** [comment]
Ihr Plan ist, eine Bombe aus dem extrem energiedichten Lithium-Ionen-Akku des Handys zu basteln. In einem Dokument, das mit meinem Namen und meiner Adresse unwiderruflich frei um die Welt geschickt wird, wirkt sich eine solche (nicht unbedingt unrealistische, siehe YouTube!) Bomben-Bauidee möglicherweise dauerhaft negativ auf meine Einreisechancen in verschiedene Länder aus. :wink: 

Daher werde ich auch meinen Kommentar hier in den nächsten Wochen ein bisschen zensieren. Natürlich mit dicken Zensierbalken.

Die Stelle ist aber eigentlich -- finde ich -- nur wirklich witzig, wenn man den Zusammenhang zwischen dem "nicht brauchbaren Handy" und Alexandras unausgesprochenem Gedanken instinktiv begreift. Das dürfte nahezu niemandem so gehen, auch mir nicht, wenn ich die oben beschriebene, unzensierte Entwurfszene zuvor nicht geschrieben hätte. 

Das kann also beliebig verändert werden; zumindest von meiner Seite aus wäre das wirklich kein Problem. Der Witz existiert ja gar nicht.

Falls die Szene sogar dann lustig wirkt, wenn man den Hintergrund nicht kennt, dann könnten wir natürlich gerne versuchen, das aufrecht zu erhalten. Dieses Feedback hatte ich natürlich bisher nicht.

**Comment by ToBeFree** [comment]
Der Witz ist nicht so wichtig. Der Logik- und Moralfehler wiegt in meinen Augen schwerer. Ich finde, das kann weg. :)

**Comment by ToBeFree** [comment]
Witz erhalten und Moralfehler behoben. 🙂
