### ISSUE TITLE
»Sucht mal in allen Fächern und Räumen dieses komischen Raumschiffes nach einer anderen CD, auf der ›Örslängü‹ steht!«

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#489]
Ich finde die Szene eigentlich ganz nett. Andererseits sollten die vier mittlerweile gut genug Örzlängü sprechen, um darauf nicht angewiesen zu sein.

**Comment by yur-y** [comment]
Ach ja, und dass die "CD" in Örzlängü beschriftet ist, ergibt natürlich auch keinen Sinn.

**Comment by ToBeFree** [comment]
Oooooh. :D 

Ja, ich würde vorschlagen, die Szene zu behalten und einfach "Englisch" auf die CD zu schreiben. Vielleicht kann sogar ein kleiner Denkfehler, wie er uns (mir) damals unterlaufen ist, eingebaut werden: yury fragt nach einer "Örslängü"-CD, aber Orakel findet nur "Englisch". Vielleicht wirft er die sogar erstmal weg. Da ließe sich, wenn gewünscht, noch relativ gut eine kleine Erweiterung vornehmen.

**Comment by yur-y** [comment]
✔
