### ISSUE TITLE
5 Milliarden Basketbälle...

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#491]
...nehmen lediglich eine Fläche von einigen Hundert Quadratkilometern ein, also kleiner als die Fläche Berlins. Ist also vollkommen realistisch ;)

**Comment by ToBeFree** [comment]
Wie hast du das denn jetzt berechnet? :smiley: 

Ah, ich weiß. Man kann sie zweidimensional quadratisch anordnen, "lückenlos" aneinander, mit ihrem Kugeldurchmesser als Seitenlänge. Oder -- das wäre jetzt cool, falls du das wirklich gemacht haben solltest -- man verwendet Füllfaktoren, welche beispielsweise bei Kristallstrukturen verwendet werden. Dreidimensional wäre das dann im Idealfall eine "kubisch flächenzentrierte" Anordnung. Du studierst doch Mathematik. Vielleicht gefällt dir das. Bei uns war es Teil der Werkstoffe-Vorlesung. :D 

https://de.wikipedia.org/wiki/Kubisches_Kristallsystem

**Comment by yur-y** [comment]
Nö, einfach nebeneinander. ;)
