### ISSUE TITLE
Erde als Gefahr?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#492]
"Die Erde wird übermorgen, um 21:32 Uhr UTC, aus dem Weltall angegriffen. Das liegt daran, dass sie von großen, hässlichen uggy-Wesen vom Planeten ugghy als Gefahr angesehen wird."

Das ist doch angesichts der Rückständigkeit der Erde (trotz Äöüzz-Technologie) ziemlich unwahrscheinlich, oder?

**Comment by yur-y** [comment]
Oh wait. Es ist Free, der schreibt. ;)

**Comment by ToBeFree** [comment]
Haha! 😂
