### ISSUE TITLE
(Kekse?) Originaltitel: "Unklar, woher die "Vängefül Destrüktiön" eigentlich plötzlich kommt."

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#495]
Daher habe ich den letzteren Satz hinzugefügt. So OK?

»Cool, dass die uns mitgenommen haben. Hoffentlich hält sich Island an die Anleitung!«, sagte Free. Die vier hatten das gestohlene uggy-Raumschiff an die »Vängefül Destrüktiön« angedockt, das binnen weniger Örzklonks losgeschickt worden war, nachdem Alexandra die Äöüzz via IGLS über die drohende Zerstörung der Erde informiert hatte.

So könnten wir auch die Ortsangaben komplett entfernen.

**Comment by yur-y** [comment]
Oh, das ist Blödsinn. »Reg dich ab. Die uggys brauchen noch zwei Tage bis zur Erde. Also, was ich sagen wollte, wir erreichen Örz in fünfzehn Minuten.«

**Comment by ToBeFree** [comment]
Achso! Ich hatte mir das tatsächlich so vorgestellt, dass die Protagonisten kurzerhand vom Militär -- genauer: von Tisiphöne -- auf einem Militärschiff mitgenommen wurden. Wahrscheinlich, weil sie neugierig darum gebeten haben, am Einsatz zumindest als Zuschauer teilnehmen zu dürfen. Ich dachte, die sitzen da halt in einer Gästekabine, nicht in einem angedockten Raumschiff. (Wieso sollte es auch? 🙂)

Eine Erklärung wäre aber definitiv notwendig, egal, für welche Option wir uns entscheiden. Auch das Wegfallen der Ortsangaben ist ein sehr schöner Nebeneffekt, den wir auf jeden Fall nutzen sollten.

Was hältst du von:

»Cool, dass die uns mitgenommen haben. Hoffentlich hält sich Island an die Anleitung!«, sagte Free. Die vier saßen in einer geräumigen Gästekabine der »Vängefül Destrüktiön« angedockt, das binnen weniger Örzklonks losgeschickt worden war, nachdem Alexandra die Äöüzz via IGLS über die drohende Zerstörung der Erde informiert hatte.

**Comment by yur-y** [comment]
Ja, das ist super, danke. Ich hatte übersehen, dass sie ja tatsächlich zwischendurch auf Örz sind.

**Comment by ToBeFree** [comment]
😄 Dass GitHub derartige Live-Kommentarschaltungen ermöglicht, wusste ich noch gar nicht. Sehr cool. Dankeschön!

**Comment by ToBeFree** [comment]
Ich nehme an, du übernimmst ab dort -- ansonsten sag kurz Bescheid, dann entwerfe ich eine Szene :)

**Comment by yur-y** [comment]
Ah, Du willst noch ne Szene entwerfen? Gerne! ;)

**Comment by yur-y** [comment]
Hätte es jetzt so gelassen und den Dialog einfach weiterlaufen lassen^^

**Comment by ToBeFree** [comment]
:D Ok. Ich baue auf dem auf, was du im Eingangsbeitrag stehen hast. Ah! Hm. Na, ich glaube, da fehlt wirklich noch eine Erklärung. Als Antwort auf diesen Beitrag hier kommt eine Neufassung deines Vorschlags. Ob, und wie, du den einsetzt, kannst du ja noch überlegen^^

**Comment by yur-y** [comment]
Was für eine Erklärung fehlt?

Idee für Szene: Free versucht seinen Laptop irgendwie mit der Bordelektronik zu verkabeln...

**Comment by ToBeFree** [comment]
lol

**Comment by ToBeFree** [comment]
Die Erklärung, dass sie sich wirklich auf der Vängefül Destrüctiön befinden. Wobei... Das ist schon drin?

Ich gucke eben in den Quelltext.

**Comment by yur-y** [comment]
Die vier saßen in einer geräumigen Gästekabine der »Vängefül Destrüktiön«, die binnen weniger Örzklonks losgeschickt worden war, nachdem Alexandra die Äöüzz über die drohende Zerstörung der Erde informiert hatte.

**Comment by ToBeFree** [comment]
Passt 👍 :)

Ich hätte gerade noch Kekse-Essen eingebaut, oder so. Aber ich wüsste auch nicht, wo.

**Comment by ToBeFree** [comment]
(außerdem wäre das Essen von Popcorn / Keksen beim Verfolgen des Angriffs auf den eigenen Heimatplaneten möglicherweise etwas, äh, pietätlos.^^)

**Comment by yur-y** [comment]
Die vier saßen Kekse essend in einer geräumigen Gästekabine... ;)

**Comment by ToBeFree** [comment]
:D    --- also, von mir aus gerne. Zumindest zu Orakel passt es unabhängig von jeder Pietät. Falls es ein großes moralisches Problem darstellt (aber wieso eigentlich?)... dann soll ihn halt jemand darauf aufmerksam machen. 😄

**Comment by yur-y** [comment]
Ja ja, die Jugend von heute... ;)

Also wenn Du ein starkes Bedürfnis verspürst, Orakel Kekse essen zu lassen, dann nur zu ;)

**Comment by ToBeFree** [comment]
Keine Kekse, die Szene ist gut. :)
