### ISSUE TITLE
Inhaltsverzeichnis verlinken?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#496]
Wollen wir das Inhaltsverzeichnis für die E-Böök-Version zu den Kapiteln verlinken, falls das möglich ist? ;)

**Comment by ToBeFree** [comment]
Oh, das geschieht noch nicht automatisch? Dafür würde ich tatsächlich ein Plugin hinzufügen. Kommt demnächst!

**Comment by ToBeFree** [comment]
@yur-y versuch mal:

\usepackage[hidelinks]{hyperref}

Gefühlsmäßig eher _nach_ allen bisher eingebauten "usepackage"s.

**Comment by yur-y** [comment]
Done. :)
