### ISSUE TITLE
Wer soll die E-Mail an Island schreiben?

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#497]
Im Original ist es Free, der den Kontakt zu Island herstellt, und der ihn irgendwann vor dem uggy-Angriff warnt.

In der Neufassung ist es Orakel, der auf Örz eine Werbeanzeige für einen galaktischen Proxy-Service gesehen hat und sich (mehr oder weniger naiv) einfach per E-Mail mit Island über alltägliche Ereignisse unterhalten hat.

Vielleicht sollte es besser auch Orakel sein, der Island warnt. Bis gerade hatte ich das sogar so im Kopf. Siehe #492

**Comment by ToBeFree** [comment]
Apropos: Eigentlich benutzt doch auch Orakel, wie alle "normalen" Sprecher im Roman, korrektes Deutsch...

**Comment by yur-y** [comment]
Warum sollte es besser Orakel sein? Free gliedert sich dort ganz gut in die Szene ein... "Damit hatte Free nicht gerechnet. Fünfzehn Tage, fünfzehn Stunden, aber nicht fünfzehn Minuten. Schnell ging er an seinen Laptop und bemerkte, dass er das Internet benutzen konnte. Sofort schickte er eine E-Mail an Island ab. [e-mail]"

**Comment by ToBeFree** [comment]
Free hatte bis dahin noch keinen E-Mail-Kontakt mit Island, schreibt nun aber wie selbstverständlich eine E-Mail über den Dienst, den Orakel entdeckt hat. Möglich, aber vielleicht merkwürdig.

**Comment by ToBeFree** [comment]
Okay, seit Orakel seinen Freunden von der E-Mail-Unterhaltung mit Island berichtet hat, ist genug Zeit vergangen. Außerdem haben die Freunde Island seitdem persönlich getroffen und ihm den Schutzschildgenerator gegeben, den er während dieser Szene bereits nutzt. Island weiß also, dass die Protagonisten leben, und dass die E-Mails von Orakel echt waren. Es wäre nicht allzu verwunderlich, wenn Free in der Zwischenzeit (nach mehreren Örz-Aufenthalten!) ein Konto bei IGLS TransparentProxy eingerichtet hat und dazu in der Lage ist, E-Mails an Erdbewohner zu senden. Vielleicht ist es nicht einmal seine erste E-Mail an Island.
