### ISSUE TITLE
Wichtig: Die FÄZ ist ein Medium von Örz! Für eine irdische Publikation bitte den "Washington Herald" verwenden. ;)

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#499]
"yury es sich nicht nehmen, auf seinem E-Böök über das Örznet die FÄZ zu lesen, die völlig absurde Spekulationen darüber aufstellte, wie Floating Island es geschafft hatte, die Welt zu retten."
... "Die FÄZ macht Propaganda für ihn"

Hier muss irgendeine irdische Zeitung stehen! Die Frage ist nur, ob wir eine reale Zeitung anschwärzen wollen oder wie wir das lösen.

**Comment by ToBeFree** [comment]
Ooooh!

**Comment by ToBeFree** [comment]
Nein, wir sollten keinen realen Zeitungsnamen verwenden. Das heißt aber nicht, dass wir uns nicht einen Namen ausdenken können, der "irdisch" klingt. Wie wäre es mit "North Wales Tribune"?

**Comment by ToBeFree** [comment]
Guck mal, die Idee hatte nicht nur ich. :)

https://en.wikipedia.org/wiki/Washington_Herald

**Comment by ToBeFree** [comment]
Kein Fehler, nur eine Notiz
