### ISSUE TITLE
Abwehrsysteme auf den Planeten...

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#500]
...bringen nicht so wirklich viel, weil man ja nicht gerade an den Planeten vorbei ins Sonnensystem reinfliegen muss. Ist sogar vermutlich ziemlich unwahrscheinlich, dass sowohl Pluto als auch Jupiter da genau auf dem Weg liegen ;)

**Comment by yur-y** [comment]
**Wichtig:** Weiterer Folgefehler zu Beginn von Kapitel 23. Evtl. der Übersichtlichkeit halber oben in die Aufzählung aufnehmen?

Auf Örz angekommen, ließ yury als Erstes die Nämäsis-Kanone repa-
rieren und neue Planetenraketen einbauen.
»Ihr solltet das nächste Mal vielleicht ein bisschen sparsamer mit den
Raketen umgehen«, merkte yury an.
»Aber die haben uns doch mit Kanonenschüssen provoziert«, be-
schwerte sich Alexandra.
»Und deshalb musstest du mit fünf schwarzen Löchern einen Mond in
unserem Sonnensystem zerfetzen⁈«
»Ja.«

**Comment by ToBeFree** [comment]
Oh, Mist. Dann werden mir die Folgefehler aber zu viele.

Es gibt noch eine Möglichkeit. Die Freunde fliegen *absichtlich* dorthin.

Dafür müsste man sich nur einen Grund überlegen.

**Comment by ToBeFree** [comment]
(da mir momentan keiner einfällt, befürchte ich, dass es letztendlich wirklich auf Streichen hinausläuft. Vielleicht genügt es, Pluto zu streichen, und den Jupitermond als Zufall zu betrachten?

**Comment by ToBeFree** [comment]
Wir können ja davon ausgehen, dass das Außendisplay des Schiffs einige "Verbesserungen" am schwarzen Sternenhimmel vornimmt. So wie ein Head-up-Display. Dadurch wird es deutlich wahrscheinlicher, dass die Freunde sich für einen kurzen Abstecher zu einem "fast" auf dem Weg liegenden Planeten oder Mond entscheiden.

Beispiel für ein solches Head-up-Display, und ein Flug durch unser Sonnenystem:
https://www.youtube.com/watch?v=gzyAq3GYYiI

Überspringe Planetenlandungen -- die Flugszenen zwischen den Planeten sind das, was ich meine. In diesem Spiel finden Sprünge immer von Stern zu Stern statt, während die IA-Protagonisten von außen einfliegen -- das kann ich gerne mal nachspielen und aufnehmen. Zur groben Vorstellung genügt aber wahrscheinlich das oben verlinkte Video.

Wegen "zweidimensional": Das Sonnensystem ist glücklicherweise ziemlich flach (ebenfalls im Video realistisch dargestellt). Dieser Aspekt kommt uns also kaum in die Quere.

**Comment by yur-y** [comment]
Und noch mehr **Folgefehler**: "Ich habe neulich in einem Katalog eine Türbö Tächyön 2100 gesehen, mit der man relativ preiswert durch die Verteidigungsanlagen im Sonnensystem brechen könnte."

**Comment by ToBeFree** [comment]
Zu "fast auf dem Weg": Das gilt nicht für alle Planeten; der Warpantrieb ermöglicht zwischen Planetensystemen eine deutlich höhere Geschwindigkeit als innerhalb eines Planetensystems. Es kann durchaus einen Umweg darstellen, an der Erde vorbei zu fliegen, Pluto zu besuchen und zurück zur Erde zu fliegen. Anders sieht es aus, wenn sich Pluto "vor" der Erde befindet und als Zwischenstopp gewählt werden kann.

**Comment by ToBeFree** [comment]
So, das wird ein gutes Stück Arbeit xD

**Comment by ToBeFree** [comment]
Noch einmal genauer nachgedacht; hier ist die Lösung.

Es ist extrem unwahrscheinlich, dass Privatpersonen schwere Kriegswaffen zur Ausrüstung eines Erkundungs-Raumschiffs kaufen dürfen. Es ist geradezu absurd, dass das interplanetare Äquivalent zur planetaren Atombombe vollkommen legal irgendjemandem außerhalb des Militärs zur Verfügung stehen soll. Das ist so, als würde man Erdbewohnern erlauben, Atomraketen für den privaten Gebrauch zu erwerben.

Als wäre das nicht wahnsinnig genug, fliegen die Freunde mit dieser Massenvernichtungswaffe **nach ausdrücklichem Auftrag eines Äöüzz-Gerichts** in ein Planetensystem ein, zu dem gesetzlich selbst grundlegende Kontaktaufnahme und Handel verboten sind. Nachdem sie dazu verurteilt wurden, die Schäden ihres letzten Besuches zu reparieren, besuchen sie das Sonnensystem und zerstören als allererstes einen Jupitermond. Na klar.

Schade um die Szene, aber das kann so nicht bleiben.

Zur Form des Sonnensystems und der Position von NGC 6193: Man kann in der freien Astronomiesoftware "Celestia" folgende Schritte durchführen:

- Sol auswählen (dafür gibt es einen Menüeintrag)
- Auswahl zentriert halten
- In den Anzeigeoptionen die "Orbits" und "Bezeichnungen" für Planeten aktivieren
- In den Anzeigeoptionen die Sternbilder mit Linien, Grenzen und lateinischen Namen aktivieren
- Mit dem Mausrad herauszoomen und mit der rechten Maustaste rotieren, bis alle Planetenbahnen schön sichtbar sind
- Mit der rechten Maustaste rotieren, bis das Sternbild "Ara" (deutsch: "Altar") im Bild erscheint. Es grenzt an Scorpius, ein möglicherweise leichter zu findendes Sternbild. Das Kreuz des Südens (Crux) ist ein gutes Zeichen dafür, dass man in die richtige Richtung guckt.

Dann sieht man, dass es tatsächlich unrealistisch ist, dass ein Raumschiff aus dieser Richtung zuerst andere Planetenbahnen passieren soll, bevor es bei der Erde ankommt.
