### ISSUE TITLE
Seitenumbruch

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#505]
Der Seitenumbruch auf der 2. Seite von Kap. 23 vor "»Nein, das ist kein Zufall«, sprach der Computer, der inzwischen hochgefahren war." sollte unbedingt erhalten bleiben, ist ein genialer - Zufall! Dürfte allerdings auch nicht so schwer sein, es ist ja nur eine Seite dazwischen.

**Comment by ToBeFree** [comment]
Theoretisch ließe sich ein Zeilenumbruch forcieren, sogar ein Doppelseiten-Umbruch (je nach Wunsch bei einer geraden oder ungeraden Seite). Das hat allerdings auch ein gewisses Schadenspotenzial: Wenn der forcierte Umbruch überhaupt nicht passt, entsteht entweder eine Leerseite, eine Beinahe-Leerseite, oder riesige Zeilenabstände zum Auffüllen.

Gerne einfach im Kopf behalten - - Issue bleibt offen

**Comment by ToBeFree** [comment]
Ich befürchte, wir werden auf diesen zufälligen Seitenumbruch verzichten müssen. 😅

**Comment by ToBeFree** [comment]
Ein forcierter Seitenumbruch an dieser Stelle wäre jedenfalls äußerst unschön, vor allem dann, wenn du einen "Doppelseiten"-Umbruch möchtest, sodass die überraschende Nachricht erst beim Umblättern sichtbar wird.
