### ISSUE TITLE
"Orakel und Alexandra hatten Mühe, yury davon abzuhalten, das Schiff in die Luft zu sprengen, nur, damit die unkontrollierte Fahrt gestoppt würde."

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#506]
...und damit auch sich selbst in die Luft zu sprengen? Verstehe ich nicht...

**Comment by ToBeFree** [comment]
Naja, das ist absichtlich eine absurde Idee, nach dem Motto "Das Schiff bewegt sich ja gar nicht mehr, wenn das Schiff nicht mehr existiert".

"Aliens can not destroy your ship

if you self destruct!"

http://nymag.com/selectall/2017/02/roll-safe-the-guy-tapping-head-meme-explained.html

**Comment by ToBeFree** [comment]
Falls es zu dumm oder unlustig ist, gerne ersetzen oder streichen. Vielleicht fällt dir eine absurde, aber theoretisch tatsächlich sinnvolle Anhaltemöglichkeit ein. Etwa:

"Orakel und Alexandra hatten Mühe, yury davon abzuhalten, die Wasserstoffreaktoren zu zerstören, nur, damit die unkontrollierte Fahrt gestoppt würde."

Oder die Triebwerke, was von Innen ein bisschen schwierig sein dürfte. :)

**Comment by yur-y** [comment]
https://www.bloomberg.com/view/articles/2018-02-09/destroying-a-quote-s-history-in-order-to-save-it ;)

**Comment by yur-y** [comment]
Würde es dann so lassen?

**Comment by ToBeFree** [comment]
Nur, wenn der Witz nicht zu blöd ist. Kann ich nicht beurteilen. Ich
persönlich würde es eher so lassen, als es realistischer umzuschreiben. 😄
