### ISSUE TITLE
Kapiteleinteilung

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#507]
Kapitel 5 und 23 sind mit 3,5 bzw. 2 Seiten schon sehr kurz. Ich bin mir aber nicht sicher, ob das ein Problem ist.

**Comment by ToBeFree** [comment]
In der aktuellen Form (vielleicht bereits behoben) ist es in Ordnung, denke ich. Die Infinite Adventures haben einen extrem knappen Erzählstil, der auf viele detaillierte Szenenbeschreibungen verzichtet. Mir persönlich gefällt das eigentlich ganz gut. 🙂
