### ISSUE TITLE
"meinte", "sagte"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#508]
- "genervt" (40-mal). Alternativen: missmutig, entnervt, "sagte genervt" -> "beschwerte sich", ....?
- "»x«, meinte y." (Vermutlich aus dem Wunsch heraus, nicht zu oft "sagte" zu verwenden. "Meinte" ist aber nicht wirklich ein Synonym.) Alternativen: ... [Kurze Statistik: "sagte" (303-mal), "meinte" (165-mal, fast ausschließlich in dieser Bedeutung), "antwortete" (84-mal), "erwiderte" (7-mal), ...]
- ...

Ergänzungen trage ich hier oben ein.

**Comment by ToBeFree** [comment]
Die Zeichenkette "nervt" kommt im ganzen Roman nur noch 20 mal vor, was auf knapp 400 Seiten hoffentlich in Ordnung ist. Danke für die bisherigen Ersetzungen. 🙂

**Comment by yur-y** [comment]
Ich denke, es dürfte so in Ordnung sein. Von mir aus schließen :)

**Comment by ToBeFree** [comment]
Es gibt leider nicht allzu viele Alternativen. 😄 

Vieles ist kontextabhängig, ich nutze inzwischen häufiger "stimmte zu", "widersprach" etc. -- aber an manchen Stellen kann man wenig machen.
