### ISSUE TITLE
Stelle: Vierte Wand

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#509]
Ich finde die Stelle genial.

»Du musst umblättern«, sagte yury dann, an Dich gerichtet. »Und
bitte vorher den nächsten Absatz mit einem dicken schwarzen Stift durch-
streichen.«

Das Universum explodierte, und die Welt hörte auf, zu existieren.

Aber kurze Frage: Müsste es nicht "den nächsten Satz" heißen?

**Comment by ToBeFree** [comment]
Oh, dankeschön! 😄

Ja, auf jeden Fall. Vielleicht hatte ich in einer älteren Version dort mehrere Sätze stehen.

**Comment by yur-y** [comment]
✔
