### ISSUE TITLE
Zeit im IA-Universum

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#512]
»Unser gesamtes Justizvollzugssystem wurde vor einigen Jahrtausen-
den durch eine bahnbrechende Erfindung revolutioniert. Im Jahr 5533 ist
uns endlich gelungen, nicht nur die schwersten ›klassischen‹ Krankhei-
ten, sondern auch psychische Grundmängel wie die Erwägung kriminel-
ler Handlungen heilbar zu machen.

Ich habe daraus jetzt mal das "Jahr 5533 Ä. Ö." gemacht, um klarzumachen, dass es sich um Örz-Jahre und Örz-Zeitrechnung handelt. Trotzdem weist die Stelle auf ein grundsätzlicheres Problem hin: Im IA-Universum ist es derzeit (implizit) so, dass die Äöüzz auf irgendeine unbekannte Weise aus einer vormaligen menschlichen Zivilisation hervorgegangen sind. Aber dann müssten die Menschen ja vor Jahrhunderten oder Jahrtausenden Überlichtreisen erfunden haben, damit es zeitlich passt - sofern es keine Zeitreisen gibt.

Mögliche Lösungen:
- Die Äöüzz gehen nicht aus einer irdischen Zivilisation hervor. (Aber warum dann die ganzen Andeutungen?)
- Die vier reisen ständig in der Zeit hin und her, ohne es zu wissen, wenn sie zwischen Örz und Erde reisen. (Unelegant und erfordert Zeitreisen.)
- Die irdische Zivilisation, aus der die Äöüzz hervorgegangen sind, hat aus der Zukunft der Protagonist_innen (gleichzeitig mit oder nach der Reise nach Örz) eine Zeitreise in die Vergangenheit unternommen. (Erfordert Zeitreisen.)
- Gibt es weitere Möglichkeiten?

Wenn wir uns damit anfreunden können, dass Zeitreisen im IA-Universum möglich sind, finde ich glaube ich von den bisherigen die dritte Idee am besten. Dann würde sich allerdings die Frage stellen, ob wir das noch ein bisschen mehr im Buch andeuten wollen.

**Comment by ToBeFree** [comment]
Die dritte Idee ist tatsächlich sehr reizvoll. Auf sowas wäre ich gar nicht
gekommen. 😄👍

Zeitreisen, von SOTIs Manipulationen abgesehen, sind aber möglicherweise
ein bisschen... zu sehr konstruiert. Zu sehr "Standardausrede" bzw.
"Totschlaglösung". Ich finde die dritte Idee aber sehr kreativ und
vorstellbar. Das ließe sich umsetzen, falls dich meine ursprüngliche Idee
nicht überzeugt.

Mein ursprünglicher, keine Zeitreisen erfordernder Gedanke war, dass die
Äöüzz tatsächlich eine frühe Abspaltung der menschlichen Zivilisation sind.
Das könnte zum Bespiel vor dem Mittelalter geschehen sein. Die alten
Griechen oder Römer wären das dann gewesen. Wohl eher letztere, denn die
Griechen waren meines Wissens nach äußerst demokratisch, während die
Konzernherrschaft der Äöüzz noch am ehesten an römische Verhältnisse
erinnern mag, und außerdem, weil ich glaube, dass man über die Römer mehr
technische bahnbrechende Erfindungen als mögliche Erklärung findet.

Und was ist dann eigentlich passiert? Mehrere Möglichkeiten. Entweder Hilfe
von außen, oder Entführung von außen, oder selbstständiger Raumflug.
Letzteres ist möglicherweise zu absurd, kann aber lustig verarbeitet
werden: Bereits damals flog eine Gruppe von Verrückten mit einem vollkommen
ungeeigneten hubschrauberähnlichen Gerät durchs Weltall. Das muss nicht
einmal mit Überlichtgeschwindigkeit geschehen sein, sondern kann durch
relativistische Effekte bei Nahe-Lichtgeschwindigkeit für die Fliegenden
wie eine kurze Kaffeefahrt gewesen sein. Bei der Entfernung nach Örz ist
der Zeitrahmen schwer erklärbar: 4000 Lichtjahre mit
Lichtgeschwindigkeit... Zumindest die Römer wären eindeutig noch heute
unterwegs.

Bei Hilfe oder Entführung von außen wird der Zeitrahmen plausibler. Die
Ur-Äöüzz wurden von Außerirdischen entführt, vielleicht sogar genetisch
manipuliert, falls das kein eigener Entschluss war. Düster. Zumindest wäre
vollkommen klar, wieso die Äöüzz das Thema als Tabu behandeln. Letztendlich
haben sich die Äöüzz über ihre Helfer oder Entführer erhoben. Entweder als
Masse (alle Äöüzz befreien sich und erobern das noch sehr kleine
Alien-Reich), oder als Splittergruppe: Eine Gruppe von Ur-Äöüzz entkommt
den Entführern, bzw. versteckt sich vor den Helfern. Die Splittergruppe
landet auf einem wunderschönen Planeten, einem Paradies. Es wird Örz
genannt, ganz klar nach der Erde (Earth), als Erinnerung an die frühere
Heimat. (Anmerkung: Wie alt ist das Wort? Etymologie? Ansonsten einfach
"lustiger Zufall" oder Ergebnis einer Rückwärts-Beeinflussung der
Erdbewohner.) Während die Aliens degenerieren, entwickelt sich die
Splittergruppe mithilfe gestohlener Alien-Technologie immer weiter. Dies
geschieht rasend schnell, angetrieben durch jahrhundertelange permanente
Angst vor dem Feind. Krieg und Angst waren schon immer ein wirksamer
Forschungsantrieb. Und irgendwann überrennt die Splittergruppe die früheren
Helfer bzw. Entführer. Gnade bzw. bedingungslose Rache sind das Ergebnis.
Falls es sich um Entführer gehandelt hat, wird in einer später als
unmoralisch verurteilten Aktion die gesamte Zivilisation dem Erdboden
gleich gemacht. Alternativ, und weniger unmoralisch: Die Splittergruppe
kehrt nach Jahrhunderten mit Erkundungsschiffen zurück zu den Aliens. Dort
zeugt nur noch ein Nuklearer Winter, oder ein zerbrochener Gesteinsbrocken,
oder ein weißer Zwerg an Stelle der Sonne, oder eine Horde degenerierter
Urwaldbewohner vom tragischen Untergang der früheren Helfer/Entführer.
Möglicherweise ist die Splittergruppe entstanden, weil ein paar
intelligente Menschen diesen Untergang vorausgeahnt haben.

**Comment by yur-y** [comment]
Das ist genial! Nur die Etymologie von "Örz" wird dann nicht funktionieren, und wir müssten die obige Passage anpassen... Ein Örzjahr ist ja nur ein wenig länger als ein Erdjahr.

**Comment by ToBeFree** [comment]
Dankeschön 😄 

Ich schlage die Zeit vor, in der Marcus Tullius Cicero, dessen Bruder Quintus (Déjà vu! 😄) und Gaius Iulius Caesar gelebt haben. Das war dann zwischen 100 v. Chr. und 44 v. Chr.. Wichtig zu beachten hierbei ist, dass es damals diese Jahreszahlen eben noch gar nicht gab, und dass "v. Chr." niemand etwas von "Chr." wissen konnte. Es gibt aber seit **45 v. Chr** den julianischen Kalender, der bereits weitestgehend unserem heutigen gregorianischen Kalender entspricht.

https://de.wikipedia.org/wiki/Kalenderreform_des_Gaius_Iulius_Caesar

https://de.wikipedia.org/wiki/Ab_urbe_condita_(Chronologie)

Apropos, den Term "Ab urbe condita" könnte man abwandeln und als "ÄÜC" für die Äöüzz-Jahresrechnung nutzen. 😉 

In den IA ist kein Datum angegeben, aber an einer Stelle wird unter der Müngstener Brücke ein Restaurant aus rostigen Platten gebaut. Das war gegen 2012, glaube ich. Dieses Detail würde ich vernachlässigen und grob 2020 als Jahr der aktuellen Handlung verwenden.

Für die Äöüzz-Chronologie dürfen wir keine allzu großen Zeiträume veranschlagen, wenn die Äöüzz genügend Zeit für die enormen technischen Entwicklungen bis heute haben sollen. Es darf z.B. nicht erst nach tausend Jahren eine Abspaltung geben. Sinnvoller erscheinen mir ca. 45-65 Jahre (weil man damit leicht rechnen kann, und weil diese Dauer mindestens notwendig sein dürfte, damit genetisch manipulierte Neugeborene als Erwachsene ein Raumschiff stehlen können). Dann fände nämlich die Abspaltung der Splittergruppe und die erste Besiedlung von Örz gegen "0"-20 n. Chr. statt. Um die Jahreszahlen ein bisschen aufzublähen, und damit sie nicht so langweilig identisch mit unseren heutigen Jahreszahlen sind, verwenden die Äöüzz vielleicht mit einem gewissen Heimweh die alte römische Jahreszählung: Dann wird immer "753" zu unserer Jahreszahl addiert. 

Rechenbeispiel: Die Römer werden 45 v. Chr. entführt, deren Nachkommen fliehen um "0" und gründen auf Örz ihre Siedlung im Paradies. Auf die Jahreszahl wird "753" addiert. Das Jahr 2020 n. Chr. entspricht dem Jahr "2773 ÄÜC". Ich finde, 2773 sieht schön aus.

Oder so ähnlich.

**Comment by ToBeFree** [comment]
Achso, dabei ist gar nicht berücksichtigt, dass Erd- und Örzjahre eben nicht hundertprozentig identisch sind.

So einfach wird es dann wohl nicht. Trotzdem ist 2773 eine schöne Jahreszahl.^^

**Comment by yur-y** [comment]
Finde ich prinzipiell gut, aber dann brauchen wir noch eine gute Erklärung für die Englisch-Ähnlichkeit von Örzlängü und das dürfte sehr schwer werden. Übrigens spielt der Roman wahrscheinlich Anfang der 2020er-Jahre: Der von Island in Auftrag gegebene "Tower of Liberty" - eine Anspielung auf das [One World Trade Center](https://en.wikipedia.org/wiki/One_World_Trade_Center), vormals "Freedom Tower" - ist 2022 Fuß hoch.

**Comment by ToBeFree** [comment]
Ich habe jetzt "1984 ÄÜC" geschrieben. Ich glaube, das passt. :)
