### ISSUE TITLE
Eine halbe Lichtsekunde pro Quadratsekunde...

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#513]
...heißt, dass man in zwei Sekunden bis auf Lichtgeschwindigkeit beschleunigen kann. Mit der Beschleunigung braucht man nach meinen Berechnungen über 8 Tage, um von Örz zur Erde zu kommen. Um die Maximalgeschwindigkeit der 4-6692 zu erreichen, falls das möglich wäre, bräuchte man sogar über 100 Tage.

»Mensch, hat das Ding einen Wasserstoff-Verbrauch«, staunte Free beim Blick auf die Tankanzeige.
»Dafür sind wir innerhalb von 6 Stunden am Ziel«, freute sich Alexandra.

Irgendwas stimmt da nicht. ;) Ist das neue Raumschiff jetzt entsetzlich langsam oder superschnell?

REMINDER: yury überschlug kurz eine Rechnung im Kopf, dann wurde ihm schwindelig. »Zwei Meter pro Femtosekunde. Das ist ja vollkommen wahnsinnig.«

»Erzähl das dem Raumschiffverkäufer, der dir das Doppelte angeboten hat«, witzelte Orakel.

**Comment by ToBeFree** [comment]
Oh ja :) Die Geschwindigkeitsangabe muss möglicherweise stark nach unten
angepasst werden, um nicht vollkommen unrealistisch zu sein.

Es gibt beim Warpflug im IA-Universum, zumindest nach meinen bisherigen
Entwürfen, einen Unterschied zwischen Normalraumflug und Warpflug. Der
Normalraumflug kann niemals Lichtgeschwindigkeit überschreiten und
unterliegt (theoretisch, aber nicht konsequent umgesetzt) relativistischen
Effekten. Nur der Warpfeldgenerator ermöglicht es, die Relativität
plötzlich vollständig aufzuheben. Geschwindigkeiten werden dann in
Lichtjahren pro Zeiteinheit gemessen; ein Flug dauert für Passagiere und
Außenstehende exakt gleich lang. Der Übergang zwischen den beiden Flugarten
ist bei unvorsichtigem (oder mutwillig destruktivem) Umgang für alle
Objekte außerhalb der platzenden Warpblase mit einem Gravitationsschock
verbunden, der Orakel durch die Luft fliegen und Alexandra ein Schaltpult
zertrümmern lässt. In der uggy-Piratenszene wird beim erzwungenen Stopp
deutlich, dass der Warpantrieb auch (zwangsweise, möglicherweise stark
belastend) unter Lichtgeschwindigkeit aktiv sein kann und auch dann alle
relativistischen Effekte aufhebt.

Der Türbö Tächyön soll ein Normalraum-Beschleunigungs-Monster sein. Mit
relativistischen Effekten gilt die Rechnung übrigens nicht. Trotzdem ist
die Beschleunigung enorm und viel zu groß für ein Raumschiff. Solche
Beschleunigungen treten aber durchaus auf, im CERN-Teilchenbeschleuniger
zum Bespiel.

Und natürlich hat auch der Türbö Tächyön ein wahnwitziges Warpmodul,
welches unter enormem Wasserstoffverbrauch und bei äußerst geringer
Lebensdauer (3 Jahre vs 30 Jahre, kleines Spaßfahrzeug vs großes
Erkundungsschiff) einen sehr kurzen Flug zur Erde ermöglicht. Das müssen
aber auch nicht unbedingt 6 Stunden sein, sondern gerne mehr.

Apropos: Masse ist schwer und nur energieintensiv zu befördern. Davon kann
die NASA bei jedem Raketenstart ein Lied singen. Zudem steigt der
Warpantrieb-Treibstoffverbrauch äußerst nicht-linear mit der gewünschten
Geschwindigkeit an. Der Türbö Tächyön kommt nur deshalb ohne Zwischentanken
aus, weil er so leicht ist. Die 4-6692 könnte gar nicht genug Wasserstoff
tanken, um in einem einzigen Hinflug mit dieser Geschwindigkeit zur Erde zu
fliegen. Langsamer Flug ist erforderlich, um den Verbrauch so zu halten,
dass die 4-6692 ohne Zwischenstopp von Örz nach Örs (oder zum Helix-Nebel)
kommt.

Apropos, Falls der Flug zum Helixnebel zu schnell ist, bitte die Zeitdauer
verlängern - - eigentlich müssen die Freunde einige Tage an Bord des
entführten Schiffes verbringen. Mache ich aber gerne einfach nachträglich.

**Comment by yur-y** [comment]
Ah, das mit dem Normalraumflug hatte ich nicht verstanden. Dachte mir nur, dass die Beschleunigung entweder viel zu langsam oder viel zu schnell ist.^^ Welche Beschleunigung empfiehlst Du denn für den Normalraumflug?

**Comment by yur-y** [comment]
@"(theoretisch, aber nicht konsequent umgesetzt)": Was wären denn bisher nicht berücksichtigte Effekte? (Die fliegen doch nur während sehr kurzer Zeit im "Normalraumflug" zu relativistisch relevanten Geschwindigkeiten?) Und welche wurden bisher umgesetzt?

**Comment by ToBeFree** [comment]
Ein Effekt, der mir in den Sinn kommt, ist eine Farbverschiebung der von außen eintreffenden elektromagnetischen Strahlung (eben auch Licht). Diese könnte aber durch die Außenbeobachtungs-Computer ausgeglichen werden, sodass auf den Displays nichts davon zu bemerken ist.

**Comment by ToBeFree** [comment]
Hab dir ein PDF geschickt. Über die Beschleunigung des Türbö Tächyöns im Normalraumflug müssten wir uns noch Gedanken machen. Es kommt darauf an, welche Limits wir setzen wollen. Das absolute untere Limit für jedes Raumschiff dürfte die Beschleunigung sein, mit der man von einem Planeten mit x-facher Erdgravitation noch abheben kann. Sonst sitzt man fest. Vielleicht ist der "Antigravitationsantrieb" davon nicht betroffen und ermöglicht unter solchen Bedingungen noch einen langsamen, sanften Start. Trotzdem sollte ein Raumschiff meiner Meinung nach dazu in der Lage sein, ausschließlich mit den Raketentriebwerken von einem Planeten zu starten.

x-fache Erdgravitation... 5-fach vielleicht? Ab einer gewissen Schwerkraft ist der Planet ja vollkommen lebensfeindlich. Dort landet man dann vernünftigerweise sowieso nicht mit einem Raumschiff, das nicht für Extremsituationen gebaut wurde. Ein Erkundungsschiff, die 4-6692, sollte aber eine gewisse Robustheit gegenüber Extremsituationen besitzen. Bei 5-facher Erdgraviation noch ins Weltall fliegen zu können, halte ich für ein sinnvolles Minimum für die 4-6692.

Der Türbö Tächyön soll eine höhere Normalraum-Beschleunigung als die 4-6692 haben. Das hat aber nichts mit großen Planeten zu tun, sondern mit dem Spaßfaktor des rot lackierten Sportschiffs. Ich finde, ein schnelles Sportschiff sollte das träge Erkundungsschiff in puncto Beschleunigung mindestens doppelt, wenn nicht sogar vierfach, übertreffen. Und der "Türbö Tächyön" ist als Super-Luxus-Rennschiff vielleicht zehn- oder zwanzig-mal so beschleunigungsstark wie die 4-6692.

Zu beachten hierbei ist auch wieder die Masse: Die 4-6692 ist deutlich größer und schwerer als das kleine Rennschiff. Das kleine Rennschiff wird nachher vielleicht sogar in eine kleine Garage in der 4-6692 integriert oder daran als Beiboot angedockt. Die 4-6692 ist kein riesiges Monster, aber mit 100 Metern Donut-Durchmesser durchaus beeindruckend. 

(hier kommt mehr, ich experimentiere gerade mit Blender)

**Comment by yur-y** [comment]
Ich brauche ne Zahl. ;)

**Comment by ToBeFree** [comment]
Die "zwei Meter pro Femtosekunde" stimmen unabhängig von der Normalraum-Beschleunigung. Es handelt sich dabei nur um den Warpflug (4000 Lichtjahre in 6 Stunden). Falls _daran_ etwas geändert wird, muss eben diese Zahl angepasst werden.

Zur Normalraum-Beschleunigung:

Maximal-Normalraum-Beschleunigung der 4-6692 mit den Raketentriebwerken: ca. 100 m/s².

Maximal-Normalraum-Beschleunigung des Türbö Tächyön mit den Raketentriebwerken: ca. 1000 m/s². 

Damit kommt man nicht allzu schnell im Weltall voran. Man kann sich damit notfalls innerhalb eines Sonnensystems bewegen (ca. 20 Stunden für eine astronomische Einheit, von Stillstand zu Stillstand). Relativistische Effekte treten kaum auf; es ist eher der Treibstoff aufgebraucht, als dass man damit auch nur 5% der Lichtgeschwindigkeit erreicht. Diese Einschränkung erwähnt yury aber sogar in der Originalfassung des Romans, als der Warpantrieb nach der uggy-Verfolgung auf dem Mond kaputtgeht. #342

Es handelt sich nicht um klassische chemische Raketentriebwerke. Die dafür benötigte Treibstoffmenge wäre zu groß. Es wird nicht genau beschrieben, wie die Äöüzz-Technologie funktioniert, aber Wasserstoff und Fusionsreaktoren werden erwähnt.

**Comment by ToBeFree** [comment]
Die Geschwindigkeit ist okay. Dafür gibt es nicht einmal eine Toilette an Bord, denn jeder Ballast erhöht den Wasserstoffverbrauch enorm. Niemand möchte dieses Ding für eine Erkundungstour nutzen, und niemand kann darin große Waffen oder andere Ausrüstung transportieren. Wer den Tank leert, muss sich zudem vergewissert haben, dass er auf einem Planeten landet, auf dem es Wasser gibt... und eine Anlage, um daraus Wasserstoff herzustellen. Der Tächyön kann das zwar auch, aber das "Auftanken" eines leer geflogenen Tanks ganz ohne Hilfsmittel dauert mit der winzigen mitgelieferten Solatzelle mehrere Wochen. Island als Zusatzgewicht verhindert dann sogar, dass die Freunde es in einem Schub schaffen -- die Freunde stranden im All. Das kopiere ich auf die IA2-Diskussionsseite.

**Comment by ToBeFree** [comment]
https://www.freiwuppertal.de/ia-autoren/mw/index.php?title=Diskussion:IA2#Warum_der_T.C3.BCrb.C3.B6_T.C3.A4chy.C3.B6n_so_schnell_sein_darf.2C_ohne_den_Roman_kaputt_zu_machen
