### ISSUE TITLE
Zahlen im Fließtext möglichst ausschreiben

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#514]
Auch in Stellen wie "ein etwa vierzig Jahre alter Mann", aber nicht bei Kommazahlen, sehr großen Zahlen (>100 und keine runde Zahl) oder Stellen mit vielen aufeinanderfolgenden technischen Details. Im Moment geht da noch einiges. Dass wir trotzdem mehr arabische Zahlen haben werden als ein normaler Roman, ist aber auch klar.

**Comment by ToBeFree** [comment]
Kein Fehler, nur eine Notiz
