### ISSUE TITLE
"Designfehler" des Grundgesetzes

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#516]
»Ich habe gehört, das Grundgesetz habe einen kleinen Designfehler gehabt«, erklärte yury. »Von Artikel 79 wurden die wichtigsten Bestandteile der Verfassung gegen Veränderung geschützt. Es wurde aber mit keinem Satz erwähnt, dass es verboten sei, genau diesen Artikel abzuschaffen. Floating Island hat angeblich ganz legal die ›Ewigkeitsklausel‹ entfernt und anschließend die nicht mehr geschützten Grundrechte außer Kraft gesetzt.«

Nette Idee, aber das ist laut Wikipedia nicht so:

"Dass Art. 79 Abs. 3 Grundgesetz ebenfalls den Schutz der Unabänderlichkeit genießt, wird allgemein angenommen, obwohl es nicht dem Wortlaut zu entnehmen ist. Die funktionale Interpretation spricht jedoch dafür, denn andernfalls würde die Schutzwirkung sinnlos werden, was nicht dem Zweck der Norm und der Zielsetzung des Verfassungsgebers entspräche. Neben einer immanenten Begründung werden für die Unabänderlichkeit der Ewigkeitsklausel auch überpositive Gründe vertreten.

Schon in einem Aufsatz aus dem Jahre 1952 hat der Verfassungsrechtler Theodor Maunz erkannt, was er als Gebot der „Normlogik“ bezeichnet hat: dass Art. 79 Abs. 3 GG seine Schutzwirkung nur erreichen kann, wenn die Unantastbarkeit, die er für bestimmte Verfassungsgrundsätze ausspricht, auch für ihn selbst gilt. Das bedeutet, dass auch die Begründung der Unantastbarkeit in Art. 79 Abs. 3 GG selbst der Ewigkeitsklausel unterliegt."
https://de.wikipedia.org/wiki/Ewigkeitsklausel

...und es überzeugt auch nicht ganz, dass Floating Island bzw. seine Handlanger auf juristische Tricks zugrückgreifen müssten, wenn er mit den technischen Mitteln sowohl eine starke repressive als auch (zumindest am Anfang) eine ideologische Vormachtstellung hat.

**Comment by ToBeFree** [comment]
Davon wusste ich sogar. :D Aber schlimm fand ich nicht, dass es theoretische Überlegungen dazu gab, die eine Lücke verneint haben. In der Praxis kann Thilo Alfred trotzdem getan haben, was zuvor für unmöglich oder verboten gehalten wurde.

Der Einwand, dass die Erklärung wenig glaubwürdig wirkt, ist in meinen Augen schwerwiegender. Der ganze Sinn der Konstruktion war ja die Vermittlung von Glaubwürdigkeit.

Wirkt es denn wirklich absurd, dass Island auf Gesetzesbrüche verzichtet, wo Populismus und Volksmehrheit sich bereits in der Vergangenheit als "legal" wirksame Mittel zur Machtergreifung bewährt haben? ;)

**Comment by yur-y** [comment]
Nein, wir können es auch so lassen.
