### ISSUE TITLE
Gegen Ende des Romans: Taxifahrt: Orakel hat doch gar kein Bargeld. 

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#517]
Orakel muss das gerade online geraubte Geld vor der Taxifahrt abheben, und freut sich vielleicht über die großen Scheine, die er dabei erhält. Vielleicht macht er das sogar zusammen mit Ingrid, gegenüber der er irgendeinen stolz prahlenden Spruch sagen kann, und die dann über seinen "Firmenboss"-Reichtum staunt. :)

Und irgendwann (IA2?) druckt er sich dann mal einen Kontoauszug aus und erlebt eine Überraschung. SOTI hat sich genau an seine Anweisungen gehalten - - wörtlich. Aber vom "Verwendungszweck", dem Betreff-Feld der Überweisungen, war in Orakels Anfrage keine Rede. Die lauten zu seinem Entsetzen wie folgt, jeweils mit sechsstelligen Plusbeträgen:

"Kernwaffenshop24 Rückerstattung"
"Danke für die schöne Nacht ;)"
"Gute Qualität, würde ich wieder kaufen"
"Bitte nochmal die gleiche Menge Plutonium."
"Wie immer"
"Viele Grüße aus Sizilien" (von: international gesuchter Mafiaboss) 
"Danke für die diskrete Entsorgung, die Polizei hat tatsächlich nix gemerkt"
"Starker Stoff"
"Erfolgsprovision" (von: KGB Moskau)
"Pass jetzt aber bitte auf, dass das Finanzamt nix mitbekommt"
"Für einen Freund"
"Ermittlungen tatsächlich eingestellt, danke"
"Eine Hand wäscht die andere" (von: Ku Klux Klan America) 

Das wäre auch alles gar kein Problem gewesen, wenn nicht hinter Orakel in der Schlange am Automaten ein Polizist gestanden hätte.

**Comment by yur-y** [comment]
...oder er zahlt einfach mit Kreditkarte?

Es ist zwar eh unwahrscheinlich, dass er noch ein Konto von der Zeit vor Örz hat (immerhin sind die vier international gesucht, da würde man ein einfaches Bankkonto mal sperren, aber wenn er noch eins hat, kann er auch ne Kreditkarte haben.

Und mal abgesehen davon, dass es krass ist, wie er einfach *gar nicht* von der Polizei verfolgt wird, nachdem Ingrid die Polizisten am Kleiderhaken festgebunden hat.^^

**Comment by yur-y** [comment]
Vorschlag (Veränderungen erwünscht):

Orakel rannte weg. Er sah ein Taxi, sprang hinein und schrie den Fahrer an: »Zum Pentagon! Wie viel macht das?«

Der Fahrer fuhr los und sagte: »23,50.«

»Kann ich mit Kreditkarte bezahlen?«

»Ja, natürlich.« Der Fahrer sah ihn verständnislos an.

Als sie in der Nähe des Pentagons angekommen waren, sah Orakel yury.

»Ey, Fahrer. Anhalten.«

Der Fahrer hielt an und Orakel fiel ein Stein vom Herzen, als das Lesegerät seine Zahlung tatsächlich bestätigte. \textit{Man kann von dieser Seele halten, was man will}, dachte Orakel, {aber sie versteht ihr Geschäft.} Er sprang aus dem Taxi und lief auf yury zu, der neben einem Lkw stand.

**Comment by ToBeFree** [comment]
Haha, total gut! 😄 Diese Fassung geht ja sogar darauf ein, dass die Deutschen klischeemäßig mit Bargeld bezahlen, während die Amerikaner oft ihre Kreditkarte verwenden.

Momentan kein bestimmter Änderungsvorschlag -- nur das "Der Fahrer führ los und sagte" lässt sich eventuell verschönern / ausschmücken.

**Comment by ToBeFree** [comment]
Zur Polizeiverfolgung: Naja, die Polizei kommt halt nicht "automatisch". Die beiden Polizisten können momentan keine Verstärkung herbeirufen.

**Comment by ToBeFree** [comment]
Siehe #561
