### ISSUE TITLE
Erd-Schutzschirm

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#518]
Ich habe die Bedienungsanleitung und eine Umbauanleitung für den großen Schutzschildgenerator an die Mail angehängt. Wenn du die Anleitung befolgst, kannst du mithilfe einiger Steine, etwas Kohle, zwei Aluminiumplatten und neun Litern flüssigem Stickstoff sowie 270 Metern Kupferkabel den Generator so sehr verstärken, dass er einen Schutzschild um die gesamte Erde erzeugt.

[...]

Nach einem Tag hatte Island 200 Liter flüssigen Stickstoff, eine Lkw-Ladung Kieselsteine, zwei Tonnen Steinkohle und 1000 Meter Kupferkabel besorgt. Nun schuldete er vielen Leuten eine Menge Geld, aber das störte ihn momentan wenig. In der Nacht stahl er 200 Aluminiumplatten von einem schlecht gesicherten Betriebshof, und sein Grundstück sah aus wie eine Baustelle.

?

**Comment by ToBeFree** [comment]
Er kauft/klaut eben deutlich mehr, als er braucht. Overkill. :) Nur die Zutaten sind möglicherweise von vorneherein absurd. Der Stickstoff zur Kühlung des Geräts, okay, das machen auch einige Computer-Bastler. Aluminiumplatten? Kupferkabel? Vielleicht werden die Kupferkabel parallel zu bestehenden Kabeln angeschlossen, um eine bessere Stromübertragung zu gewährleisten und eine Überhitzung der Drähte zu vermeiden. Vielleicht dienen die Aluminiumplatten als überdimensionale Kühlrippen -- dafür wird Aluminium tatsächlich eingesetzt. Kohle?! Vielleicht sind da Kohleschleifer drin, die verstärkt oder ersetzt werden müssen. Steine?! Wozu Steine? Alles merkwürdig... 😄 

Ich glaube, das war im Original noch absurder, und ich habe es bereits mit einigermaßen sinnvollen Zutaten umgeschrieben.

**Comment by yur-y** [comment]
Das ist unlogisch, wenn er nur so wenig Zeit hat. Vorschlag: Er braucht auch mehr Zeug, das scheint ohnehin "realistischer" (soweit man das Wort hier verwenden kann) für so einen Riesenschutzschirm.

**Comment by ToBeFree** [comment]
DIe Größe des Planeten im Gegensatz zu einem Raumschiff war mir früher nicht so stark bewusst. Es ist eigentlich der Wahnsinn, dass der Generator das können soll. Die nötige Leistung und die entstehende Wärme, selbst falls das Kernkraftwerk zur Versorgung genügt, müsste eigentlich die ganze Umgebung zum Schmelzen bringen.

Aber gut: Die Äöüzz haben es eben geschafft, das irgendwie so effizient hinzubekommen, dass die Hitze sich im kontrollierbaren Rahmen hält, solange man mit flüssigem Stickstoff kühlt. Und Erfahrung mit Schutzschirmen haben sie auch, also haben sie vielleicht auch Technologie zum Errichten eines planetenweiten Schutzschirms. 

Ja, Island sollte von Anfang an laut Anleitung mehr Zeug brauchen. 😄
