### ISSUE TITLE
T3z38j3 H958a3h

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#519]
Warum verwendet Alfred (oder wer auch immer) eigentlich eine englische Tastatur für die Verschlüsselung einer deutschen Liste?

**Comment by yur-y** [comment]
...und später in einer Notiz dann wieder nicht: g3w8565 e83 R34hopwdz7htwd9e3w...

**Comment by yur-y** [comment]
Ach ja, und ich hatte gerade keine Lust, die ganze zweite Notiz noch mal auf Korrektheit zu überprüfen. Ist die safe?

**Comment by ToBeFree** [comment]
Bist du sicher, dass die Tastatur englisch ist? Der obere linke Nachbar der Taste "h" ist auf einer deutschen Tastatur das "z", deshalb taucht an dritter Stelle ein "z" auf (kein "y"). Ich überprüfe gleich mal die ganzen Buchstaben. Ich glaube aber, das habe ich bereits gemacht. :)

**Comment by yur-y** [comment]
Noch besser, dann ist es gemischt: das "a" im zweiten Wort ;)

**Comment by ToBeFree** [comment]
Das "a" war glücklicherweise der einzige Fehler. :)

Ein Skript zum Entschlüsseln und Verschlüsseln des Geheimtextes befindet sich jetzt im "archive"-Ordner.
