### ISSUE TITLE
Formatierung für Rufen/Schreien: \iashout

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#520]
Ich öffne dafür mal ein Issue, weil es bisher glaube ich nur im Wiki diskutiert wurde.

Also: Derzeitiger Stand ist \uppercase, weil leicht ersetzbar. Ich finde, es gibt gute Argumente sowohl für \textbf (sieht gut aus, wirkt deutlicher und kann gut von Lautsprechern etc. abgegrenzt werden) und \textit (sticht nicht so extrem heraus und stört daher weniger den Lesefluss, ist typografisch daher eine deutlich häufiger gewählte Hervorhebung). Es drängt nicht, weil es nur ein einzelnes Replace ist, aber irgendwann müssen wir uns entscheiden. ;)

**Comment by ToBeFree** [comment]
\uppercase ist clever. Darauf wäre ich als Zwischenlösung nicht gekommen. :)

Ich würde das Issue offen lassen, bis deine Überarbeitung "proofreading" bei 100% angekommen ist. Dann spiele ich wieder am Code herum. :D

**Comment by yur-y** [comment]
Der Moment der Entscheidung naht... Kursiv oder fett, oder eine ganz andere Lösung?

Ich persönlich fände zwar schade, wenn \textit verschiedene "Bedeutungen" hat, aber zu exzessiver Fettdruck ist glaube ich in der Typografie nicht so gern gesehen und sticht dann doch sehr heraus. Von daher wäre ich tendenziell gegen \textbf und für entweder \textit oder eine ganz andere Lösung, bin aber relativ agnostisch, also wenn Du eine starke Meinung dazu hast, nehmen wir die einfach :)

**Comment by ToBeFree** [comment]
Ich stimme dir vollkommen zu und tendiere ebenfalls zu \textit :)

**Comment by ToBeFree** [comment]
Eine Überlegung noch, hinsichtlich der "verschiedenen Bedeutungen": Ich definiere stattdessen "\iashout", sodass die Information nicht verloren geht, was Schreien und was Computersprache ist.

**Comment by ToBeFree** [comment]
`\newcommand{\iashout}{\uppercase}`

**Comment by ToBeFree** [comment]
Gibt automatisch eine Fehlermeldung aus, anstatt ruhig fehlzuschlagen, falls der Befehl bereits existiert.
