### ISSUE TITLE
Was ist gemeint?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#522]
Danach diskutierten die vier bis in die Nacht hinein weiter über den geplanten Pentagon-Einbruch. Sie kamen zu dem Ergebnis, dass ein Einbruch im Fort-Knox-Stil (diesmal dem Lkw) am vielversprechendsten sei.

"diesmal mit einem Lkw"? Verstehe es gerade nicht.

**Comment by ToBeFree** [comment]
Hm, allzu viel Sinn ergibt der Satz auch gar nicht.

Gemeint war eigentlich eine große Aktion mit viel Chaos und Feuer, nur dass dabei ein LKW statt eines Helikopters zum Einsatz kommt. Der Vergleich hinkt: Beim Fort-Knox-Angriff waren viele Helikopter dabei, beim Pentagon-Angriff rast ein einziger LKW auf das Gelände, wodurch vollkommen übertriebene Sicherheitsmaßnahmen eingeleitet werden, welche letztendlich nur den vier Protagonisten zugute kommen.

**Comment by ToBeFree** [comment]
Danach diskutierten die vier bis in die Nacht hinein weiter über den geplanten Pentagon-Einbruch. Sie kamen zu dem Ergebnis, dass ein Ablenkungsmanöver zum unbemerkten Betreten des Gebäudes erforderlich war.

Schließlich hatte Orakel einen Vorschlag. "Wir könnten den LKW einfach in einer großen Explosion mit dem Pentagon kollidieren lassen."

"Klar", antwortete Free. "Wir können das aber auch sein lassen."

"Also, ich finde die Idee gut", sagte Alexandra.

yury blickte auf die Uhr, dann erhob er sich müde von seinem Sessel. "Von mir aus könnt ihr das ganze Pentagon in die Luft sprengen. Gute Nacht."

**Comment by yur-y** [comment]
Ist eingebaut. :)
