### ISSUE TITLE
Wikipedia-Startseite

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#523]
Den Gag mit der Wikipedia-Startseite finde ich nicht schlecht, aber wie passt er zum vorher erwähnten 30minütigen Webdesign?

»Die wacht schon wieder auf«, sagte Orakel und seufzte. »Wir müssen die irgendwie dazu bringen, dass sie sieht, dass es HPW-Industries wirklich gibt. Ich habe eine Idee: Free? Kannst du mir eine Internetseite von HPW-Industries erstellen?«

»Ja, klar. So was mache ich in zehn Minuten!«

Nach einer halben Stunde war die Internetseite fertig, und das keine Minute zu früh, denn die alte Frau wachte gerade wieder auf. Schnell setzten sich alle neben die alte Frau und versuchten, so besorgt wie möglich zu gucken. Dann richtete sich die Frau langsam auf.

[...]

»Geht doch«, flüsterte yury. »Du kannst die Wikipedia-Startseite jetzt schließen.«

**Comment by ToBeFree** [comment]
Die einzige Möglichkeit, die damit nicht kollidiert, ist, dass Free den HTML-Quelltext der Wikipedia-Startseite lokal bearbeitet, um Aktienkurse und Firmendaten anstelle des normalen Inhalts anzuzeigen. Das macht aber irgendwie den Witz kaputt.

**Comment by ToBeFree** [comment]
Wie wäre es mit: "Du kannst die Wikipedia-Spielwiese jetzt schließen"?

Vgl. https://de.wikipedia.org/wiki/Wikipedia:Spielwiese
https://de.wikipedia.org/wiki/Wikipedia:Sandkasten (ist eine Weiterleitung)
https://en.wikipedia.org/wiki/Wikipedia:Sandbox
