### ISSUE TITLE
»Dönt-get-enrägd«-Brettspiel

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#524]
Eher "Lüdö" zwecks Korrektheit, oder lassen, weil es lustig klingt?

**Comment by ToBeFree** [comment]
Achso, das wusste ich gar nicht.

Hm.

Der Örz-Bezug macht an der Stelle ja eigentlich keinen Sinn. "Ludo"?

**Comment by yur-y** [comment]
Finde den Örz-Bezug aber ganz lustig. Ich lasse jetzt erst mal "Lüdö".
