### ISSUE TITLE
100% erreicht? Letzte Schritte

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#527]
* Stelle sicher, dass diese Änderungen wirklich auf GitHub gelandet sind: Siehst du deinen "100%"-Commit unter diesem Link: https://github.com/yur-y/ia-trilogy/commits/master   dann hat es funktioniert.
* Klicke hier: https://github.com/yur-y/ia-trilogy/pull/new/master  Einfach abschicken, Standardeinstellungen stimmen. Um das dadurch geöffnete Pull Request kümmere ich mich gerne, du darfst aber auch selbst auf "Merge" klicken. 
* Klicke hier: https://github.com/yur-y/ia-trilogy/pull/1   Diesen Schritt kann ich nicht für dich machen, denn er findet in deinem Repository statt. Einfach unten auf der Seite den grünen "Merge"-Knopf anklicken, dann bestätigen. Ein Kommentar ist nicht erforderlich, der Standardtitel ist okay.
* In GitHub Desktop: Klicke den "Refresh"-Knopf (bzw Push-/Pull-Knopf) , mit dem du zuletzt deine "100%" hochgeladen hast. Klicke gegebenfalls ein zweites Mal, um die neu gefundenen Änderungen dann wirklich zu "pull"en. Sobald ein längerer Download-Prozess angestoßen wurde, ist dieser Schritt erledigt. Warte noch, bis der Download abgeschlossen ist.
* Schließe GitHub Desktop. Der Ordner "ia-trilogy", in dem bis dahin das Repository gespeichert war, muss jetzt archiviert werden. Ich persönlich würde ihn mit 7zip auf "Ultra"-Kompressionsstufe in eine Datei verpacken. Du kannst aber jedes Mittel deiner Wahl hierfür verwenden. Beachte nur, dass der Ordner für eine klassische zip-Datei zu groß ist (über 4GB)! Das Erstellen einer Archivdatei verhindert ein ansonsten gar nicht so unwahrscheinliches versehentliches Arbeiten im falschen Ordner. Wenn du ihn einfach nur umbenennst, taucht er wahrscheinlich sogar noch in deinen "häufig verwendeten Ordnern" auf.
* Lösche den Originalordner, behalte nur die Archivdatei. Theoretisch solltest du sie nie benötigen, aber man weiß nie, welche unerwarteten Katastrophen auftreten. Wichtig ist, dass der Originalordner wirklich nicht mehr dort existiert, wo er vorher war.
* Schreibe bitte hier einen Kommentar, damit ich weiß, dass du hier angekommen bist. Warte mit dem nächsten Schritt, bis ich Bescheid sage – ich erstelle Kopien auf freiwuppertal.de/git und auf meiner Festplatte. 
* Sobald ich die Sicherungen erstellt habe, die eigentlich auch vollkommen überflüssig sein sollten, fahre fort mit:
* Lösche deine Fork auf GitHub: Scrolle auf der folgenden Seite ganz nach unten (roter Bereich). Klicke auf "Delete Repository" (nicht auf "archive", auch wenn es zunächst sinnvoller / weniger schädlich klingen mag). Du wirst dann darum gebeten, den Repository-Namen zur Sicherheit nochmal einzutippen. Tippe zu deiner eigenen Sicherheit exakt Folgendes ein: "yur-y/ia-trilogy". So kannst du sicher sein, dass es sich nicht um das Hauptrepository handelt, sondern um deine Fork. Ersteres könntest du hoffentlich sowieso nicht löschen; die Eingabe deines Benutzernamens gibt aber dir persönlich die Sicherheit, das Richtige zu tun. 
* Ab hier heißt es: untätig warten, bis ich die Aufräumaktion beendet habe. Ich denke, ich schaffe das an diesem Wochenende, falls du heute Nacht die 100% pusht. :)

**Comment by yur-y** [comment]
Ich werde wahrscheinlich nachher noch die "100%" pushen. Disclaimer: An einigen Stellen habe ich notwendige Änderungen noch nicht durchgeführt, weil sie in dem Moment zu aufwendig schienen. Für die entsprechenden Stellen sollte aber jeweils noch ein Issue offen sein (und es gibt ja auch immerhin noch 130 davon).
Ansonsten bin ich jetzt erst mal 3 Wochen im Urlaub - danach kann ich gerne bei einer finalen Bearbeitung helfen. Hast Du einen Vorschlag für ein Vorgehen zur finalen Bearbeitung?

**Comment by yur-y** [comment]
Ah, ich habe gerade erst den Thread zur Timeline gesehen. Das klingt so weit gut, finde ich :)
Was hältst Du von der Idee, für den Arbeitsschritt "Letzter Schliff" ein FinalEditBootcamp zu machen, in dem man ca. einen Tag lang noch mal alles liest und gemeinsam an den Stellen arbeitet, die noch letzte Änderungen brauchen?

**Comment by ToBeFree** [comment]
Sicherungen sind erstellt, die Fork kann gelöscht werden. :)

Zur Größe des komprimierten Archivs: Ja, da ist der ".git"-Ordner mit enthalten, der bereits komprimiert ist. Um diesen Ordner zu verkleinern, muss man an der Versionsgeschichte herumbasteln. Das mache ich als Abschluss des Aufräumvorgangs.

**Comment by ToBeFree** [comment]
Zum FinalEditBootcamp, gerne! Hätte ich spontan als "Sprint" bezeichnet. 😄 

Gerne einfach ins Wiki einbauen, die Seite ist ja frei bearbeitbar. Stichpunkt genügt, kann man nachher weiter ausführen.

**Comment by yur-y** [comment]
Fork müsste jetzt gelöscht sein. Bis in 3 Wochen dann! :)

**Comment by ToBeFree** [comment]
https://www.freiwuppertal.de/ia-autoren/mw/index.php?title=Timeline&diff=465&oldid=455
