### ISSUE TITLE
"HPW-Industries" oder "HPW Industries"?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#528]

**Comment by ToBeFree** [comment]
Der Bindestrich wirkt im Englischen wahrscheinlich merkwürdig.

"HPW Industries"

**Comment by ToBeFree** [comment]
Mit Tilde (~) gelöst, damit kein Umbruch entsteht. Ich hoffe, das gibt keine Probleme mit überlangen Zeilen. Ansonsten einfach die Tilde löschen.
