### ISSUE TITLE
"Lkw", "Heli"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#529]
Wenn wir das Wort verwenden, dann "Lkw", nicht "LKW" (vom Duden empfohlen und derzeit so umgesetzt).

Ansonsten möglichst oft in "Lastwagen"/"Laster" umwandeln und "Heli" in "Hubschrauber"/"Helikopter". Das passt aber nicht überall (vor allem wegen Wortwiederholung), in diesen Fällen können die Abkürzungen stehen bleiben.

**Comment by ToBeFree** [comment]
"Lkw" sieht gut aus. Ich wusste nur nicht, dass man das so schreiben darf (oder sogar soll). 👍 

"Lastwagen" ist auch gut.

"Laster" sollten wir vermeiden; es ist ein Wort mit vollkommen anderer Bedeutung außerhalb der Umgangssprache.

"Heli" ist im Erzähltext schlecht, weil umgangssprachlich (laut Duden: _"schweizerisch, sonst umgangssprachlich"_). In wörtlicher Rede wäre es vielleicht akzeptabel, aber auch dort verzichten wir ja weitgehend auf Umgangssprache.

**Comment by ToBeFree** [comment]
Lkw ✔️

**Comment by ToBeFree** [comment]
"Tanklaster" akzeptiert ✔️

**Comment by ToBeFree** [comment]
"Heli" als Wiederholungsvermeidung nach "Helikopter" für unschön befunden. Wiederholung entfernt, "Heli" durch "Helikopter" ersetzt. ✔️ Siehe #546

**Comment by ToBeFree** [comment]
»Nicht das. Wie du den Heli gerettet hast«, sagte yury.

akzeptiert

**Comment by ToBeFree** [comment]
»Ach so«, meinte Orakel, »ich wollte hupen, damit sich die Polizisten erschrecken und dann abstürzen. Dabei habe ich aus Versehen den falschen Knopf gedrückt und der Heli stürzte nach unten. Erschrocken dachte ich, jetzt stürzen wir ab. Aber ich habe rechtzeitig den Motor wieder gestartet.«

Gleiche Begründung, außerdem redet hier Orakel.

**Comment by ToBeFree** [comment]
_Aus einem Helikopter hörte Orakel einen Mann sprechen, der offenbar telefonierte. Orakel versteckte sich in der Nähe und lauschte:_

_»… Wolfgang. Die haben uns noch nicht erkannt. Ja, sie hat mich gefragt, ob ich einen Heli fliegen könnte. Irgendwo in der Nähe war dieser komische yumi oder yogi, oder wie der Typ heißt. Den Verfressenen und den Technik-Freak konnte ich nicht entdecken. Die haben hier ganz schön viele Helis. Den genauen Standort kann ich dir nicht sagen. Wir sind am Arsch der Welt. Ich rufe dich morgen wieder an.«_

Marcor Schreiner darf das; er sagt auch "Arsch" im gleichen Gespräch.

**Comment by ToBeFree** [comment]
_»Oh, guten Tag Frau Fischer, entschuldigen Sie, dass ich so spät noch anrufe, aber ist der Wolfgang da? \uppercase{Der Wolfgang. Ob der da ist.} Mein Name ist Marcor Schreiner. Marcor Schreiner. \uppercase{Marcor Schreiner.} Nein, ich will keine Kekse, ich möchte mit dem Wolfgang sprechen. Danke, tschüss!~– Hi Wolfgang. Deine Mutter ist total schwerhörig, ich musste dreimal meinen Namen wiederholen. Warum wohnst du noch mit 45 Jahren bei deiner Mutter? Ach, egal. Hör mal, irgendeiner von diesen dummen Freaks hat meine Familienpackung Nitro-TNB geklaut. Ich glaube, dass es der Verfressene war.~– Wie ich darauf komme? Der Laptop von diesem Technik-Freak ist kaputt, der ist damit beschäftigt, den zu reparieren. Dieser komische yumi oder wie der Typ heißt, ist viel zu sehr mit irgendwelchen Angriffsplanungen beschäftigt, um etwas zu kapieren, also kann es nur der Verfressene gewesen sein. Der dachte bestimmt, dass das Kekse wären. Übrigens bin ich gestern in den Heli von denen eingebrochen und habe dort eine Zeitbombe installiert. Um sie zu deaktivieren, ist folgender Code fällig:«_

Marcor Schreiner darf das. :)

**Comment by ToBeFree** [comment]
_»Ihr wolltet mich also belauschen«, stellte er fest. Dann verschwand sein Lächeln. »\uppercase{Alle in den Heli! Sofort, oder es knallt!}«_

Marcor Schreiner darf das.

**Comment by ToBeFree** [comment]
**Orakel hatte sich zurückgelehnt und aß gerade eine Pizza, als Frees Helikopter mit offener Tür von oben an ihm vorbeiflog. Da offenbar irgendetwas nicht in Ordnung war, nahm Orakel die Verfolgung auf. Als die beiden wieder auf gleicher Höhe waren, drückte Orakel einen Knopf, stieg aus dem Pilotensitz, lief zur Tür, öffnete sie, nahm Anlauf und sprang in Frees Heli. Dort angekommen, stellte er Free zur Rede.**

Der Erzähler darf das **nicht.** 🚩

**Comment by ToBeFree** [comment]
Neue Fassung:

_Orakel hatte sich zurückgelehnt und aß gerade eine Pizza, als Frees Helikopter mit offener Tür von oben an ihm vorbeiflog. Da offenbar irgendetwas nicht in Ordnung war, nahm Orakel die Verfolgung auf. Als die beiden wieder auf gleicher Höhe waren, drückte Orakel einen Knopf, stieg aus dem Pilotensitz, lief zur Tür, öffnete sie, nahm Anlauf **und sprang über den Abgrund durch die beiden offenen Türen.** Dort angekommen, stellte er Free zur Rede._

**Comment by ToBeFree** [comment]
_Alexandra starrte verdutzt auf ihr Funkgerät. Dann funkte sie den Hubschrauber erneut an.

»Äh, Orakel, wenn das dein Heli ist, was ist dann mit Free passiert?«_

Als wörtliche Rede in Paniksituation akzeptiert.

**Comment by ToBeFree** [comment]
Oh, da ist ja noch etwas:

_»Nichts wie weg, die werden gleich schießen, wenn Mountains Helikopter kommt und sie begreifen, dass dieser Heli hier nur unserer sein kann!«, sagte Free zu dem Piloten. Dieser ließ den Helikopter nun schnell wegfliegen, in Richtung der Flotte._

**Comment by ToBeFree** [comment]
_»Wow! Ich habe gerade einen neuen Hubschrauber im Internet gefunden«, berichtete er den anderen._

_Free blieb eine Weintraube im Hals stecken. »Was?«, keuchte er. »Du möchtest schon wieder einen Helikopter stehlen?«_

_»Ja«, sagte yury begeistert und deutete mit dem Finger auf den Bildschirm. »Das ist eine Boeing CH-47F. 3630 Kilowatt pro Rotor, mit volldigitaler Triebwerksregelung. 290 Kilometer pro Stunde bei über zehn Tonnen Nutzlast. Den gibt es aber nur für ausgewählte Kunden bei Spezialhändlern.«_

_»Ach, und du glaubst, dass die uns den Heli geben, wenn wir da einfach so hinspaziert kommen und ganz lieb fragen?«, fragte Free._

_yury wollte gerade antworten, als Alexandra mit einem Tabellenblatt angelaufen kam und das Gespräch unterbrach._


erstmal akzeptiert, aber da ist noch ein anderer Fehler. "Spezialhändler"? Das Ding wird wahrscheinlich direkt von Boeing geliefert, nehme ich mal an.

**Comment by ToBeFree** [comment]
"Truck" geht manchmal auch:
