### ISSUE TITLE
S. 65/66: Bleiben "[...]" und "#hust#"?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#530]
Die Stilentscheidung kannst Du gerne treffen und das hier dann schließen.

**Comment by ToBeFree** [comment]
Auslassungszeichen sind in Zitaten möglicherweise unvermeidlich (mal gucken, wo das auftaucht). In wörtlicher Rede wäre es aber ungeeignet, weil es gar nicht gesprochen werden kann.

Das "#hust#" sollte weg, denke ich. Ich gucke nachher, wo es vorkommt.
