### ISSUE TITLE
S. 208: Stilfrage

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#532]
"Dass das Forschungsraumschiff an diesem Ort gelandet war, erwies sich als glücklicher Zufall; mit den letzten Atemzügen hatte der fliegende Stahlklotz ein verstecktes Paradies entdeckt, bevor er brennend zugrunde gegangen war."

Ich persönlich finde die Szene ein wenig zu metaphorisch aufgeladen, würde die Entscheidung aber Dir überlassen.

**Comment by ToBeFree** [comment]
Ja, stimmt, das ist zu pathetisch.

**Comment by ToBeFree** [comment]
Hm.

Ach was. Behalten. Schadet nicht. :)
