### ISSUE TITLE
1 Örztempz = (thermodynamische Temperatur des Tripelpunktes des Wassers)/(7³)

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#536]
_Eine moderne Klimaanlage war in jedem Raum einzeln einstellbar und stellte innerhalb weniger Minuten die Wunschtemperatur von **147 bis 343** Örztempz her. Das entsprach umgerechnet ungefähr -20 bis +40 Grad Celsius._

(vorher "**-14 bis +28** Örztempz")

Gibt es auch in dieser Version negative Örztempz? Die große Differenz (343-147 > 60) und die niedrige "147"-Zahl scheinen das zu implizieren.

Ich würde vorschlagen, bei dieser Gelegenheit auf eine absolute Temperaturskala umzustellen, die bei Null Kelvin beginnt. Das hat für wissenschaftliche Rechnungen viele Vorteile und passt vielleicht auch besser zu den Äöüzz.

**Comment by yur-y** [comment]
Auf jeden Fall wäre ich auch für eine absolute Skala, aber was meinst Du - sollte sie die gleichen Gradschritte haben wie auf der Erde (nur halt im Siebenersystem), um einen weiteren Anknüpfungspunkt zu haben, oder eher nicht, weil wir nicht wissen, ob Wasser für die Äöüzz einen ähnlichen Stellenwert hat? (Andererseits gibt's im Supermarkt halt auch "Bänänäs & Äpölz" zu kaufen.^^) Ich glaube, vorher hatte ich nämlich zur zweiten Variante tendiert und jetzt eher zur ersten.

**Comment by ToBeFree** [comment]
Die Überlegung zum Wasser gefällt mir, aber ich würde sagen, da die Lebewesen, die Lebensmittel und die Technologie (Wasserstoff-Antrieb) alle sehr wasserabhängig sind, ist es durchaus nachvollziehbar, wenn ein Bezug zu Wasser vorhanden ist.

Bei "Kelvin" ist das aber gar nicht der Fall (?)

Aber du hast mich auf eine Idee gebracht. Was hältst du von so etwas:

* 0 Kelvin = 0 Örztempz (absoluter Nullpunkt)
* 273,16 Kelvin = 7^3 Örztempz = 343 Örztempz (Tripelpunkt von Wasser)

Das wäre dann eine lineare Abhängigkeit, eine einfache Rechenformel ließe sich konstruieren, und der Celsius-Bezug ist nur noch indirekt vorhanden.

**Comment by yur-y** [comment]
> Bei "Kelvin" ist das aber gar nicht der Fall (?)

Na ja, der Nullpunkt der Skala ist fix, aber man könnte ja einen beliebigen Gradschritt wählen. Da hat man den der Celsius-Skala genommen, der ja historisch halt 1/100 des Abstands zwischen Schmelz- und Siedepunkt von Wasser bei "normalem Luftdruck" darstellt. Aus der Definition von Kelvin hat man das aber natürlich formell rausgenommen, indem man einfach die Zahl 273,16 aus dem Hut gezaubert hat. Aber das könnte ja auch jede andere sein, und damit sind unendlich viele sinnvolle absolute Temperaturskalen vorstellbar, wenn man nicht den Bezug auf Wasser im Hintergrund hat.

That said, finde ich Deinen Vorschlag gut. ;)

**Comment by ToBeFree** [comment]
😄

**Comment by ToBeFree** [comment]
(343/273.16)*(273.15+**40**) = 393.21
(343/273.16)*(273.15+**-10**) = 393.21

**Comment by ToBeFree** [comment]
315 base 10 = 630 base 7  (rund)
 392 base 10 = 1100 base 7 (rund)
