### ISSUE TITLE
Meta: Ersetzen, falls es irgendwo falsch beschrieben wird: Der Quelltext der Überarbeitung ist nicht von 2014, sondern 2012.

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#539]
Die Metadaten der alten PDFs und ODTs waren sehr aufschlussreich, und die werde ich auch als historische Dokumente so belassen: 

Erstelldatum: 10. Februar 2012, 22:53:36 Uhr
Letzte Änderung: 23. Oktober 2018, 08:46:33

Gesamte "Bearbeitungszeit": 116 Stunden, 12 Minuten, 45 Sekunden
(wahrscheinlich war das Dokument oft einfach in Abwesenheit auf einem gesperrten Computer geöffnet.)

Das 2014er PDF-Dokument habe ich nachträglich spontan aus dem 2012er Quelltext für einen Klassenkameraden generiert.

**Comment by yur-y** [comment]
Der Originaltext ist sogar von 2010 bis 2011 oder 2012, wenn ich mich richtig erinnere! Das müsste doch auch im Forum erkennbar sein?

**Comment by ToBeFree** [comment]
Ich habe im IA1-Roman und im IA1-Bonusband keinen Hinweis mehr auf "2014" gefunden.
