### ISSUE TITLE
Konrad Irbys neue Rede bitte auf grobe Fehler überprüfen

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#560]
#559 

Vorgenommene Änderungen:

* https://github.com/InfiniteAdventures/ia-trilogy/commit/8d31e7013b0a7b8ca84602beccae1c640a7a8b6e (`https://github.com/InfiniteAdventures/ia-trilogy/commit/8d31e7013b0a7b8ca84602beccae1c640a7a8b6e`)
* https://github.com/InfiniteAdventures/ia-trilogy/commit/3630a0ce68b83b6904376f75ba652b36ee12a0e6 (`https://github.com/InfiniteAdventures/ia-trilogy/commit/3630a0ce68b83b6904376f75ba652b36ee12a0e6`) ("ihr" und "euch" -> "Sie")
* https://github.com/InfiniteAdventures/ia-trilogy/commit/372a053d50197fd17aaaf8a717cb4508044f860b (`https://github.com/InfiniteAdventures/ia-trilogy/commit/372a053d50197fd17aaaf8a717cb4508044f860b`) ("dieses Planetens" -> "dieses Planeten")

-----

Auf einmal kam ein uggy an die Zelle. »\uppercase{Gewonnen!}«, rief Orakel. 

»Psst, sei ruhig«, zischte yury.

Plötzlich legte sich der uggy flach auf den Boden, woraufhin Orakel einen Lachanfall bekam. Wenige Sekunden später sahen sie den Grund das Verhalten des uggys: Konrad Irby tauchte im Gang auf. Anscheinend hatten die uggys wirklich großen Respekt vor ihm.

Orakel deutete mit ausgestrecktem Zeigefinger auf ihn und rief: »Schaut mal, da ist dieser komische Konrad!«

Konrad rief zurück: »Ey, Sie Fresssack. Mein Handy ist weg!«

Orakel entgegnete: »So werde ich aber gern begrüßt. Ach ja, das ist ganz schön doof, wenn einem das Handy gestohlen wurde, ich kenn mich damit aus.«

»Dir wurde mal dein Handy gestohlen?«, fragte Alexandra.

»Psst, ich versuche mit Konrad eine soziale Bindung aufzubauen!«

Alexandra schlug sich mit der Hand gegen die Stirn. Auch Irby war wenig begeistert.

»Ich brauche keine soziale Bindung. Spielen Sie hier nicht den Hobbypsychologen, dazu mangelt es Ihnen an Kompetenz.«

»War nicht so gemeint. Was willst du denn dann von uns?«

»Könnten Sie mich bitte siezen? Wir sind hier in einer höflichen Umgebung!«

»Von mir aus. Wie lautet Ihr Anliegen?«

»Ich möchte Ihnen meine Geschichte erzählen, weil mir sonst niemand zuhört. Mein Name ist Konrad Irby. Der echte Konrad Irby. Das Original. Wie Ihnen sicherlich bereits aufgefallen ist, bin ich bin der totale Herrscher dieses Planeten. Ich habe ugghy gekauft, von meinem eigenen Vermögen. Damals waren alle ziemlich überrascht, dass das legal ist. Ich habe die Meisterleistung vollbracht, Lücken in uggy-Gesetzen zu finden und das ganze Sternenreich von Grund auf umzukrempeln. Mir gehört das Sonnenlicht, das Sie blendet, die Luft, die Sie atmen, und der Boden, auf dem Sie stehen. Einen ganzen Planeten nenne ich mein Eigentum. Ich habe eine raumfahrende Polizeiarmee aufgebaut und werde von allen Verbrechern der Galaxis gefürchtet. Durch mein Wirken wird Recht und Ordnung in einem Raum durchgesetzt, der man zuvor für inhärent anarchisch gehalten hat. Ich bin in die Geschichte eingegangen. Mein Name ist schon heute eine Legende. Man wird sich für Jahrhunderte an mich erinnern…«

Orakel gähnte. Auf diese langweilige Unterhaltung hatte er keine Lust mehr und schwieg. Irby sah frustriert ein, dass man mit Orakel nicht mehr reden konnte und verließ die Zelle mit dem Worten »ughfu handu nuddu« (»sie haben das handy auch nicht«).

**Comment by ToBeFree** [comment]
Ja, da ist noch etwas, "werden Recht und Ordnung" statt "wird Recht und Ordnung"

**Comment by yur-y** [comment]
Da bin ich mir in diesem Fall nicht so sicher, weil es eine feststehende Wendung ist? Ich glaube, "wird" klingt in meinen Ohren besser.

**Comment by ToBeFree** [comment]
ok :)

**Comment by ToBeFree** [comment]
Na, ich weiß noch nicht. Im Duden finde ich nur "Law and Order"; "werden" wäre auf jeden Fall nicht falsch.

**Comment by ToBeFree** [comment]
oh, "der man zuvor" -> "den man zuvor"

**Comment by yur-y** [comment]
Ups, muss ich übersehen haben. Ich finde immer noch, dass es eine Wendung ist, habe aber kein größeres Problem mit "werden". :)

**Comment by ToBeFree** [comment]
ok, dann "werden" :) Falls es gleich noch drin ist, übernehme ich die Änderung
