### ISSUE TITLE
#411: Neue Textpassagen bitte auf grobe Fehler überprüfen

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#563]
#411: Neue Textpassagen bitte auf grobe Fehler überprüfen:

https://github.com/InfiniteAdventures/ia-trilogy/commit/637649ee76c4cf90f14a91b26b643e5e51da054f (`https://github.com/InfiniteAdventures/ia-trilogy/commit/637649ee76c4cf90f14a91b26b643e5e51da054f`)
https://github.com/InfiniteAdventures/ia-trilogy/commit/01596d51ba155ea34fcb28e912a14594b1bc9abe (`https://github.com/InfiniteAdventures/ia-trilogy/commit/01596d51ba155ea34fcb28e912a14594b1bc9abe`)
https://github.com/InfiniteAdventures/ia-trilogy/commit/3e8e4c91cdd23ed7fe04be6013bb5ab88b3e73b2 (`https://github.com/InfiniteAdventures/ia-trilogy/commit/3e8e4c91cdd23ed7fe04be6013bb5ab88b3e73b2`)

**Comment by yur-y** [comment]
Ich bin immer noch verwirrt vom neuen Arbeitsmodus, sorry. Bei mir im Dokument habe ich mehr Änderungen als die drei obigen Commits, insbesondere kommt oben noch ein "XXXXX" vor, das aber bereits ersetzt wurde. Ich habe mir bei den anderen Issues bisher immer nur die verlinkten Differenz-Übersichten angeschaut, aber anscheinend hat sich ja (teilweise?) noch mehr verändert, was ich noch mal lesen müsste?

**Comment by ToBeFree** [comment]
@yur-y Hi :D Das sollte selten der Fall sein; ich habe dann nachträglich, teilweise Wochen später, Fehler bemerkt und noch behoben, ohne den Unterschied-Link hier einzufügen. Ich versuche aber, das zu vermeiden, und es sollte die Ausnahme sein.
