### ISSUE TITLE
Kommentar: Die öffentliche Magnetschwebebahn ist eine schöne Idee

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#564]
Gefällt mir sehr. :smiley: :+1:

**Comment by yur-y** [comment]
Ich war mir nicht sicher, ob öffentliche Verkehrsmittel (wenn auch immerhin privat betrieben) in das Gesellschaftssystem passen und ob eine Magnetschwebebahn auf Örz nicht zu "antiquiert" ist. Aber wenn es Dir gefällt, bleibt es drin :)
