### ISSUE TITLE
Vorschlag für Veröffentlichungsdatum: 1. April 2019

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#575]
Eine Tradition der Schachburg ist das Veröffentlichen eines Aprilscherzes oder einer überraschenden echten Neuigkeit am 1. April. Die Forenbenutzer wissen nie, ob es sich wirklich um einen Aprilscherz handelt. Außerdem ist der 1. April ein gutes Datum für die Veröffentlichung eines vollkommen verrückten Romans, und das Datum kann man sich auch Jahre später noch merken.

"Die Infinite Adventures wurden am 1. April 2019 veröffentlicht" -- das bleibt im Kopf. 😃

Außerdem muss die Veröffentlichung vom Bonusband, vom Soundtrack, vielleicht sogar von der Soundtrack-CD, koordiniert am gleichen Tag stattfinden, und der Probedruck eines Buches dauert möglicherweise mehrere Wochen. Es ist sinnvoll, ein Datum zu wählen, das ohne enormen Stress ziemlich sicher eingehalten werden kann. Der 1. April gefällt mir sehr. Ich hätte zwar mit einer früheren Veröffentlichung gerechnet, aber das neue Datum ist deutlich realistischer als "2018". Es verhindert zudem, dass wir das Datum ständig mit neuen Entschuldigungen verschieben müssen.

**Comment by ToBeFree** [comment]
Irgendwann 2019, kein Stress.

**Comment by yur-y** [comment]
Approved.
