### ISSUE TITLE
Bitte auf grobe Fehler überprüfen: Goldbarren und Südafrika

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#582]
https://github.com/InfiniteAdventures/ia-trilogy/commit/c68bb205ac374a487cf6eee0fdd528737736bcdc (`https://github.com/InfiniteAdventures/ia-trilogy/commit/c68bb205ac374a487cf6eee0fdd528737736bcdc`)

https://github.com/InfiniteAdventures/ia-trilogy/commit/62ad0d5b2983fecc4d39fffeef3f32c4c5704639 (`https://github.com/InfiniteAdventures/ia-trilogy/commit/62ad0d5b2983fecc4d39fffeef3f32c4c5704639`)

Siehe auch #388 

Danke :)

**Comment by ToBeFree** [comment]
"eintausend", damit im Gegensatz zu "Tausend" keine Großschreibung vom Duden empfohlen wird. Die passt dort nämlich nicht hinein bzw. wirkt verwirrend.

**Comment by yur-y** [comment]
Wieso sollte dort Großschreibung empfohlen sein? Als Zahlwort wird doch "tausend" kleingeschrieben?

Es gibt noch eine weitere Stelle in dieser Szene, bei der derzeit "tausend Rand" steht (was meiner Meinung nach richtig wäre, aber auf jeden Fall sollte es einheitlich sein).

**Comment by ToBeFree** [comment]
Oh, stimmt, danke. Ich hatte den Duden-Eintrag zu "Tausend" falsch verstanden. Ich ersetze "eintausend" wieder durch "tausend".
