### ISSUE TITLE
Super-Diff

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#583]
Mal sehen, ob ich das schaffe, und ob das Ergebnis brauchbar ist. Ich erstelle einen Commit, der alle Dateien auf den Stand vor der "gemeinsamen Überarbeitung" bringt, und mache diesen dann rückgängig. Das Ergebnis müsste eine Art "Super-Diff" mit allen bisherigen Änderungen sein.

**Comment by ToBeFree** [comment]
Hat funktioniert! Möglicherweise möchtest du GitHub Desktop verwenden, um in der "History" etwas bequemeres als den Internetbrowser zum Stöbern zu nutzen.

https://github.com/InfiniteAdventures/ia-trilogy/commit/75a83b38d654a5508e3832efb449ae89b3fdc2cb (`https://github.com/InfiniteAdventures/ia-trilogy/commit/75a83b38d654a5508e3832efb449ae89b3fdc2cb`)

:slightly_smiling_face:

**Comment by yur-y** [comment]
Habe nun alles gelesen und nur eine wenige Änderungen vorgenommen, vielleicht kannst Du noch kurz drüberschauen :)

**Comment by ToBeFree** [comment]
Habe deine Änderungen mit gleichzeitigen Änderungen von mir vereinigt. 😄 

Eine Frage wegen "Viel Glück" habe ich in #586 beschrieben.
