### ISSUE TITLE
niansa über Veröffentlichung informieren // Der recovery modus...

### ISSUE THREAD

**Issue by niansa** [InfiniteAdventures/ia-trilogy#585]
Recht weit zu anfang, in kapitel 8, steht, das yury an an frees computer gekommen ist, da free den recovery modus nicht raus genommen hat. Aber: man kommt auch (z.B. zum passwort ändern) an eine root shell, indem man im grub auf dem haupteintrag E drückt und als kernel parameter init=/bin/bash angibt und bootet. Dagegen hilft setzen eines passwortes für grub... ;)

**Comment by ToBeFree** [comment]
Huch, willkommen bei uns, @niansa 😄 Schön, dass tatsächlich jemand die Geschichte liest. Darf ich fragen, wie du darauf gestoßen bist?

Nette Idee mit dem Kernel-Parameter, kannte ich noch nicht. Danke für den Vorschlag! 🙂

**Comment by niansa** [comment]
@ToBeFree klar, darfst du. :) Es ist etwas kompliziert, aber: ich habe auf der webseite mit der Supertux Musik versehentlich auf einen Link geklickt. So landete ich auf deiner Webseite. Ich fand sie interressant und guckte mich etwas um, bis ich die Seite mit der Geschichte gefunden habe. Ich konnte mir auf grund von irgendeinem bug im Webbrowser das PDF nicht angucken und nicht runterladen. Mit wget hat es dann geklappt. Nachdem ich es angelesen hatte, war ich so begeistert, dass ich es auf meinem E-Reader runtergeladen habe. Und, alle, denen ich teile der Geschichte vorgelesen habe, waren begeistert! ;)

**Comment by ToBeFree** [comment]
@niansa Haha, wie genial. Über Wansti's Musikseite. 😄 

Vielen lieben Dank für das Feedback! Das Buch erscheint hoffentlich am 1. April 2019. Ich pinge dich dann auf GitHub an -- hoffe zumindest, dass ich daran denke. Ich verschiebe das Issue in offener Form in das "Veröffentlichungs"-Projekt und benenne mal den Titel um.

**Comment by ToBeFree** [comment]
Wegen des ursprünglichen Vorschlags: Ich befürchte, die Szene bleibt unverändert, denn sonst müssen wir uns unerwartet auch noch Gedanken über die Namensnennung und das Copyright des fertigen Buches machen. Jeder Vorschlag ist aber willkommen, und in diesem Fall habe ich zumindest etwas gelernt. 🙂

**Comment by niansa** [comment]
Oh okay. Aber stimmt, macht Sinn.

**Comment by niansa** [comment]
Danke :smiley:

**Comment by ToBeFree** [comment]
Gerne; danke auch für den Hinweis auf den defekten Link. Ich habe schon manchmal erlebt, dass GitHub "rohe" Dateien manchmal nur als Bruchstücke ausliefert. Bei Musikdateien ist es besonders schlimm.

Ich habe den Link jetzt ersetzt: https://www.freiwuppertal.de/0-infiniteadventures-current.pdf

Die Datei werde ich regelmäßig aktualisieren und dann hoffentlich im April 2019 durch den "fertigen" Link ersetzen.

**Comment by ToBeFree** [comment]
@niansa kannst du mir deine Post-Adresse an tobias@freiwuppertal.de schicken? Der Bonusband kommt möglicherweise erst später raus, aber das Hauptbuch ist fertig. Du kannst es vermutlich sogar vor dem 1. April erhalten.

Am E-Book arbeite ich gerade. Das HTML ist bis auf die Bilder fertig, siehe aktuelle Commits.

**Comment by niansa** [comment]
Entschuldige bitte die späte Antwort, ich werde es baldmöglichst machen!

**Comment by niansa** [comment]
@ToBeFree E-Mail ist verschickt, sollte angekommen sein. :100:

**Comment by ToBeFree** [comment]
Oh! Gut, dass du nochmal Bescheid gesagt hast. Das ist bei Gmail im
Spamordner gelandet. Ich gucke mir gleich die Kopfzeilen an und schreibe,
woran es gelegen haben könnte.

Kann hier geschlossen werden.

**Comment by ToBeFree** [comment]
Antwort gesendet, Adresse notiert. Viel Freude beim Lesen :)

**Comment by niansa** [comment]
Danke.

**Comment by niansa** [comment]
Buch ist angekommen, eine E-Mail hast du auch bekommen. Auch hier nochmal vielen Dank. 🙂

**Comment by ToBeFree** [comment]
Gerne :)

**Comment by ToBeFree** [comment]
Gerne, danke für die Benachrichtigung. :)
