### ISSUE TITLE
Viel Glück [Komma?] Free

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#586]
Nach "Viele Grüße", "Mit freundlichen Grüßen" etc. kommt kein Komma; sollen wir das nicht konsequent auch für diese selbstgebastelte "Viel Glück"-Grußformel anwenden?

**Comment by yur-y** [comment]
Ich hatte es gerade eingefügt, weil das ja keine Standard-Grußformel ist und es für mich so intuitiver klingt. (Oder sogar mit Ausrufezeichen?) Ich hänge aber nicht an dem Komma.

**Comment by ToBeFree** [comment]
Ein Ausrufezeichen löst das Problem :)
