### ISSUE TITLE
"Free hatte sich das Telefon in der Zwischenzeit zurückgeholt"

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#587]
Vielleicht einfach nur "Free hatte sich das Telefon zurückgeholt"? Es vergehen im Hintergrund nur wenige Sekunden, und ein langer Erzähltext nimmt möglicherweise die Hektik aus der Situation heraus. Andererseits verwenden wir sowieso relativ häufig, vielleicht zu oft, wörtliche Rede und sehr wenig Erzähltext.

**Comment by yur-y** [comment]
Ja, hast Recht. Ich war mit der Formulierung auch nicht zufrieden, fand nur die Variante mit Namen und Doppelpunkt unschön. Wenn Du also insgesamt noch eine bessere Idee für die Stelle hast, gerne einbauen :)
