### ISSUE TITLE
"13Ö13ö Standard-Örztime"

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#588]
Klingt zuerst nett, aber ich brauchte einen Moment, um zu verstehen, wie das gemeint ist. Außerdem findet diese Zeitangabe in wörtlicher Rede statt, und ich glaube, Orakel kann Großschreibung nicht anders sprechen als Kleinschreibung. Das endgültige Gegenargument für diese Schreibweise gibt wahrscheinlich das unbegründet ineffiziente Hinzufügen eines Buchstabens am Ende. "13:13 Standard-Örztime" liest sich vermutlich leichter.

**Comment by yur-y** [comment]
13Ö13 Standard-Örztime?

**Comment by ToBeFree** [comment]
Jo, ich glaube, das ist eine gute Alternative.

**Comment by ToBeFree** [comment]
Jo, ich glaube, das ist eine gute Alternative.
