### ISSUE TITLE
Handelnde Personen und deren Geschlecht

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#590]
_<sup>(Unterüberschrift in den Titel verschoben ~ToBeFree)</sup>_

Nur mal ad hoc aus dem Gedächtnis:
- Alexandra
- Orakel
- Free
- yury
- Floating Island
- Wolfgang
- Bright Mountain
- Breit Kiffer
- Konrad Irby
- die Seele des Internets
- der unbenannte Äöüzz-Nachbar
- Krjtikül Djsästör
- Dömd Fällör
- Tisiphöne
- und viele weitere Statisten

Den [Bechdel-Test](https://de.wikipedia.org/wiki/Bechdel-Test) bestehen die IA derzeit nicht mal ansatzweise. Alexandra wechselt glaube ich irgendwann mal mit einer namenlosen Sekretärin in einem Regierungsgebäude zwei Sätze.

**Comment by ToBeFree** [comment]
Oh. Hm. Interessant. Ich glaube, das Problem bei uns ist, dass fast alle
"eigenständigen" Hauptcharaktere böse und machtsüchtig sind. Die
Charaktereigenschaften der Antagonisten weisen einen nicht unerheblichen
Bezug zum Hormon Testosteron auf. Das schließt weibliche Antagonisten
selbstverständlich nicht aus, macht sie aber intuitiv unwahrscheinlicher
für die IA. Es würde vermutlich sogar negativ und merkwürdig wirken, wenn
die Antagonisten stattdessen weiblich wären. Ich befürchte, dass wir ein
derart grundlegendes Problem nur im Nachhinein in den nachfolgenden Bänden
lösen können, und dass dafür mehr Planung und Überlegung erforderlich ist,
als einfach genau wie bisher nur mit veränderten Namen und Pronomen
fortzufahren.

**Comment by ToBeFree** [comment]
Oh. Hm. Interessant. Ich glaube, das Problem bei uns ist, dass fast alle
"eigenständigen" Hauptcharaktere böse und machtsüchtig sind. Die
Charaktereigenschaften der Antagonisten weisen einen nicht unerheblichen
Bezug zum Hormon Testosteron auf. Das schließt weibliche Antagonisten
selbstverständlich nicht aus, macht sie aber intuitiv unwahrscheinlicher
für die IA. Es würde vermutlich sogar negativ und merkwürdig wirken, wenn
die Antagonisten stattdessen weiblich wären. Ich befürchte, dass wir ein
derart grundlegendes Problem nur im Nachhinein in den nachfolgenden Bänden
lösen können, und dass dafür mehr Planung und Überlegung erforderlich ist,
als einfach genau wie bisher nur mit veränderten Namen und Pronomen
fortzufahren.

**Comment by ToBeFree** [comment]
Ich packe das mal ins Wiki ^

**Comment by ToBeFree** [comment]
https://www.freiwuppertal.de/ia-autoren/mw/index.php?title=Diskussion:IA2#Zweite_Handlung:_.C3.84.C3.B6.C3.BCzz-Raumfahrerinnen_entdecken_das_Roboter-Imperium

**Comment by yur-y** [comment]
Oh, ich wusste gar nicht, dass es bei den Äöüzz zwei Geschlechter gibt. Wurde glaube ich bisher so nirgendwo erwähnt, oder? (Ich hatte sogar in Erinnerung, dass mal eine gegenteilige Erwähnung im Text drin war, aber könnte mich auch irren.)

Ich hatte jetzt auch keine konkreten Veränderungsvorschläge im Sinn, es ist mir halt nur noch mal aufgefallen.

**Comment by ToBeFree** [comment]
Ins Wiki für die IA2 und folgende Bände verschoben

**Comment by ToBeFree** [comment]
Ins Wiki für die IA2 und folgende Bände verschoben. Ich hoffe, das ist in Ordnung.

**Comment by ToBeFree** [comment]
<h1 align="center"><big>❄️<br>Eingefroren: Testdruck läuft</big></h1>

<p align="center">Seit dem Testdruck bemerkte Fehler und Wünsche bitte im <a href="https://github.com/InfiniteAdventures/ia-trilogy/projects/4"><b>neuen Projekt</b></a> einfügen.</p>
