### ISSUE TITLE
Abschnitt mit vielen Fehlern

### ISSUE THREAD

**Issue by niansa** [InfiniteAdventures/ia-trilogy#591]
Ich habe auf S. 272, unten, im abschnitte mit dem vergesslichen uggy diese Fehler überall gefunden:

1. Nicht-Beachtung der Klein- und Großschreibung
2. Keine Umlaute

**Comment by ToBeFree** [comment]
Hi @niansa, vielen Dank für die Meldung und fürs aufmerksame Lesen. Ich bin sehr positiv überrascht. 😄

In diesem speziellen Fall handelt es sich um eine Schreibweise, die wir ohne besonderen Grund für alle uggys gewählt haben. Falls ein uggy einmal Umlaute oder Großschreibung spricht oder schreibt, handelt es sich um einen Fehler.

Das mag merkwürdig wirken, da gerade die uggys so penibel auf alle Gesetze achten.  Allerdings wird an einer Stelle des Romans erwähnt, dass für die Übersetzung der uggy-Sprache so viel Strom benötigt wird, dass kurzzeitig die Lichter in der 4-6692 ausgehen. Was wir lesen, ist ein Übersetzungsversuch. Vielleicht kann man die uggy-Sprache gar nicht ordentlich mit Groß- und Kleinschreibung übersetzen, oder so ähnlich.

Als Gimmick, das übersetzte uggy-Sprache von Deutsch unterscheidbar macht, hat sich das so ergeben. Der oberste Anführer der uggys spricht übrigens ganz eindeutig Deutsch. Der Grund dafür wird im Roman als Überraschung in einem Gespräch mit Orakel erwähnt. ☺️

**Comment by niansa** [comment]
Okay. :D
