### ISSUE TITLE
"Äüörüzü" als Katzennamen früher erwähnen

### ISSUE THREAD

**Issue by niansa** [InfiniteAdventures/ia-trilogy#593]
Ab S. 284 (im PDF) fehlt Alexandra eine Zeit lang, als hätte es sie nie gegeben... ist das gewollt? Ist mir beim lesen aufeinmal ziemlich aufgefallen. Und der Satz, das yury, Orakel und Free jemanden im Raumschiff nicht berken, macht das deutlich.

Edit: 2 Seiten weiter ist sie wieder da.

**Comment by ToBeFree** [comment]
@niansa ich finde die Stelle nicht, könntest du ein kurzes exaktes Zitat einfügen, damit ich im Quelltext oder im PDF danach suchen kann?

**Comment by ToBeFree** [comment]
Danke 🙂 

----

Die Örz-News berichteten täglich über Islands Taten im Sonnensystem. Seit Monaten gab es keine Titelseite mehr, auf der kein Foto von Island zu sehen war. Irgendwann wurde es den vieren zu viel, und sie flogen wieder zur Erde.

Der Nachbar war an irgendeiner Örz-Krankheit erkrankt, die wohl einiges mit einer Erd-Grippe gemeinsam hatte. Weil er sich vorerst nicht um **seine Katze** kümmern konnte, entschloss Alexandra sich dazu, sie mit auf das Raumschiff zu nehmen. Auf der 4-6692 flog nun auch »**Äüörüzü**« mit, ohne dass yury, Orakel oder Free etwas davon wussten.

\begin{center}
	∞∞∞
\end{center}

Als sie sich dem Sonnensystem näherten, verringerte yury vorsichtig die Geschwindigkeit des Raumschiffs und deaktivierte den Warp-Antrieb. Orakel drückte einige Tasten, und auf den Außenbildschirmen wurden die Umlaufbahnen der Planeten als hellblaue Linien um die Sonne herum sichtbar. Einige weitere Tastendrücke färbten die Umlaufbahn der Erde rot ein, und es wurden fünf Punkte sichtbar, die mit »L1« bis »L5« beschriftet waren.

\begin{figure}[p]
	\includegraphics[width=\linewidth]{include-main-lagrange.jpg}
	\caption{Lagrange-Punkte der Sonne und der Erde}
\end{figure}

An diesen Punkten, erklärte Orakel, konnte man die 4-6692 ohne Treibstoffverbrauch im Weltall parken. yury ergänzte, dass die Schwerkraft von Erde und Sonne sich an diesen »Lagrange-Punkten« gegenseitig aufhob.

»Die Punkte L1, L2 und L3 sind instabil«, erklärte yury. »Man rutscht sozusagen davon weg und muss dann eben doch immer wieder die Triebwerke nutzen, um das Raumschiff zurück zum Punkt zu bringen.«

»Deshalb nehmen wir stattdessen einen Premium-Parkplatz«, witzelte Orakel. »Bei den Punkten L4 und L5 kann man das Raumschiff jahrelang parken, ohne dass es von alleine wegfliegt.«

Mit einem Beiboot näherten sich die Freunde der Erde, während der Autopilot die 4-6692 in sicherer Entfernung am L5-Punkt parkte. Über der Erde in einer stabilen Umlaufbahn angekommen, schloss Alexandra die Katze mit etwas Futter in ihrem Zimmer ein. **Dann verließen Orakel, yury, Alexandra und Free das Beiboot und schwebten in Raumanzügen herab.**

**Comment by ToBeFree** [comment]
Ich habe aber gerade nochmal nachgesehen: Der Name der Katze wird dort zum ersten Mal erwähnt. Das war in der ursprünglichen Fassung anders, dort bezeichnete "Äüörüzü" noch die Spezies, nicht das eine Tier.

**Comment by niansa** [comment]
Ne ich meine: Es wirkt zu anfang so, als wäre Alexandra nicht da.

**Comment by niansa** [comment]
Aaah. Okay... Also darauf, dass das die Katze ist, bin ich nicht gekommen. ^^

**Comment by ToBeFree** [comment]
Ich glaube, die jetzige Fassung lässt selbst unaufmerksame Leser spätestens bei der Explosions-Szene begreifen, wer Äüörüzü ist. 🙂
