### ISSUE TITLE
Finden mit SoulOfTheInternets allmächtigeM und unbesiegbareM Universums-Explorer (?)

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#595]
_Finden mit SoulOfTheInternets allmächtigem und unbesiegbarem Universums-Explorer._

Zweimal M, oder? Vorher stand dort eine Mischung,

_Finden mit SoulOfTheInternets allmächtigem und unbesiegbaren Universums-Explorer._

Ich musste aber lange überlegen.

**Comment by yur-y** [comment]
Ja, müsste in dem Fall stimmen. Wechselflexion (-m/-n) wird nur eingesetzt, wenn das zweite Adjektiv mehr zum Substantiv gehört und damit dem ersten eher über- als nebengeordnet ist.

**Comment by ToBeFree** [comment]
Hui. :) Danke!
