### ISSUE TITLE
Frage: Darf ich pull requests machen?

### ISSUE THREAD

**Issue by niansa** [InfiniteAdventures/ia-trilogy#596]
Ich frage lieber, bevor ich es tue und es falsch war. Ich bin mir nicht ganz sicher wegen Namensnennung.

**Comment by ToBeFree** [comment]
Hi @niansa, es wäre am besten, wenn du indirekt auf Fehler hinweist, nach dem Motto "Auf Seite X des aktuellen PDFs sieht irgendetwas sprachlich merkwürdig aus, aber ich bin mir nicht sicher, was". Direkte Hinweise sind vermutlich ebenfalls in Ordnung, aber bitte ohne Korrekturvorschlag. Pull requests müsste ich ablehnen.

Der Quelltext ist frei verfügbar, die Entwicklung findet größtenteils transparent statt, aber das Projekt ist geschlossen und wenig einladend für neue Autoren. Das war früher anders, aber niemand außer uns hat sich dauerhaft engagiert oder neue Szenen beigetragen. Vielleicht ist es auch eines Tages wieder ein offenes Projekt. Nach dem Motto "zu viele Köche verderben den Brei" besteht aber derzeit kein Bedarf in dieser Hinsicht. Daher gibt es vorerst keine Pull requests und keine neuen Mitglieder im Autorenteam.

**Comment by niansa** [comment]
Okay, danke.
