### ISSUE TITLE
Termin für finale Bearbeitung

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#597]
Frohes neues Jahr! Sorry, dass ich gestern vergessen hatte, das Bearbeitungskästchen wieder zu unchecken (gibt es dafür ein deutsches Wort?).
Da der Veröffentlichungstermin näher rückt und die Zahl der Issues langsam aber sicher sinkt, würde ich vorschlagen, dass wir mal einen Termin für die finale Bearbeitung festmachen. Hast Du einen Vorschlag?

**Comment by ToBeFree** [comment]
Frohes Neues! Und ich hatte schon gedacht, du arbeitest die Nacht durch an irgendwelchen Fehlern. :smile: 

(Nee, hab ich mir schon gedacht. Passiert mir auch ständig. Vielleicht kann man dazu "deaktivieren", "leeren" oder "abwählen" sagen)

Ich würde gerne demnächst wieder Testexemplare drucken. Für deines benötige ich eine aktuelle Adresse, die du mir noch per E-Mail schicken müsstest. Mirco bekommt sein Exemplar unangekündigt als Überraschung per Post.

Der Druck und Versand dauert erfahrungsgemäß ca. 10 Werktage. Das sind zwei Wochen Wartezeit, in denen wir uns z.B. auf den Bonusband konzentrieren könnten.

Was hältst du davon, den Hauptroman bis Ende Freitag, den 18. Januar 2019, in einen Zustand zu bringen, der eigentlich "fertig" ist? Mit dem Buch in der Hand finde ich bestimmt anschließend noch unzählige Änderungsvorschläge, aber dafür muss es erst einmal gedruckt worden sein.

Sämtliche Issues des aktuellen Projekts sollten wir bis zum Drucktermin geschlossen haben. Ich arbeite heute am Hauptroman, um #520 , #584 und #593 zu beheben.

**Comment by ToBeFree** [comment]
Der Hauptroman ist ja bereits praktisch fertig. Die Issues beziehen sich nur noch auf den Bonusband.

Testdruck ab **11.** Januar?

**Comment by niansa** [comment]
@yur-y unchecken ist abwählen. ;)

**Comment by ToBeFree** [comment]
<h1><big><center>❄️<br>Eingefroren für Testdruck</center></big></h1>

Seit dem Testdruck bemerkte Fehler und Wünsche bitte im <b>[neuen Projekt](https://github.com/InfiniteAdventures/ia-trilogy/projects/4)</b> einfügen.
