### ISSUE TITLE
E-Book als .epub

### ISSUE THREAD

**Issue by niansa** [InfiniteAdventures/ia-trilogy#599]
Ich finde das epub format bei E-Books wegen besserer kompatibilität und lesbarkeit auf z.B. Tolinos viel besser als im pdf format! Ich hoffe, das es nicht zu schwierig ist, tex zu epub zu konvertieren! :D

**Comment by ToBeFree** [comment]
Danke für den Wunsch: Kein Problem, ist bereits geplant und kommt auf jeden Fall! :)

Siehe #399 für die bisher gesammelten Format-Ideen.

**Comment by niansa** [comment]
Super.

**Comment by ToBeFree** [comment]
Das EPUB ist fertig und erscheint zusammen mit dem Buch bald auf infiniteadventures.de

**Comment by ToBeFree** [comment]
Das EPUB ist fertig und erscheint zusammen mit dem Buch.
