### ISSUE TITLE
S. 16: "A 340" -> "A\,340" (dünnes Leerzeichen ohne Umbruch)

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#606]

**Comment by ToBeFree** [comment]
"Achtelgeviert" kannte ich noch nicht, aber ich habe bei der Suche einen LaTeX-Standardbefehl entdeckt, der genau für solche Fälle vorgesehen ist (ist allerdings ein Sechstelgeviert). 🙂
