### ISSUE TITLE
S. 18: "die Milchhörnchen" -> "das Milchhörnchen"?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#614]
Ich dachte, Orakel hat sich das letzte genommen? Aber vermutlich hätte er es eher direkt aufgegessen? (s. S. 16)

**Comment by ToBeFree** [comment]
Jetzt sind es Kekse. 🙂 

Ein möglicher Widerspruch wäre, dass Orakel keine Datteln mag und vielleicht früher auf die Idee kommen könnte, stattdessen Kekse zu frühstücken. Da das Datteln-Essen durch die Suche nach den Keksen unterbrochen und anschließend wieder fortgesetzt wird, kann man aber davon ausgehen, dass Orakel die Kekse als Beilage holen wollte.
