### ISSUE TITLE
S. 27: "aus dem deutschen Festnetz" -> ???

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#621]
Ich hatte ja schon mal yurys und Orakel Verwunderung über die deutschsprachige Sprache beim amerikanischen Sender eingebaut. Aber deutsches Festnetz ist nun wirklich absurd?

**Comment by ToBeFree** [comment]
Das ist natürlich bitter.

"aus dem amerikanischen Festnetz"?
