### ISSUE TITLE
"Kühlraum" -> "Tiefkühlzelle"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#625]
_Ursprünglicher Titel: **S. 32, Kühlraum-Szene: "Er war ein einziger Eisblock". Der Strom geht nicht!**_

_Ursprünglich ohne Kommentar._

_~ToBeFree_

**Comment by ToBeFree** [comment]
Je größer ein Gefriergefäß ist, desto geringer ist das Verhältnis von Oberfläche zu Volumen. Ein großer begehbarer Kühlraum ist also deutlich temperaturstabiler als ein kleines Gefrierfach.

Hier ist beispielsweise eine Gefriertruhe, in deren Datenblatt explizit steht: "Lagerzeit bei Störung: 74h"
https://home.liebherr.com/de/deu/produkte/hausger%C3%A4te/standger%C3%A4te/gefriertruhen/details/gtp-4656.html

Das Ding hat ein Volumen von 419 Litern. Ein Würfel mit diesem Volumen hätte eine Kantenlänge von 0,75 Metern. Eine begehbare Tiefkühlzelle kann mehr als zehnmal so groß sein, ich habe eine mit 12.000 Litern Innenvolumen für ca. 3500 Euro gefunden.

Wenn es sich "nur" um einen Kühlraum mit Temperaturen von über 0 Grad handelt, sieht es wahrscheinlich anders aus. Aber dann würde Orakel auch bei funktionierender Stromversorgung nicht zum "Eisblock" werden und anschließend vor sich hin tauen. Ich denke also, es handelt sich um eine Tiefkühlzelle, und diese kann auch nach 48 Stunden durchaus noch sehr kalt sein. Aufgrund des großen Volumens vielleicht auch kalt genug, um Orakel passiv zum Eisblock abzukühlen.
