### ISSUE TITLE
S. 34: "riss ein Fenster auf"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#627]
...Wird dann nicht die Etage überflutet? Oder macht das nichts, wenn die Öffnung kurz genug ist?

**Comment by yur-y** [comment]
Nein, nur das (andere) Zimmer, (in dem nicht die TMPE ist,) oder?

**Comment by ToBeFree** [comment]
Ich denke aber, dass es um das Treppenhaus geht. Wenn wir bequemerweise davon ausgehen, dass es nur ein einziges Treppenhaus gibt (diese Annahme trifft der Roman bisher tatsächlich), dann muss man das Treppenhaus abdichten, damit von unten kein Wasser hereinkommt, sobald oben etwas geöffnet wird.

Möglicherweise ist aber die ganze Situation total absurd. Der über dem Wasser liegende Teil der Etage wiegt sicherlich mehrere Tonnen. Der Luftdruck wird wahrscheinlich ziemlich stark sein, und die Freunde hätten beim Betreten der Etage gegen einen heftigen Windstrom ankämpfen müssen.

Würde ich einfach so lassen. Dass die Etage überhaupt existiert, ist ja auch schon absurd.
