### ISSUE TITLE
S. 43: "was Orakel entweder nicht zu bemerken oder nicht zu stören schien"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#629]
Das ist grammatikalisch - ich weiß nicht ob inkorrekt, aber doch zumindest gewöhnungsbedürftig, weil Orakel bei "bemerken" das Subjekt und bei "stören" das Objekt darstellt.

**Comment by ToBeFree** [comment]
Oh, interessante Überlegung. Ja, das klingt dann eigentlich so, als ob Orakel stört.
