### ISSUE TITLE
S. 52: "Zehn-Liter-Kanister". Und generell das Tanken im ganzen Buch

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#634]
Ich fürchte, mit Kanistern kommt man da nicht so weit. [Dieser Heli](https://www.johanniter.de/dienstleistungen/im-notfall/rettungsdienst/luftrettung/rettungshubschrauber-christoph-12/technische-daten/) verbraucht z. B. 225 Liter pro Stunde.^^

**Comment by ToBeFree** [comment]
Oh Gott. 😅 

Ja, das ist mir sogar bereits aufgefallen. Es war mir zu schmerzhaft, das irgendwie konsequent beheben zu wollen. An einer Stelle wirft Orakel mit einem Stein nach einem Helikopter, der daraufhin notlandet. yury stiehlt anschließend mit nicht näher beschriebenen Mitteln den Tankinhalt. Das könnte auch ein Schlauch gewesen sein, durch den dann wenigstens an einer Stelle des Romans eine volle Tankladung Kerosin gestohlen wurde.

Mal gucken, ob wir das schön gelöst bekommen. 🙂

**Comment by ToBeFree** [comment]
Ja, beim Benzinpreis habe ich kürzlich aktuelle Preise eingefügt. 😃

**Comment by ToBeFree** [comment]
Die von dir angesprochene Szene ist gar nicht problematisch, denn es handelt sich sowieso um Benzin, das vom Helikopter wieder ausgespuckt wird.

Beim Kerosindiebstahl auf dem Flughafen wird keine Literzahl erwähnt. Es wirkt zwar nicht so, aber theoretisch könnten die Freunde einen riesigen Kanister, eine Schubkarre und einen Schlauch dabeihaben, mit der Schubkarre fliehen, den Kanister ins Taxi laden und mit dem gestohlenen Treibstoff eine halbe Stunde lang fliegen.

**Comment by ToBeFree** [comment]
Ich hatte überlegt, die Schubkarre noch einzubauen, aber das passt nicht in die chaotische Situation.
