### ISSUE TITLE
"Ein Besuch im Fast-Food-Restaurant"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#635]
1000 Rand sind ca. 65 Euro. Das schafft selbst Orakel nicht.^^

**Comment by ToBeFree** [comment]
Doch doch, das war Absicht. 😄

**Comment by ToBeFree** [comment]
Okay, ich habe auf der Website eines bekannten Fast-Food-Restaurants mal einen Warenkorb für den Lieferservice zusammengestellt. Soweit ich das erkennen kann, kommt man nicht auf 65 Euro, ohne einen menschlichen Magen physikalisch zu überfüllen.

Tausend ist aber eine schöne Zahl. Vielleicht ist Orakel ein Angeber und übertreibt ein bisschen? 🙂

**Comment by ToBeFree** [comment]
Nehmen wir einfach mal an, dass Orakel gerne ein bisschen übertreibt. 😄
