### ISSUE TITLE
S. 16: "zu ihrem neuen Airbus" -> "zu Ihrem neuen Airbus"

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#638]
Jetzt kann ich natürlich behaupten, das sei einer der wenigen Fehler gewesen, die ich "mehr" gefunden habe als du. Um diesen Eindruck mal eben zu beseitigen: Das ist der _einzige_ Fehler, den ich dort gefunden habe. 😅

**Comment by yur-y** [comment]
Bitter, dass ich das übersehen habe.^^
