### ISSUE TITLE
Allgemein: "schrie" -> "rief"(?)

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#643]
Ja, OK, ich mag das Wort einfach nicht.^^

**Comment by ToBeFree** [comment]
Generell Zustimmung -- aber das scheint vielleicht doch eine der wenigen Stellen im Roman zu sein, wo "schreien" auch in der Bedeutung "panisch schreien" vorstellbar und passend ist.

**Comment by ToBeFree** [comment]
Schließen?

**Comment by ToBeFree** [comment]
Status: Nicht ersetzt: Unnötig starke Lautstärke ist gegeben, fehlende räumliche Distanz zum Empfänger. "Schreien" scheint das Geschehen besser zu beschreiben als "Rufen"

»Du… Du… Du…«, sagte yury wütend.

»Orakel?«, fragte Orakel kleinlaut.

»\iashout{Vollidiot!}«, schrie yury.

**Comment by ToBeFree** [comment]
Status: 

-----

**Comment by ToBeFree** [comment]
Status: 

-----

**Comment by ToBeFree** [comment]
Status: 

-----

**Comment by ToBeFree** [comment]
Status: 

-----

**Comment by ToBeFree** [comment]
Status: ersetzt: Orakel hat das möglicherweise schon lange geplant, Panik ist gar nicht unbedingt vorhanden und würde dann doch wohl eher zu einer direkten Flucht führen. Sein Ruf _soll_ die Wachleute erreichen, seine Rucksack-Inbesitznahme _soll_ von den Wachleuten bemerkt werden, und er weiß, dass er laut (aber nicht übertrieben laut) rufen muss, um die eigentlichen Adressaten zu erreichen. Außerdem sieht "rief" hier sprachlich schön aus.

-----

Vor dem Museum war inzwischen ein großer Helikopter mit zwei Hauptrotoren gelandet und zog die Aufmerksamkeit der Touristen auf sich. Fröhlich gingen Free und Orakel eine Treppe hinunter, als plötzlich ein Wachmann rief: »Das Bild ist ein Fake! Schnappt euch den Typen mit dem Rucksack!«

»Mist!«, schrie Orakel. Er riss den Rucksack an sich, rannte schräg über die Stufen und sprang über das Treppengeländer, die Wachmänner waren dicht hinter ihm. Free blieb entgeistert stehen und wurde beinahe vom Personal überrannt. Nachdem er Orakels akrobatische Flucht eine Weile beobachtete hatte, lächelte er und ging in aller Ruhe zum vereinbarten Ausgang.

Über Umwege hängte Orakel seine Verfolger ab; schließlich lief er auf einen der Seitenausgänge zu. Free stand schon draußen, als die Glastür automatisch geschlossen wurde. Orakel rannte immer noch weiter. Er nahm sich eine Vase, die auf einem schön gedeckten Tisch stand, und schmetterte sie mit aller Kraft gegen die Glastür. Nun wurde der Hausalarm ausgelöst, die Tür blieb jedoch unbeschädigt. Orakel gab Free ein Handzeichen, dass er bereits zum Helikopter rennen sollte. Dann nahm Orakel erneut Anlauf und sprang mit aller Kraft gegen die Glastür. Sie zersprang in tausende Teile, und Orakel war draußen. Doch Orakel freute sich nicht. Er hatte viele Scherben am Körper und ertrug höllische Schmerzen. Er sah, wie yury in der Ferne schon die Motoren des neuen Helikopters startete. Völlig außer Atem kam Orakel dort an. Free zog ihn hinein und schloss schnell die Tür.

**Comment by ToBeFree** [comment]
Status: ersetzt, aber nicht durch "rief", wegen der ansonsten entstehenden Wortwiederholung. Grund: Aus "Rufen" wird ohne Anlass nicht auf einmal "Schreien". Schon gar nicht, wenn es sich um einen konzentrierten Versuch handelt, eine fremde Sprache zu imitieren.

-----

Orakel maulte auf dem ganzen Weg herum. Er wollte etwas essen und nicht von blöden grünen Wesen entführt werden. Als sie in der Stadt ankamen, gingen sie in ein großes Gebäude. Anscheinend war dieses Gebäude eine Art Rathaus. Nun standen die vier einem Dorfbewohner gegenüber, welcher etwas größer war als die anderen und eine Krone auf dem Kopf trug.

Orakel meinte: »Hi, ich bin Orakel und…«~– »ÖRÄGEL!«, rief das Wesen.

»Nee, nee, mein Freund. O-R-A-K-E-L!«

»ÖRÄGEL!«, schrie das Wesen erneut. Dann packte es Orakel mit erstaunlicher Kraft und setzte ihn auf einen Stuhl. Schließlich nahm es seine Krone vom Kopf und setzte sie Orakel auf. Dabei sagte es: »Öhm, nabbadabeidadu. Öhm, babauzi. Örägel… Örägel… Habnabatopschadamika… ÖRÄGEL.«

**Comment by ToBeFree** [comment]
Status: nicht ersetzt, "anschreien" ist hierfür ein gutes Wort

----

Daraufhin sah ihn das Wesen an. yury vermutete später, dass es wohl ein wütendes Gesicht gemacht hatte, dann schlug es ihn.

»Hey! Was soll das?«, schrie yury das Wesen an. Daraufhin umarmte ihn der Äöüzz freundlich und verschwand.

**Comment by ToBeFree** [comment]
Status: Trotz Wortwiederholung nicht ersetzt, da es kein besseres Wort als "anschreien" zu geben scheint. Falls dir noch eines einfällt, bevor der Roman veröffentlicht wird, bitte folgendermaßen vorgehen:

- Issue erneut öffnen
- Issue dem letzten Veröffentlichungsprojekt zuordnen
- Einen Kommentar mit "@ToBeFree" hinzufügen
- eine E-Mail an mich senden, Betreff "Wichtig, vor der Veröffentlichung"

----

Es gab nirgendwo eine Lampe, nirgendwo einen Lichtschalter, nirgendwo eine Tür, nirgendwo Fenster und eigentlich gab es außer vier Wänden gar nichts. Plötzlich stieß Free mit jemandem zusammen. Er fiel zu Boden. Das Etwas schlug Free und schrie ihn an: »Schlag mir nie wieder auf den Kopf, du blödes, haariges Wesen!«

**Comment by ToBeFree** [comment]
Status: ersetzt, klassischer Fall von "Rufen"

----

Dann war es still. Nach zehn Minuten ging die Klappe auf und die vier wurden mit komischen Haken an der Kleidung nach oben gezogen. Als sie oben waren, wurden sie von mehreren Äöüzz durch das Dorf geschleppt und anscheinend zu einem Gericht oder etwas Ähnlichem gebracht. Alexandra, die der Meinung war, dass es sowieso nicht schlimmer werden konnte, schrie plötzlich in die Menge:

»Äzü! Äöüözz! Gnörüüüüräz! Üäf!« (oder so ähnlich).

Die Reaktion der Äöüzz war unglaublich. Sie ließen die vier sofort los und liefen mit großer Angst weg.

**Comment by ToBeFree** [comment]
Status: Schon allein wegen der ansonsten direkt entstehenden Wortwiederholung nicht ersetzt. Zudem nicht unpassend, immerhin hat Orakel Angst um sein Leben. yury hingegen ist gelassen genug, um Galgenhumor zu fabrizieren. :)

----

Die vier liefen, so schnell wie sie konnten, zum Helikopter. Plötzlich fingen die Wesen an, zu schießen. Sie hatten eine Strahlenkanone oder etwas Ähnliches.

»Hilfe!«, schrie Orakel, während er den Schüssen auswich. »Die schießen ja auf uns!«

»Ach was!«, rief yury zurück. »Ich dachte, wir hätten Neujahr!«

**Comment by ToBeFree** [comment]
Status: ersetzt, klassischer Fall von "Rufen"

----

»Habt ihr hier Pizza?«, fragte der neue König einen seiner Diener.

»Päzzö? Äj, Päzzö!«, schrie ein Wesen in die Runde. Kurz danach öffnete sich eine Tür und es kamen fünf Wesen heraus, die ein riesiges Tablett auf dem Kopf trugen.

**Comment by ToBeFree** [comment]
Status: nicht ersetzt, die Explosion dürfte yury einen gehörigen Schreck und eine Portion Angst eingejagt haben. Die Dramatik der Explosion würde durch "Rufen" gemindert.

----

»Der Helikopter hält das nicht mehr lange durch!«, rief yury.

»Warte, der ist jetzt schon bei 99…«. Dann wurde Free von einem lauten Knall unterbrochen. Er drückte den Beam-Knopf.

»Der Hyperwurm ist explodiert!«, schrie yury. Kurz danach schoss eine riesige Feuerwelle vom Helikopter auf den Boden. Dort, wo eben noch Orakel gestanden hatte, war nur noch Asche. Dann war alles ganz still. Alexandra, Free und yury standen am Fenster und starrten den Krater an.

**Comment by ToBeFree** [comment]
Status: nicht ersetzt, denn wie immer bei "anschreien" gibt es keine schönere Alternative.

----

»Wo ist Floating Island?«, fragte Alexandra direkt.

Wolfgang zögerte. Nach einigen Sekunden entschied er, dass er sowieso nichts zu verlieren hatte. »Im Gefängnis. Ich hole mir gerade die Million, die mir zusteht. Irgendwo wird er sie schon versteckt haben. Und jetzt verschwindet gefälligst, ich habe zu tun!«, schrie er die vier an und schlug die Tür vor ihrer Nase zu.

**Comment by ToBeFree** [comment]
Status: einmal ersetzt, das zweite Vorkommen, schon allein, um eine Wortwiederholung zu beseitigen.

----


»Oh, verdammt! Mir steckt ein Stück Burger im Hals!«~– Orakel lief, ganz offensichtlich ohne echte Not, schreiend durch das Raumschiff und suchte eine Toilette oder etwas zu trinken. Er lief bestimmt zehn Minuten im Kreis, bis er Alexandra sah, stehen blieb und sie anschrie: »Arrgh! Mir steckt ein Stück Burger im Hals!«

»Achter Gang rechts, vierte Tür links«, rief Alexandra ihm zu.

Orakel schrie noch »Danke!«, dann lief er weiter.

**Comment by ToBeFree** [comment]
Status: ersetzt, denn "schreien" wäre hier schlichtweg übertrieben.

----

In eine Postboten-Uniform gekleidet betrat Orakel die Zentrale der 4-6692. »Guckt mal, was gerade durch die Schleuse hereingekommen ist.«

Dann bekam yury einen Lachanfall.

»Sie lebt! Sie lebt!«, schrie Alexandra überglücklich.

**Comment by ToBeFree** [comment]
Status: ersetzt, denn der angeblich so panische yury hat gerade mit relativ kühler Gelassenheit einen genialen Plan entwickelt. Außerdem richtet er seine Worte gezielt an eine einzige andere Person, die in diesem Fall auch gar nicht "angeschrien" wird, sondern sich vielleicht wirklich am anderen Ende des Raums befindet.

----

»Ich habe ihn geortet!«, freute sich Free.

»Sofortiger Gegenschlag! Richte die Solarspiegel in Richtung des Lasers aus!«, schrie yury mit panischem Blick auf die Kapazitätsanzeige.

»Meinst du, ich lasse mir von dir etwas…«

**Comment by ToBeFree** [comment]
Status: nicht ersetzt, da stirbt jemand.

----

\textit{»Das Zielobjekt wird nun zerstört. Für diesen Vorgang wurden 1500 GB Arbeitsspeicher benötigt. Danke, dass Sie Java genutzt haben.«}

\textit{»Prötäktjng. 0 \% käpäzity üsed. Ästimätd prötäktiöntime: (infinü)«}

»So viel Glück gibt’s doch gar nicht!«, schrie die Person auf dem anderen Schiff noch, bis dieses durch seine eigenen reflektierten Laserstrahlen überhitzte und in einem gewaltigen Lichtblitz verging.

**Comment by ToBeFree** [comment]
Status: ersetzt, weil in diesem Fall beide Worte meiner Meinung nach gleich passend sind und um Ersatz gebeten wurde.

----

»Moin Soulchen. Das mit dem Raumschiff war nicht so nett, eigentlich wollten wir… Arrg!« Ein heller Lichtblitz traf Orakel auf der Brust. Er fiel zu Boden.

»Orakel!«, schrie Free.

**Comment by ToBeFree** [comment]
Status: ersetzt durch "brüllte": Der gute Mann hat gerade einen heftigen Stromschlag erhalten. Die Lautstärke seiner Antwort, die er zudem ziellos in die Luft brüllt, darf gerne durch das Wort "schrie" verdeutlicht werden. "Brüllen" ist aber ebenfalls eine ganz nette Beschreibung, die ansonsten fast nie einsetzbar ist.

----

Ein zweiter Blitz hatte Orakel erneut zu Boden fallen lassen. Diesmal ließ er sich nicht davon beeindrucken. »Trotzdem bescheuert!«, schrie er wütend.

**Comment by ToBeFree** [comment]
Status: ersetzt, "riefen" passt gut.

----

Dann meldete sich die Stimme erneut: \textit{»Ihr seid hier, um mein neues, unglaublich realistisches Virtual-Reality-Spiel auszutesten!«}

»Was?«, schrien die vier gleichzeitig.

**Comment by ToBeFree** [comment]
Status: ersetzt, weil "anschreien" hier sowieso nicht gut passt. Es mangelt vermutlich eher an Lautstärke.

----

yury ging zu Alexandra, legte seine Hand auf ihre Schulter und sagte: »Passiert. Kaufen wir uns halt ein…«

»Du verstehst das nicht!«, schrie Alexandra yury an und rannte weg.

----

Neue Fassung:

[...]

»Du verstehst das nicht!«, rief Alexandra beleidigt und rannte weg.

**Comment by ToBeFree** [comment]
Status: ersetzt, aber nur an der ersten Stelle.

----

Zehn Minuten verbrachte Free damit, die Triebwerke aneinander zu schrauben. Hin und wieder hörte man »So ein schlecht konstruierter Mist« und ähnliche Flüche aus seiner Richtung. Alexandra, yury und Orakel langweilten sich. Sie waren voll und ganz nass, von Kopf bis Fuß.

Plötzlich schrie Free: »Ja, ich habe es geschafft! Jetzt brauche ich nur noch einen PC, hoffentlich mit Linux, und dann läuft alles!«

yury wurde knallrot, er schwamm auf Free zu, packte ihn an den Schultern, rüttelte ihn und schrie: »Guck dich doch mal um! Wir sind am Ende der Welt! Wo willst du hier, verdammt noch mal, einen PC herkriegen?!«

**Comment by ToBeFree** [comment]
Status: nicht ersetzt, wobei man hier sicherlich auch "Rufen" verwenden kann. Die Verzweiflung und die Lautstärke könnten durchaus groß sein.

----

Während Free sämtliche internen Daten des CDWAI aus dem Intranet auf einen USB-Stick kopierte und sich mindestens hundert Mal über das Betriebssystem aufregte, das offenbar voller Programmierfehler war, ging auf einmal die Tür zum Büro auf und ein fein gekleideter Herr fragte: »Bitte verzeihen Sie die Störung. Wünschen Sie einen Kaffee?«

»Nein! Raus!«, schrie der Helfershelfer den erschrockenen Diener an. Leise schloss dieser die Tür wieder und verschwand.

**Comment by ToBeFree** [comment]
Status: ersetzt, beide Vorkommen, aber zu dieser Szene gibt es eine weitere Fehlermeldung. Diese Rufe aus dem Nichts werden möglicherweise gelöscht.

----

»Ähm… Kann sein, ist das nicht der Typ, der mal in der Zeitung stand, weil er ein Fast-Food-Restaurant leer gegessen hat und…«

\textit{»McIsland!«}, schrie eine unglaublich laute Stimme von allen Seiten. Die fünf zuckten zusammen. \textit{»Es war nicht irgendein Restaurant! Es war McIsland! Das Original! Schreib dir das hinter die Löffel!«}

»Verdammt. Weg hier«, sagte der Mann und flog weg.

\textit{»Ich bin überall! Ihr könnt nicht vor mir fliehen!«}, schrie die Stimme noch lauter.

**Comment by ToBeFree** [comment]
Status: nicht ersetzt, schon allein wegen der ansonsten entstehenden Wortwiederholung. Lautstärke und Panik sind vorstellbar. Dass sich die Lautstärke steigert, auch.

----

»Cool! Essen mit einer Showeinlage!«, freute sich Orakel.

»Das ist keine Showeinlage, das ist die Polizei!«, rief yury. »Schnell weg!«.

yury, Alexandra und Free liefen weg, doch mit den Worten »So viel Zeit muss sein« ging Orakel zurück zur Theke und gab dem Verkäufer Trinkgeld.

»Orakel, komm!«, schrie Free.

**Comment by ToBeFree** [comment]
Status: ersetzt, das ist kein "Anschreien". Die Freunde sind bereits weit entfernt.

----

»Die wollen mir kein Essen geben!«, sagte er, als er bei ihnen ankam. yury wollte gerade sein Verständnis für diese Entscheidung bekennen, als der Wachmann auf einmal begriffen hatte, dass die vier gerade ausbrechen wollten.

»Hey, ihr da, sofort herunterkommen! Wo habt ihr die Jetpacks her? Runter, habe ich gesagt!«, schrie er die vier an. Die kümmerten sich nicht weiter um ihn und flogen langsam über das große Gefängnistor. Der Wachmann konnte nichts machen und fing schließlich an, zu weinen.

**Comment by ToBeFree** [comment]
Status: ersetzt, das ist eher ein "Zuruf".

----

Daraufhin hatte Orakel eine Idee: Er sah eine alte Frau in der Warteschlange. Während er auf den frei gewordenen Platz neben sich rutschte, schrie er zu der alten Frau: »Ey, Ömchen, sie können meinen PC haben, der ist schon an!«

**Comment by ToBeFree** [comment]
Status: nicht ersetzt, Orakel ist wirklich so taktlos.

----

Orakel rannte weg. Er sah ein Taxi, sprang hinein und schrie den Fahrer an: »Zum Pentagon! Wie viel macht das?«

**Comment by ToBeFree** [comment]
Status: ersetzt

----


»Nein, ich will dich nicht küssen, du alte, dreckige…«

»…Super-Omi!«, schrie yury in die Runde, bevor Orakel seinen Satz beenden konnte.

**Comment by ToBeFree** [comment]
Status: nicht ersetzt, "anschreien". Außerdem ist die Szene sowieso nicht mehr zu retten.

----

Quintus erinnerte sich, entschuldigte sich und fiel tot um. Orakel und Free hatten keine Zeit, sich darüber zu wundern, weil plötzlich ein Polizist neben ihnen stand. Er schrie die beiden an und war fest davon überzeugt, dass sie Quintus ermordet hätten.

**Comment by ToBeFree** [comment]
Status: nicht ersetzt, Panik gegeben. Als Anfangsszene aus Archivgründen zudem vor allzu drastischen Änderungen geschützt.

----

Das Flugzeug verlor immer mehr an Höhe und der selbsternannte Profipilot las einfach nur die erste Seite der Bedienungsanleitung. Danach fragte Free noch nach Erdnüssen. Das wurde Orakel zu viel. Er schrie ihn an: »Du musst den Steuerknüppel zu dir hinziehen! Schnell!«

**Comment by ToBeFree** [comment]
Status: nicht ersetzt, weil Anfangsszene und Orakel.

----

Orakel wusste nicht, was er antworten sollte. Er hatte allerdings vor fünf Tagen einen Kapitän im Fernsehen gesehen, der sehr beliebt war und andauernd »Volle Kraft voraus!« sagte. Diesen Satz verstand Orakel nicht, aber er war sich sicher, dass dieser Satz der richtige war. »Volle Kraft voraus!«, schrie Orakel den Offizier an; dieser reagierte mit einem verwunderten Blick, tat schließlich allerdings, was der »Kapitän« ihm befahl.

**Comment by ToBeFree** [comment]
Status: einmal ersetzt, das zweite Vorkommen, durch "Brüllen in ihre Richtung".

----

»Nur noch 1.500 Fuß!«, sagte Orakel. »Das sind«~– er rechnete kurz~– »knapp fünfhundert Meter.«

yury schrie ihn an, zog Free von den Instrumenten weg und schubste Orakel dorthin. Der begann sofort fieberhaft, sich an das Gelernte zu erinnern. Inzwischen waren sie nur noch knapp über dem Meer… und Orakel lenkte das Flugzeug wieder nach oben. Diese Maßnahme kam jedoch zu spät; das Flugzeug landete auf dem Wasser und fuhr mit hoher Geschwindigkeit auf eine Schiffswerft zu, die gerade ein mehrere Hundert Millionen Euro teures Passagierschiff fertiggestellt hatte. Das Schiff schwamm auf dem Wasser und der stolze Besitzer stand auf der Brücke und winkte den Werftmitarbeitern noch zum Abschied zu. Da schwamm das Flugzeug nur noch ganz langsam an das Schiff heran. Die Nase des Flugzeuges berührte das Schiff leicht. Daraufhin ging das Schiff unter.

»Ihr schon wieder? Das kann ja wohl nicht wahr sein, ihr habt gerade eine halbe Milliarde Euro \iashout{versenkt}!«, schrie der Kapitän, der sich noch retten konnte, sie an.

**Comment by ToBeFree** [comment]
Status: nicht ersetzt, Situationskomik

----

Es klickte, und die Person am anderen Ende hatte aufgelegt.

Orakel schrie noch in das Telefon: »Mit extra Käse bitte!«, aber es war zu spät. Plötzlich stand ein Mann neben Free, yury und Orakel.

**Comment by ToBeFree** [comment]
Status: nicht ersetzt, absurde Situationskomik

----

Orakel nahm das Telefon und schrie hinein: »Jetzt pass mal gut auf, du dumme Kuh! Ich sitze seit Tagen in dieser blöden Etage fest, der Aufzug funktioniert nicht mehr, ich habe Pizza mit extra Käse bestellt und Sie schicken mir einen Pizzaboten, der A meine Pizza mit extra Käse nicht dabeihat und B sich als Agent ausgibt. Wenn Sie sich keine vernünftigen Pizzaboten leisten können, dann arbeite ich halt für Sie. Ich möchte einen Stundenlohn von 10€ und zwei Pizzen! Guten Tag!«

**Comment by ToBeFree** [comment]
Status: nicht ersetzt, absurde Situationskomik

----

Die Mieter hatten gerade einen Kuchen gebacken. Als Orakel ihn essen wollte, verbrannte er sich eine Hand. Orakel wunderte sich noch, warum seine Hand so weh tat, als yury bereits einen Eimer Wasser darüber kippte. Anstatt sich bei yury zu bedanken, schrie ihn Orakel an: »Was fällt dir ein? Jetzt ist meine Hand so nass und ich muss sie an einem Handtuch abtrocknen, welches mir gar nicht gehört!«

»Ach, aber einfach den Kuchen anfassen, das darfst du!«, schrie yury zurück.

**Comment by ToBeFree** [comment]
Status: einmal ersetzt, das erste Vorkommen. "rief" ist passender und löst die Wiederholung auf.

----

»Das war ein \iashout{Schleudersitz}, Mann!«, schrie yury. »Orakel, du Spielkind, warum musst du auch jeden Knopf ausprobieren, der dir über den Weg läuft?«

Die drei sanken langsam zu Boden. Sie waren in etwa an der holländischen Grenze, doch plötzlich hörten sie einen lauten Knall.

»Mist!«, schrie Free. »Das Flugzeug explodiert!«

**Comment by ToBeFree** [comment]
Status: nicht ersetzt, Panik gegeben.

----

»Der Zug entgleist!?«, fragte Orakel mit einem leichten Grinsen.

»Ja, der Zug entgleist!«, schrie yury, als er merkte, dass sie gerade auf eine Brücke gefahren waren, die sich in atemberaubender Höhe über einen Fluss spannte.

**Comment by ToBeFree** [comment]
Status: ersetzt durch "brüllte".

----

\textit{»Automat…«}

»Halt die Klappe, du blödes Gerät!«, schrie Free und wütete so lange, bis er die automatische Stimme irgendwie zum Schweigen gebracht hatte.

**Comment by ToBeFree** [comment]
Status: nicht ersetzt: Die Situationskomik ist sehr zerbrechlich.

----

»Cool, wir fliegen im Kreis!«, bemerkte Orakel, der immer noch Törtchen aß und sauer war, dass er nun nicht an den Automaten konnte. Nach etwa fünf Runden Kreisflug schrie Orakel yury an: »Kannst du nicht besser fliegen?«

**Comment by ToBeFree** [comment]
(ganze Helikopter-Absturzszene so belassen)

**Comment by ToBeFree** [comment]
Status: ersetzt, "rief" passt gut.

----

\textit{»Neiiiiin!«}, schrie yury verzweifelt, doch es war zu spät. »Meister« Orakel holte eine Säge und kniete sich neben das Loch.

**Comment by ToBeFree** [comment]
(restliche Szene belassen)

**Comment by ToBeFree** [comment]
Ersetzt, das zweite Vorkommen, um eine direkte Wiederholung zu vermeiden.

----

»Orakel, wo bist du?«, probierte Free so leise wie möglich zu rufen, damit sie keiner bemerkte.

»\iashout{Hier bin ich, an dem Flugzeug, ich zapfe gerade Kerosin ab!}«, schrie Orakel über den gesamten Flugplatz.

Free versuchte, Orakel mit Zeichensprache zu erklären, dass er sich leise verhalten sollte. Doch Orakel schrie daraufhin noch lauter:

**Comment by ToBeFree** [comment]
Status: nicht ersetzt, Lautstärke passend

----



»Wir müssen so schnell wie möglich zum Flugplatz, um Orakel aus der Luft mitzunehmen!«, schrie Free durch den Rotorenlärm.

**Comment by ToBeFree** [comment]
Status: sprachlich verschönert.

----

yury flog gerade über dem Stadion, da hörte er auf einmal ein \textit{»Platsch«}, dann ein \textit{»iiih«}, und dann wusste er sofort, was passiert war. yury schrie zu Orakel runter:

»Orakel, du kannst doch nicht einfach über dem Spielfeld erbrechen!«

**Comment by ToBeFree** [comment]
Status: ersetzt

----

neue Fassung:

Orakel gefiel das überhaupt nicht: »Ich will aber nicht abstürzen. Das Fußballspiel ist aus und ich kann mir von Blue noch nicht einmal ein Autogramm holen!«

**Comment by ToBeFree** [comment]
Status: nicht ersetzt (2x): Panik und Vermeidung von Wortwiederholung

----

Besser gesagt, er wollte es rufen. Stattdessen schrie er »Aaaaah!«, nachdem eine Kugel nur knapp sein Bein verfehlt hatte.

»Orakel, was ist los?«, riefen Free und yury.

\textit{»Tür zu und landen! Hier spricht die Polizei! Sie haben Kerosin gestohlen und keine gültige Flugerlaubnis!«}

Orakel war nun aber sehr sauer auf die Polizei. Er holte sein Handy heraus und suchte nach Bluetooth-Geräten in Reichweite, um die anderen Helikopter abstürzen zu lassen. Als das nicht funktionierte, trat er auf den Pilotensitz zu, zog am reparierten Höhensteuer für volle vertikale Geschwindigkeit und raste mit dem Helikopter in die Höhe. Während yury versuchte, die Kontrolle zurückzuerlangen, blaffte er Orakel an:

»Mensch, Orakel. Die Polizisten sollten in die Höhe schießen, nicht wir!«

»Was sollen wir denn sonst machen, um auszuweichen?«, schrie Orakel durch den Lärm.
