### ISSUE TITLE
S. 78: Abschnitttrennung nach "ärgerte sich Free"? Oder anderer Übergang, der das Verstreichen einiger Zeit deutlich macht..

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#646]

**Comment by ToBeFree** [comment]
Ja, aber Vorsicht: "Er" im nächsten Satz verliert dadurch eventuell seinen Bezug. Oder ist das in Ordnung trotz Trennung?

**Comment by ToBeFree** [comment]
An den Kapiteltrennungen würde ich allerdings nichts mehr ändern; ich schlage die drei Unendlichzeichen vor.

**Comment by yur-y** [comment]
Ja, die Unendlichzeichen meinte ich eigentlich, sorry. Meinst Du, das ist schon zu "getrennt" für einen Rückbezug mit "er"?

**Comment by ToBeFree** [comment]
Jup :) Müsste man mal ausprobieren, wie sich das liest.

**Comment by ToBeFree** [comment]
Passt schon.

**Comment by ToBeFree** [comment]
Unendlichzeichen eingebaut

**Comment by ToBeFree** [comment]
Unendlichzeichen eingebaut. 🙂 👍
