### ISSUE TITLE
S. 100: "einer" -> "eine"? (Frage @yur-y)

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#650]

**Comment by ToBeFree** [comment]
@yur-y, hier?

"Stattdessen entschieden die vier sich für eine Reise nach Greater Sudbury, einer der flächenmäßig größten Städte Kanadas."

Ist das nicht richtig?

**Comment by yur-y** [comment]
Ja, nach einiger Recherche stimme ich Dir zu, obwohl das mit meinem Sprachgefühl nicht übereinstimmt. Nach "nach" folgt der Dativ, und da der Artikel "einer" steht, muss die Apposition genauso dekliniert werden wie der Eigenname "Greater Sudbury", der hier dann im Dativ steht. :)

**Comment by ToBeFree** [comment]
Dankeschön 🙂
