### ISSUE TITLE
S. 100: "von Pennsylvania" -> "Pennsylvanias"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#651]

**Comment by ToBeFree** [comment]
Ich befürchte, die beiden Nomen "Grenze Pennsylvanias" sähen nebeneinander durch ihre Großschreibung, anders als beispielsweise im Englischen, merkwürdig aus. Falls das nicht der Fall ist, gerne.

**Comment by yur-y** [comment]
Warum?

**Comment by ToBeFree** [comment]
Es könnte so aussehen, als sei es ein feststehender Begriff aus mehreren Wörtern. Beispiel: "Deutscher Bundestag". Der Eindruck würde verstärkt durch das im selben Satz auftauchende "Allegheny National Forest", bei dem es sich um genau eine solche Konstruktion handelt.

Falls das jetzt wirklich nicht nachvollziehbar ist, gerne ändern. 😄
