### ISSUE TITLE
S. 101: Wo bleibt Pilot 40???

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#652]
Er ist während der gesamten Kanadareise unerklärt abwesend und taucht dann später bei der Rückkehr in die USA wieder auf.

**Comment by ToBeFree** [comment]
Früher hatten wir sogar FBI-Szenen in Deutschland, glaube ich. Wo es geht, habe ich das geändert. In China ist es die CIA, zuvor war es auch dort das FBI.

**Comment by yur-y** [comment]
Klar, aber die vier müssen sich das ja schon fragen nach der Absprache auf S. 100, die eher danach klingt, dass er mitkommt. (Und er gehört ja schon zum "engeren Kreis".) Da müsste vielleicht noch ein Satz von ihm mit einer Begründung rein, warum er lieber in den USA bleiben will.

**Comment by ToBeFree** [comment]
Ah! Ja, stimmt natürlich.
