### ISSUE TITLE
Wiederholt vorkommende Formulierung: "meinte/sagte ... [meist yury] ironisch"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#656]
(einfach mal nach "ironisch" suchen)

Bessere Formulierungen: Die Synonyme [hier](https://www.duden.de/rechtschreibung/spoetteln) z. B., oder je nach Situation spezifische Formulierungen.

**Comment by ToBeFree** [comment]
Oh, da werden wirklich gute Ersatzvorschläge gemacht. "spötteln/spotten", "witzeln" (wobei wir das auch bereits nutzen), "sich mokieren" (haben wir bisher gar nicht, glaube ich), "sticheln".

**Comment by ToBeFree** [comment]
War gar nicht so häufig, aber die Ersetzungsvorschläge waren super. 🙂
