### ISSUE TITLE
Teil 2: Mona Lisa einbauen

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#658]
Die sollte irgendwo zumindest noch mal nebenbei erwähnt werden, damit sie nicht ganz umsonst gestohlen wurde. Vielleicht wird sie im neuen Heim der vier auf Örz aufgehängt?

**Comment by ToBeFree** [comment]
Daran habe ich sogar gedacht, allerdings ziemlich spät. Ich glaube aber, das ist aktuell in Ordnung, sowohl von der Beschreibung her, als auch von der Prominenz der Beschreibung im Roman. Der kleine Überraschungseffekt wirkt nett, hoffe ich.

Siehe: S. 255, vorletzter Absatz

**Comment by ToBeFree** [comment]
Schließen?

**Comment by yur-y** [comment]
Oh, right. Genau an der Stelle wollte ich es auch einbauen. Hätte vielleicht doch noch mal kurz nachschauen sollen, sorry.^^
