### ISSUE TITLE
S. 157: Wörter mit Ä, Ö und Ü

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#660]
"Wir müssen wohl ein bisschen aufpassen, wann und wie hier wir Wörter mit Ä, ö oder ü aussprechen..."

1. "hier wir" -> "wir hier"
2. "Ä, ö oder ü" -> "Ä, Ö oder Ü"
3. Der Satz selbst enthält mehrere Umlaute, aber das ist noch zu rechtfertigen, finde ich, zumal sie ja auch "Ä, Ö oder Ü" sagen muss...
4. Free antwortet darauf sofort mit einem Satz mit 3 Umlauten. :D (Und später hören die anderen auch nicht gerade konsequent auf den Vorschlag)

**Comment by ToBeFree** [comment]
Oh, sehr gut. Folgefehler-Behebungsvorschläge:

**Comment by ToBeFree** [comment]
"Müssen wir nicht" -> "Sollten wir nicht"

**Comment by ToBeFree** [comment]
Ach, warte mal. Die Freunde werden danach unerwartet gefangen genommen. Könnten wir das nicht als Resultat von Frees Unachtsamkeit interpretieren?

**Comment by yur-y** [comment]
Das hatte ich auch überlegt, allerdings sollte die Verbindung dann vielleicht etwas klarer gemacht werden?

**Comment by ToBeFree** [comment]
Klingt eigentlich gut, aber ich habe die Szene nochmal mehrfach durchgelesen und wüsste nicht, wo man das einbauen kann, ohne entweder das Überraschungsmoment zu mindern oder die Satzstruktur merkwürdig aussehen zu lassen. Falls dir noch etwas einfällt, gerne -- ansonsten befürchte ich, dass das eher so bleiben muss, und dass der Leser im Zweifelsfall selbst schlussfolgern muss. Für die weitere Handlung ist der Beweggrund ja auch irrelevant; die Freunde fliehen unabhängig davon.

**Comment by yur-y** [comment]
Hast mich überzeugt. :)
