### ISSUE TITLE
S. 16: "Brücke! Kein Zutritt!" -> "Brücke -- kein Zutritt!" o. ä.

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#662]
Das erste Anführungszeichen wirkt auf mich etwas merkwürdig.

**Comment by ToBeFree** [comment]
Stimmt, das wirkt eher lustig als sinnvoll. Man stelle sich beispielsweise vor, auf dem Schild stünde nur das Wort "Brücke!". 🙂
