### ISSUE TITLE
S. 181: "Büro-Hochhaus" -> "Hochhaus"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#663]
"Leer stehend" an der gleichen Stelle ist ja leider Duden-Empfehlung. ;)

**Comment by ToBeFree** [comment]
Können wir machen; ursprünglicher Gedanke war dabei, glaube ich, die Lesbarkeit.

https://www.duden.de/rechtschreibung/Hochhaus

Wir fügen ein drittes Nomen zu einem festen Duden-Eintrag hinzu. Begründbar wäre ein Bindestrich nach folgenden Regeln:

**Comment by ToBeFree** [comment]
https://www.duden.de/sprachwissen/rechtschreibregeln/bindestrich

> D 22:
> 
> Man kann einen Bindestrich in unübersichtlichen Zusammensetzungen setzen <§ 45 (2)>.

**Comment by yur-y** [comment]
Zulässig ist das auf jeden Fall. Ich finde es halt ohne Bindestrich im Zweifel stilistisch schöner, bin da aber auch nicht passionate, also wenn Du ihn behalten willst, können wir ihn gerne behalten.

**Comment by ToBeFree** [comment]
Echt? Ok, dann ohne Bindestrich. Wichtig ist mir das nämlich auch nicht, aber dann im Zweifel für den Standard. 🙂

**Comment by ToBeFree** [comment]
😄 👍

**Comment by ToBeFree** [comment]
Dass darin Büros enthalten sind, wird im nachfolgenden Satz viel schöner deutlich.
