### ISSUE TITLE
S. 190: "sein lassen" -> "lassen"?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#665]
Finde "sein lassen" in zwei Wörtern hier verwirrend (ist aber vom Duden so empfohlen), aber vielleicht liegt es nur an mir?

**Comment by ToBeFree** [comment]
Vorsichtige Zustimmung, aber im vorherigen Satz steht "mit dem Pentagon kollidieren lassen". Der Ersetzungsvorschlag macht daraus eine möglicherweise verwirrende Wortwiederholung.

**Comment by ToBeFree** [comment]
Ich glaube, "sein lassen" ist ganz in Ordnung.
