### ISSUE TITLE
S. 203: "in 70 Jahren"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#667]
Vielleicht ist der Zeitraum etwas zu kurz? In 343 Jahren?

**Comment by ToBeFree** [comment]
Das Schöne an "70" ist, dass es auch im Dezimalsystem eine runde Zahl ist. Ich habe jetzt 343 eingetragen, aber vielleicht fällt uns kurzfristig noch etwas besseres ein.
