### ISSUE TITLE
S. 215: "Örz-Smartphone" -> "Smartphone"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#668]

**Comment by yur-y** [comment]
Hm, finde "Smartphone" nicht ideal, aber passt. :)

**Comment by ToBeFree** [comment]
Smärtphöne vielleicht. :) Aber ich würde sagen, "Smartphone" sieht dort trotzdem besser aus als "Smärtphöne".

**Comment by ToBeFree** [comment]
(außerdem verstieße das "e" am Ende vermutlich gegen die Sprachstandards von Örzlängü und wäre schon allein deshalb irgendwie merkwürdig)
