### ISSUE TITLE
S. 179: "quantenmechanische Beschreibung subatomarer Partikel als Wahrscheinlichkeitswellen"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#670]
Ich kenne mich in der Physik nicht gut aus. Aber die Fragestellung klingt, als läge sie relativ nah an heutiger Erd-Physik. Die Frage ist, ob das angesichts ungeheurer Fortschritte der Äöüzz im Bereich der Technik plausibel ist oder ob die Quantenmechanik in der Örz-Physik nicht längst von fortgeschritteneren Paradigmen abgelöst wurde, genauso wie wir uns heute nicht mehr mit Newtons Fragestellungen beschäftigen.

**Comment by ToBeFree** [comment]
Nicht ganz lösbar, wenn es Sinn ergeben und trotzdem toll klingen soll. Ein neuer Versuch mit der "riemannschen Vermutung", diesmal auch kreativer von mir zusammengebastelt.
