### ISSUE TITLE
S. 225: "Zwanzig, nein -- zweihundert..." -> "Zwanzig, nein, zweihundert..."

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#671]

**Comment by yur-y** [comment]
Scheint die üblichere Schreibweise zu sein, siehe z. B. https://www.google.com/search?q="hundert+nein+tausend"

**Comment by ToBeFree** [comment]
_Der Link ist kaputt, weil GitHub die Anführungszeichen am Ende nicht als Teil der URL erkennt; hier ist einer, der funktioniert:  [https://www.google.com/search?q="hundert+nein+tausend](https://www.google.com/search?q=%22hundert+nein+tausend")_

**Comment by ToBeFree** [comment]
Ja, sieht so auch schöner aus. :)

**Comment by ToBeFree** [comment]
Ich bin nur gar nicht darauf gekommen. 😄

**Comment by ToBeFree** [comment]
Ich bin nur gar nicht daraufgekommen. 😄
