### ISSUE TITLE
S. 226: "geplant hatte" -> "plante"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#672]
Wieso "hatte"? Während des Raumkampfs wird er ja wohl andere Sorgen gehabt haben...

**Comment by ToBeFree** [comment]
Ah, ich dachte, vor dem Kampf oder so. Ja, "plante" ist wohl besser, weil es nicht den Eindruck erweckt, die Planung sei während des Kampfes geschehen. Das wäre nämlich wirklich merkwürdig und dann wohl kaum "enthusiastisch".
