### ISSUE TITLE
S. 227: "Inzwischen wusste man, dass diese astronomischen Einzelgänger sogar häufiger vorkamen als Sterne"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#673]
Auf der Erde gilt dieser Wissensstand mittlerweile als überholt: https://www.scientificamerican.com/article/wandering-in-the-void-billions-of-rogue-planets-without-a-home/
https://www.skyandtelescope.com/astronomy-news/rogue-planets-not-plentiful/

Sollen wir das "inzwischen" als Indikator für den Örz-Wissensstand ansehen oder wie gehen wir damit um?

**Comment by ToBeFree** [comment]
Oh, Mist. Gehen wir mal davon aus, dass die neueren Erkenntnisse richtig sind. Dann sollten die Äöüzz aber nichts "wissen", was sachlich bereits jetzt als falsch bekannt geworden ist.

Wir könnten den Satz einfach weniger "stark" machen.

"Inzwischen wusste man, dass diese astronomischen Einzelgänger beinahe so häufig vorkamen wie Sterne"

Das ist dann subjektiv und könnte durch neue Erkenntnisse der Äöüzz begründet werden.
