### ISSUE TITLE
S. 239: Ergibt es Sinn, dass Raumschiffe "Scheinwerfer" haben?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#674]
Ich meine, im Allgemeinen gibt es halt nicht so viel anzuleuchten.^^

**Comment by ToBeFree** [comment]
Im leeren Weltall oder in Raumkämpfen nicht, das stimmt. :)

Zum Einsammeln von Weltraumschrott, zur Unterstützung von Bergungsarbeiten, zur Sichthilfe auf Planeten oder beim Flug über Planetenoberflächen, zur Beleuchtung auf Raumhäfen können Scheinwerfer aber nützlich sein.

Und sie sehen gut aus! https://inara.cz/data/ships/131/131492x2048.jpg
