### ISSUE TITLE
S. 245: "E-Mails an Orakel" -> "E-Mails an 'Orakel'", "an den vermeintlichen Orakel" o. ä.?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#675]

**Comment by ToBeFree** [comment]
Naja, der Leser weiß längst, dass es wirklich Orakel ist. Der Erzähler spricht hier zwar aus Islands Perspektive, aber eine derartige Distanzierung von der Realität könnte den Eindruck erwecken, als sei wirklich jemand anderes gemeint.

**Comment by ToBeFree** [comment]
Das Kapitel beginnt zudem mit einem sehr ähnlichen Satz; den müsste man zumindest im gleichen Schritt korrigieren.

**Comment by ToBeFree** [comment]
Ohne Korrektur geschlossen, gerne protestieren.
