### ISSUE TITLE
S. 245: "den 'ganzen Schotter'" -> "den 'Haufen Schotter'"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#676]

**Comment by ToBeFree** [comment]
Oh, das wäre mir nicht aufgefallen. Alternativ hätte man überlegen können, nur das Wort "Schotter" in Anführungszeichen zu setzen. Aber die hier vorgeschlagene Lösung finde ich noch besser.

**Comment by ToBeFree** [comment]
...oder doch die Alternative, weil es im Satz schöner aussieht?
