### ISSUE TITLE
S. 251: Wolfgang ruft auf Örz an?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#681]
Wie soll das gehen?

**Comment by ToBeFree** [comment]
Das ist seit jeher meiner Meinung nach Orakels genialster IA-Witz überhaupt. 😋 

Wird sogar im Bonusteil des Hauptbuches erwähnt, weil es so schön ist. Falls du nicht energisch protestierst, bleibt das genau so bestehen. 😄
