### ISSUE TITLE
S. 255: "Glücklich lehnte Orakel sich zurück..."

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#682]
Ich mag diesen Abschnitt sehr und würde ihn auch sehr gerne irgendwo behalten, bin mir aber nicht sicher, ob er hier passt. Die vier wurden halt gerade vor Gericht verurteilt, da scheint die extrem gute Stimmung etwas fehl am Platze.

**Comment by ToBeFree** [comment]
Wow, sieht die Gesetzesformatierung auf Papier gut aus. 👍 

Ja, der Einwand ist definitiv nachvollziehbar. Ich glaube aber, das ist in Ordnung: Seit dem Gerichtsprozess sind einige Tage vergangen, der Alltag läuft wieder, und Orakel ist generell ein gemütlicher Mensch, der sich von solchen Kleinigkeiten nicht stressen lässt. Es ist der extrem knappe Erzählstil des Romans, der den Eindruck erweckt, Orakel sei gerade verurteilt worden und lehne sich direkt im Anschluss daran gemütlich zurück.

**Comment by ToBeFree** [comment]
Nö pröblem (wöntfix)?
