### ISSUE TITLE
S. 257: "USA-Flagge" -> "US-Flagge" oder "amerikanischen Flagge"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#683]

**Comment by ToBeFree** [comment]
Ah, wusste ich gar nicht. Aber das scheint tatsächlich üblich zu sein:

https://www.nzz.ch/panorama/trump-malt-die-us-flagge-falsch-aus-ld.1414768

Da der Satz so lang ist, würde ich von deinen Vorschlägen eher die "US-Flagge" nehmen.
