### ISSUE TITLE
S. 264: "Wächter" -> "Wärter"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#684]
https://en.wiktionary.org/wiki/Gef%C3%A4ngnisw%C3%A4rter

**Comment by ToBeFree** [comment]
Oh, tatsächlich. Den "Gefängniswärter" gibt es im Duden, den "Gefängniswächter" nicht. Vermutlich stünde ein "Wächter" auch eher draußen vor der Tür.
