### ISSUE TITLE
S. 273: "Cool, dass die uns mitgenommen haben" -> "Gut, dass die uns mitgenommen haben"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#686]
Auch hier scheint mir "cool" angesichts der sehr realen Sorge, dass die Erde demnächst zerstört wird, eher unpassend.

**Comment by ToBeFree** [comment]
Ja, guter Einwand. Ich glaube, das Wort "cool" ist noch ein Überbleibsel aus der Originalfassung, die wir als Kinder geschrieben haben.
