### ISSUE TITLE
S. 279: "Erdzeit" -> "Bordzeit"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#687]
Es gibt keine "Erdzeit". Da die fünf sich zuletzt in Washington aufgehalten haben müssen, dürfte wohl die dortige Ortszeit relevant sein.

"EST"? "Eastern Standard Time"? "Ostküstenzeit"? "Washingtoner Zeit"? Mich überzeugt gerade nichts so richtig, aber vielleicht hast Du ja noch ne Idee. :)

**Comment by ToBeFree** [comment]
Oh, sehr gut.

Bordzeit. Es geht ja gar nicht um die Erde, sondern den künstlichen Tagesrhythmus auf dem Raumschiff. :)
