### ISSUE TITLE
S. 282: "Die hundert Prozent Wahlstimmen..."

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#688]
Erstens überzeugt mich der Satz inhaltlich nicht so wirklich (warum sollten nur 2% Island wählen, der gerade die Welt gerettet hat? Wie soll er weltweit so viele Stimmen kaufen?). Zweitens und wichtiger: Soll der Satz schon die Wahl selbst beschreiben? Oben geht es ja nur um eine Umfrage. Aber eine Seite weiter wird dann einfach davon ausgegangen, dass Island gewählt wurde. Das Plusquamperfekt im Satz irritiert halt auch irgendwie.
Wenn es um die Wahl selbst geht, würde ich das vielleicht an der Stelle deutlicher machen.

**Comment by ToBeFree** [comment]
Ah, das war ja ursprünglich als Witz gemeint:

> "Die hundert Prozent Wahlstimmen hatte Island sich teilweise erkauft, aber **der Großteil (zwei Prozent)** wählte Island freiwillig."

**Comment by ToBeFree** [comment]
(verklickt)

**Comment by ToBeFree** [comment]
Zwei Prozent sind sicherlich zu wenig. Lass uns aus dem schlechten Witz einen gesellschaftskritischen Seitenhieb mit historischen Implikationen machen: 88 Prozent.

**Comment by ToBeFree** [comment]
(Anmerkung: Das war zufällig Issue-Nummer 688.)
