### ISSUE TITLE
S. 290: "'Außer, ihm geht die Energie aus.'" - Bin mir unsicher, wie es richtig heißen muss.

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#690]
Gehört das Komma da hin oder nicht? Ich habe wirklich keine Ahnung und kurzes Googeln ergab auch nichts. Vielleicht geht einfach beides.^^

**Comment by ToBeFree** [comment]
Wenn man "Außer" durch "Es sei denn" ersetzt, wird die Kommasetzung eindeutig. Vielleicht sollten wir das einfach tun. :)
