### ISSUE TITLE
S. 308: "Island ist gestern ... zum Weltherrscher gewählt worden"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#695]
Ich dachte, er sei nun schon auf S. 282 gewählt worden?

**Comment by ToBeFree** [comment]
Ja, Mist. Die Freunde wissen ja auch längst davon und waren seitdem schon einmal auf der Erde. Die Wohnzimmer-Szene muss vermutlich gekürzt werden. 😐

**Comment by ToBeFree** [comment]
Problem gelöst. Zuerst Interimspräsident, dann Machtsicherung

**Comment by ToBeFree** [comment]
Problem gelöst. Island war vorerst Interimspräsident, dann kam seine Machtsicherung.
