### ISSUE TITLE
S. 312: "der rote Feuerball"?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#697]
Ich bin mir nicht ganz sicher, ob es passt, das Raumschiff als "Feuerball" zu bezeichnen. Wir hatten die Bezeichnung schon mal für Sterne (wo sie passt), und ich assoziiere damit, dass das Raumschiff brennt?

**Comment by ToBeFree** [comment]
Der Feuerball entsteht durch Reibungshitze. Das Raumschiff fliegt wie ein Komet durch die Atmosphäre. 🙂

**Comment by ToBeFree** [comment]
Ich glaube, das passt. Die Luft wird zu einem Plasma, die Außenhülle glüht, oder so ähnlich.
