### ISSUE TITLE
S. 186: Wirklich, "Lichtjahr" ist mit einem julianischen Jahr definiert?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#698]
Ich dachte beim Nachrechnen der "4,6692-millionenfachen Lichtgeschwindigkeit" erst, die letzte Nachkommastelle stimme nicht. Dann habe ich gelernt, dass ein Lichtjahr tatsächlich die Strecke ist, die das Licht in - weder einem natürlichen noch einem gregorianischen Jahr noch in 365 Tagen, sondern whyever - einem julianischen Jahr zurücklegt. :D

**Comment by ToBeFree** [comment]
Hauptsache, du rechnest das nach. 😅

Das wusste ich übrigens auch nicht. WolframAlpha hat mir diesen Schritt abgenommen. Im Nachhinein bin ich froh, dass ich wirklich mit "lightyears/hour" gerechnet habe.

**Comment by ToBeFree** [comment]
Hauptsache, du rechnest das nach. 😅

Das wusste ich übrigens auch bis heute nicht, dankeschön. WolframAlpha hat mir diesen Schritt abgenommen. Im Nachhinein bin ich froh, dass ich wirklich mit "lightyears/hour" gerechnet habe.
