### ISSUE TITLE
S. 313: "Zwei Meter pro Femtosekunde" -> "Zwei Billiarden Meter pro Sekunde"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#699]
Oder "zwei Billionen Kilometer pro Sekunde"? Man kann sich zwar unter beidem nichts vorstellen, aber ich finde die letzteren beiden persönlich noch etwas "anschaulicher", sofern man davon reden kann.

**Comment by ToBeFree** [comment]
Ja, stimmt schon. Dann würde ich Meter pro Sekunde verwenden.

**Comment by ToBeFree** [comment]
Alternativ "Kilometer pro Stunde" für den Auto-Vergleich. :)
