### ISSUE TITLE
S. 315: "aber yury hatte das letzte Wort: »Erstens wollen wir keinen Atomkrieg, zweitens sind die Russen nicht so blöd, einen solchen Krieg gegen die USA anzufangen, drittens hat China auch Atomwaffen und viertens fliegen wir sowieso nach China!«" -> "aber Orakel und yury stimmten Free zu."

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#700]
Die Aussage ist unlogisch, passt nicht wirklich in das Setting (es gibt ja nicht mehr wirklich autonome Nationalstaaten, weil Island alles kontrolliert) und außerdem tritt yury m. E. anderswo im Roman schon oft genug herrisch auf.

**Comment by ToBeFree** [comment]
Klingt gut 🙂
