### ISSUE TITLE
S. 319: Streiche "geradezu ein Hochhaus, ", ersetze durch "Das CDWAI war ein überdimensionales Hochhaus"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#701]
"Geradezu" klingt so, als wäre das etwas unglaublich Außergewöhnliches, oder?

**Comment by ToBeFree** [comment]
Vielleicht "Das CDWAI war ein überdimensionales Hochhaus"?

**Comment by yur-y** [comment]
Passt :)
