### ISSUE TITLE
S. 321: "yury hatte vorgeschlagen" -> "Free/Orakel/Alexandra hatte vorgeschlagen"?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#702]
Mal etwas Abwechslung?

**Comment by ToBeFree** [comment]
Orakel könnte passen, denn der hat sich dann gleichzeitig überlegt, dass man dort mit einem Flugzeug ganz gut hinfliegen könnte. Außerdem macht Orakel vielleicht sowieso zu selten gute Vorschläge.
