### ISSUE TITLE
S. 322: "In einwandfreiem Hindi" -> "In einwandfreiem Englisch"

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#703]
Es ist extrrem unplausibel, dass die vier einwandfreies Hindi sprechen sollten, und außerdem dürfte man an einem indischen Flughafen (!) mit Englisch sehr gut durchkommen. ;)

**Comment by ToBeFree** [comment]
Dafür ist das kleine Übersetzungsgerät da, das Orakel aktiviert. Vermutlich haben die Freunde ihre Übersetzungsgeräte ebenfalls mitgenommen. 🙂

**Comment by yur-y** [comment]
Oh, ups, sorry. Lesen hilft. :D
