### ISSUE TITLE
S. 324: Mithören des Gesprächs

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#704]
Wenn "die Stimme" (wie auch immer das genau funktionieren soll) mithört, wie David Peters "Fast-Food-Restaurant" statt "McIsland" sagt, wieso hört sie dann nicht auch das ganze Gespräch mit und die vier werden unmittelbar gefasst? Später kommen zwar tatsächlich Truppen in Peters' Haus, trotzdem ist es in meinen Augen logisch "gefährlich", eine solche "Allmacht" einzuführen.

**Comment by ToBeFree** [comment]
Vielleicht wird Peters – und nur Peters – persönlich durch irgendwelche raffinierte Technik überwacht.

Wir können die Stelle aber relativ einfach ersetzen. Peters kann die Freunde zum Beispiel aus Angst vor Beobachtern in sein Geheimversteck einladen.
