### ISSUE TITLE
S. 327: "Wir müssen also die aktuelle Regierung Deutschlands stürzen." - Na ja, was denn sonst? Sie müssen die aktuelle Weltregierung und alle ihre Helfer in allen pseudo-autonomen Nationalstaaten stürzen. Irgendwie ist die Frage komisch.

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#705]

**Comment by ToBeFree** [comment]
Ja, stimmt schon.

Ich könnte mir aber vorstellen, dass z.B. BIDWA und CDWAI so etwas Ähnliches wie das "Haus der Europäischen Union" in Berlin sind. BIDWA und CDWAI wären dann nationale Vertretungen der Weltregierung, aber kein offizieller Ersatz der nationalen Regierung.

In Deutschland hingegen hat Thilo Alfred persönlich für Island die Macht vollständig übernommen.
