### ISSUE TITLE
S. 330: "fünf Kilogramm Fast Food" -> "zehn BigIslands"?

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#707]
Kilogramm ist hier eine komische Maßeinheit.

**Comment by ToBeFree** [comment]
Generell ja, aber an der Stelle wirkt es möglicherweise wie eine Wortwiederholung ("McIsland", "BigIslands")? Als Übertreibung und gleichzeitig Wiederholungsvermeidung könnten Kilogramm vielleicht doch ganz nützlich sein.

**Comment by yur-y** [comment]
Ich fände die Wiederholung an der Stelle nicht schlimm, aber so lassen wäre auch OK.

**Comment by ToBeFree** [comment]
Gucke ich mir beim Einarbeiten der Änderungen einfach nochmal in Ruhe an. :)

**Comment by ToBeFree** [comment]
Geschlossen ohne Änderung, gerne protestieren. 😉
