### ISSUE TITLE
S. 337: "um dann ganz in Ruhe einzuschütten" -> "um diese dann ganz in Ruhe zu befüllen" + Satz aufteilen

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#710]
OK, ich war lange nicht in einem McDonalds oder so, aber eigentlich bekommt man einfach nen Becher und befüllt ihn dann selbst, oder? Davon würde ich absehen; aber dass die Angestellten (aus einer Flasche) in einen Becher "einschütten", glaube ich kaum.

Vielleicht sollten wir auch zwei Sätze daraus machen?

**Comment by ToBeFree** [comment]
Ich glaube, es hängt von der Filiale ab, ob der Getränkespender vor oder hinter der Theke steht. Aber natürlich "schüttet" da niemand etwas ein. 😃

**Comment by ToBeFree** [comment]
Der Satz ist momentan wirklich zu lang.

**Comment by ToBeFree** [comment]
Der Satz ist momentan wirklich irgendwie zu lang.
