### ISSUE TITLE
29. Intermezzo: Kapitellänge

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#711]
Sollten wir daraus nicht eher einen mit drei Unendlichzeichen getrennten Abschnitt machen? Oder warum ist ein Kapitel so viel kürzer als alle anderen?

**Comment by ToBeFree** [comment]
Achso, das fand ich eigentlich ziemlich elegant, als Ausnahmefall. Die damit verbundenen Seitenumbrüche wirken auf mich stilvoll.

Entstanden ist das dadurch, dass ich den Text eben zwischen zwei Kapiteln einfügen wollte, die eigentlich direkt aufeinander aufbauen.

**Comment by ToBeFree** [comment]
Ohne Änderung geschlossen, damit kein Chaos entsteht :)
