### ISSUE TITLE
S. 345: "www.bankofamerica.com" -> "www.grub.isl" +Folgeänderung

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#712]
Vorteil: Keine Werbung für ein privates Unternehmen und ein Rückbezug auf die Grand Unified Bank.

Folgeänderung: Ersetze auf S. 346 "Bank of America" durch "Grand Unified Bank"

**Comment by ToBeFree** [comment]
Ah, an die GRUB hatte ich gar nicht mehr gedacht. 😄
