### ISSUE TITLE
Äüörüzü again/Beschreibung der Örz-Katze (Frage @yur-y)

### ISSUE THREAD

**Issue by yur-y** [InfiniteAdventures/ia-trilogy#718]
Kann gut sein, dass wir das schon mal hatten, weil wir schon oft über diese Katze diskutiert haben. ;)
Ich finde es schade, dass die Beschreibung der Örz-Katzenart nun ganz raus ist (ich denke, bei der ersten Erwähnung auf S. 189 könnte sie z. B. passen). Und daher ist auch das *üüüü* gerade vermutlich für Außenstehende nicht verständlich.

**Comment by ToBeFree** [comment]
Man könnte natürlich das "üüüü" durch "miau" ersetzen. 😉 

Bei "üüüü", "miau" oder "meow" handelt es sich doch eigentlich nur um eine sprachliche Umschreibung des vermutlich weltweit gleichen Tierlauts. Es wäre also nachvollziehbar, wenn die Katze "miau" macht.

Wir können aber gerne auch die Katzenart beschreiben. Ich befürchte nur, dass es schwer wird, eine Beschreibung auf S. 189 unterzubringen, ohne dass die Szene dadurch merkwürdig unterbrochen/gestreckt wird.

**Comment by yur-y** [comment]
Ich dachte, "üüüü" soll gerade verdeutlichen, dass Örz-Katzen anders klingen als Erdkatzen. ;)

**Comment by ToBeFree** [comment]
Das können sie natürlich auch gerne tun. Dann sollten wir das tatsächlich kurz erwähnen. 😄

**Comment by ToBeFree** [comment]
Ich schlage vor, doch "miau" zu verwenden und daraus keine große Änderung mehr zu machen.

**Comment by ToBeFree** [comment]
"miau" eingebaut. Schließen?

**Comment by yur-y** [comment]
OK

**Comment by ToBeFree** [comment]
Dankeschön 🙂
