### ISSUE TITLE
Ankündigung: Repository-Cleanup

### ISSUE THREAD

**Issue by ToBeFree** [InfiniteAdventures/ia-trilogy#722]
An alle von euch, die mit "git clone" oder der Fork-Funktion von GitHub eine Kopie dieses Repositories erstellt haben: Euer Exemplar wird ungültig. Ihr müsst die Kopie von der Festplatte löschen und das Repository erneut herunterladen, ansonsten wird Git sich mit Fehlermeldungen beschweren. :)

Hintergrund: Die Commit-History wird aufgeräumt, alte Dateien werden durch Platzhalter ersetzt.

**Comment by ToBeFree** [comment]
Fertig aufgeräumt; betrifft jetzt @niansa @yur-y

**Comment by ToBeFree** [comment]
Betrifft: @yur-y @niansa

**Comment by niansa** [comment]
Vielen dank für den Hinweis!

**Comment by ToBeFree** [comment]
Gerne, danke fürs Herunterladen/Klonen! Eine große Hilfe war der GitHub-Support, der auf Nachfrage die Pull Requests gelöscht hat. Die Pull-Request-Repositories wurden als "branches" beispielsweise heruntergeladen, wenn man "git clone --mirror" eingesetzt hat. Von 3 GB auf 300 MB ist ein ziemlich beeindruckender Sprung.

**Comment by ToBeFree** [comment]
Gerne, danke fürs Herunterladen/Klonen! Eine große Hilfe war der GitHub-Support, der auf Nachfrage die Pull Requests gelöscht hat. Die Pull-Request-Repositories wurden als "branches" beispielsweise heruntergeladen, wenn man "git clone --mirror" eingesetzt hat. Von 3 GB auf 300 MB fand ich ziemlich beeindruckend.
