### ISSUE TITLE
Infiniteadventures Webseite down?

### ISSUE THREAD

**Issue by niansa** [InfiniteAdventures/ia-trilogy#723]
Wenn ich sie aufrufe, kommt:

"Wie es aussieht, wurde an dieser Stelle nichts gefunden. Möchtest du eine Suche starten?"

**Comment by ToBeFree** [comment]
Oh. 😅 

@niansa Die Seite wird um "00:01 Uhr" freigeschaltet, aber durch die Zeitumstellung und die Nicht-UTC-Zeitzone (das Blog nutzt UTC+0) entspricht das einer lokalen Zeit von 02:01 Uhr.

**Comment by ToBeFree** [comment]
Oh, das war mir nicht bewusst. Danke. 😅 

@niansa Die Seite wird um "00:01 Uhr" freigeschaltet, aber durch die Zeitumstellung und die Nicht-UTC-Zeitzone (das Blog nutzt UTC+0) entspricht das einer lokalen Zeit von 02:01 Uhr.
