### ISSUE TITLE
Information an @ToBeFree

### ISSUE THREAD

**Issue by niansa** [InfiniteAdventures/ia-trilogy#727]
Hi! Ich nochmal. Ein Hinweis an dich, meine neue E-Mail Addresse lautet `anton-sa@web.de`, mein Mailserver war mir zum Schluss doch zu viel Arbeit, vor allem nachdem ich ihn versehentlich gelöscht habe. :wink: 
Wenn möglich das hier nach dem lesen löschen. Wenn nicht ist das auch egal, bekomme eh massenhaft Spam an die Addresse. Ich sollte mich vielleicht mal um eine neue kümmern. :laughing:

**Comment by ToBeFree** [comment]
Danke :) Hab dir geantwortet
